### ISSUE TITLE
Slicer Master Level 2

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1030]
I made a Bisect slicer setup like below:
https://gist.github.com/enzyme69/ceb19e0dca7ff165e351d664f176d02e

Now I was wondering if we could have the slicer to do multiple cuts and resulting with a complete sliced object?

The video:
https://www.youtube.com/watch?v=zml6gSVK-Rs

**Comment by zeffii** [comment]
I should really add Frame color storage...

![image](https://cloud.githubusercontent.com/assets/619340/21110475/9e049b94-c09d-11e6-8578-596034b44d7e.png)

https://gist.github.com/4ba6dc7f3086aba30670cc0b17a82c0d

**Comment by zeffii** [comment]
Nothing wrong with your current approach, that's the limit of the bisect node, because this node is a wrapper around the `bmesh.bisect_plane`, and that's all it offers. 

Your node tree gives you a fair idea of what the code would need to look like for a proper Nodification of what you want to do. Two passes through the bisect code, with two matrices to represent slice planes and slice positions (plane_normal, and plane_position).

There's many possible ways to implement this, we'd always want something slightly different for the next project. Tho, possibly, if I had to propose a node interfacce for slice_repeats it would take geometry in and possibly a list of matrices, and slice the geomtry from 

    [matrix_0 -> matrix_1, then cap both]
    [matrix_1 -> matrix_2, then cap both]
    [matrix_2 -> matrix_3, then cap both]
    [matrix_3 -> matrix_n, then cap both]

but.. that's a feature request for a later stage, or a script node... or your first Node :)

**Comment by nortikin** [comment]
it is subject for recursion. why not make monad recursions?

**Comment by enzyme69** [comment]
@nortikin Monad Recursion sounds like awesome. 

http://www.sidefx.com/docs/houdini15.0/model/looping

![screen shot 2016-12-13 at 23 14 24](https://cloud.githubusercontent.com/assets/3952687/21140011/f0a7c7f8-c189-11e6-9899-6e5a4492df2e.png)

**Comment by nortikin** [comment]
this looks like dream. if i will understand monad (did not investigate code yet) maybe will say exactly what we can do with it.
it seems that core of sverchok have to be made in redux way than. all defs, as we conversated long time ago, have to be separated and we maybe can make script output to reuse layout as script or banch of scripts.
