### ISSUE TITLE
What is this Print Dump

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1032]
Not sure since when... perhaps since last time I tried to debug crashing stuff, Sverchok seems to be printing a lot of dump into the Console:

https://gist.github.com/enzyme69/c7d314e7d79c94d2ff4b1a010a1e8e59

How to turn it off?

**Comment by nortikin** [comment]
value error in import!!!
omg

**Comment by zeffii** [comment]
That's normal output for IOJson import. It will do this all the time when you Import json. yes, really yes.

There's an error, simple to fix in the `.json`  directly 
```
Unexpected error: <class 'NameError'>
on line:  11
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.78/scripts/addons/sverchok-master/nodes/generator/script1_lite.py", line 283, in process_script
    exec(self.script_str, locals(), locals())
  File "<string>", line 11, in <module>
NameError: name 'parameters' is not defined
```
I modified SNLite a little bit since that gist was created, probably. If your script uses the variable 'parameters' , then the 'inject' directive must be added into the header of the snlite script.  See

https://github.com/nortikin/sverchok/issues/942#issuecomment-264705956

Now you can edit the json yourself by looking for the script inside the json and adding `inject` yourself, or paste a link to the json in question and i'll show how to edit it. Then you can edit others that give this error the same way.

**Comment by zeffii** [comment]
I should really include a print line to show the origin of the json, so if it was online/gist then it would print the url directly into the console/terminal. so it would say

```
 ______ _    _ _______  ______ _______ _     _  _____  _     _
/______  \  /  |______ |_____/ |       |_____| |     | |____/
______/   \/   |______ |    \_ |_____  |     | |_____| |    \_
initialized.
############ 0.062
origin: gist:  https://gist.github.com/3f84f2e35aab21b40fe28e94c222d7ed
calling sv_init for LineNode
Skipping update of NodeTree
Skipping update of NodeTree
Skipping update of NodeTree
Skipping update of NodeTree
```

**Comment by zeffii** [comment]
@enzyme69 is this the output you get when you import a specific gist using iojson panel? a link to the gist would be great.

Lots of debug printing should (perhaps) be off by default, but.. on the other hand.. sometimes you wish you debug info enabled in hindsight - this is probably why it's on by default.

i'm all for reducing the amount of debug prints. Maybe we should use the [logging](https://docs.python.org/3.5/library/logging.html) library
