### ISSUE TITLE
Paper Bending

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1050]
Just wondering if this kind of paper bending is something that's interesting to do using Sverchok?
http://schnellhammer.net/blog/2011/06/skoda-paperworld/

We could probably use "Bisect" or something similar to make the cutting and then the bending.

**Comment by nortikin** [comment]
no need cutting. it is lowpoly models but simulated in GH with two plugins - first finds internal and external lines convex and inner (mount and how this calls) and second plugin is phisics simulation.

 https://yandex.ru/images/search?text=unfolding%20structures&parent-reqid=1482147260743784-825471630734195913815567-man1-3582

**Comment by nortikin** [comment]
i cannot imagin what to start here, complicated some. But whanted long time

**Comment by enzyme69** [comment]
I remember folding case where every polygon bits have Bones or Joints. Maybe Add-On or Blender.

**Comment by zeffii** [comment]
the video shows softimage ICE, which has the ability to convert polygons to NURBS surfaces. This also allows the surfaces to be folded with a radius. Blender is at a distinct disadvantage in this area. If someone really wanted it they would simulate it with bisect and transforms and edge bevels, but it would result in polygons.

totally a job for a dedicated Add-on or special node group.

i'll close this issue, not because it's not interesting (it is), but because there's only limited energy and hours in a day.
