### ISSUE TITLE
Exploring SV Object ID Bone Access

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1067]
Related to:
https://github.com/nortikin/sverchok/issues/939

I think I  started to get a hang of this Object ID thing.... testing it on BONES (Pose Bones)

![screen shot 2016-12-28 at 22 19 56](https://cloud.githubusercontent.com/assets/3952687/21520875/e738267c-cd4b-11e6-8c61-d21fdbf77ce9.png)

- Is there any more useful trick?
- why sometimes we use #
- when Filtering by NAME, sometimes using 'Cu' will select Cube, Cube.000, Cube.001 when I especially only want an object name 'Cu'.

@Kosvor2 what have you created using Object ID node so far, I am very curious. Are you Peter Shipkov?

**Comment by Kosvor2** [comment]
Instead of writing `str(XYZ)` in Formula node, you can just write `rotation_mode = "XYZ"` inside of Set node. Just dont connect value sockets when doing like that.

when invalue socket is connected node doing this `Object.Something = Value` where `Something` is what you write inside of text box. # simbol in Python makes everything what is writen after it irrelewant. So when we use it we say to node "Dont do `= Value` thing. I will do it myself inside `Something`"

First filter out all "Cube" names, then filter out "Cu" name (use two Filter nodes connected to each other).

No, no... nothing absolutely. I just think what nodes are cool. And Sverchok was first addon for blender with nodal interface so it bring my attention back in 2013.

**Comment by enzyme69** [comment]
Thanks for tips on rotation_mode = "XYZ"!

Yes, this Object ID thing surprises me in a way that I never think before. It all probably can be done with Python scripting, however, this makes everything different :) 

Cheers, will explore more. But will make video about this.
