### ISSUE TITLE
Mesh Linter node.

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1162]
### What's a mesh linter?

it checks the input mesh for mistakes, 
   - polygons/edges referencing vertex indices that don't exist.
   - negative values polygon/edge index lists.
   - edge lists with sublists that are larger than length 2. 
   - polygon lists with sublists that are smaller than 3
   - duplicate polygons / edges

The node could display info and pass through only the valid parts of incoming meshes. This would be a relatively slow node, designed only for automated sanity checking and logic correction ... not as a blackhole out of which your broken input emerges without the most broken bits. I'm sure it will be used like that.. but that's not the prime directive of the node.

**Comment by ly29** [comment]
Also check vertices for nan and inf I guess.

**Comment by ly29** [comment]
This is just kinds of problem can become really beautiful and clear code in python.

1 and 2 are really easy ```all(idx in range(len(vertices)) for idx in face/edge)```, obviously the range is created beforehand

3,4 ```(edge for edge in edges if len(edge) == 2)``` something like this

5 the duplication part just ```set(tuple(sorted(face)) for face in faces)``` because no face can contain the same vertex but in a different order and check each edge/face for membership.

https://github.com/nortikin/sverchok/blob/master/nodes/modifier_change/polygons_to_edges.py#L25-L38

**Comment by nortikin** [comment]
nesty depth's inconsistency?

**Comment by nortikin** [comment]
5 maybe set()
