### ISSUE TITLE
Image Decompose RGB into New Color Vertex node failed - Voxel thing

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1171]
Surprisingly failed maybe because of NumPy stuff.

Trying to streamling the creation of 3D Voxel from Pixel Art in one beautiful node tree.

1. Source image using Image Decomposer
2. Generate a single object with multiple boxes OUT, merge
3. Get Object from step 2. Separate for Indexing and Slicing
4. Colorize each separated object per Vertex Color.

>   File "/Users/jimmygunawan/Library/Application Support/Blender/2.78/scripts/addons/sverchok-master/core/update_system.py", line 322, in do_update_general
>     node.process()
>   File "/Users/jimmygunawan/Library/Application Support/Blender/2.78/scripts/addons/sverchok-master/nodes/object_nodes/vertex_colors_mk2.py", line 125, in process
>     colors[start_slice:stop_slice] = color
> Node Vertex color new had exception failed to coerce slice entry of type numpy.ndarray to integer
> 
> [image_decompose_study_003_2017_01_24_01_18.zip]

(https://github.com/nortikin/sverchok/files/725413/image_decompose_study_003_2017_01_24_01_18.zip)

https://gist.github.com/92f2a6f6a42e929fee2d25b3e4e6762a

**Comment by ly29** [comment]
Will have a look.

**Comment by enzyme69** [comment]
@ly29 
https://gist.github.com/994af729793da4d08bda10c31699194c

**Comment by enzyme69** [comment]
I forgot the List Item and List Join after Separate MK2, but then again the color list from RGB seems  to be a bit unusual?

**Comment by enzyme69** [comment]
Actually... it works, I just forgot few things like loading the image.

**Comment by enzyme69** [comment]
![screen shot 2017-01-24 at 12 52 29](https://cloud.githubusercontent.com/assets/3952687/22230830/fd4babc6-e233-11e6-9e9d-cc87e68619c7.png)

Interesting few steps processes. But it actually works. False alarm.

**Comment by enzyme69** [comment]
The 2 steps processed combined into one in this case is interesting "dependency issues" in Sverchok.

I tried loading the JSON and hoping it will just work but the process halted a few times because:
1) Needs Image source - easy fix
2) Needs Material - easy fix
3) The Colorize will need Object Voxel Grid to be created (currently not being generated), but because Colorize halted the process, the Object Voxel Grid arrange does not work. And all operations stopped. 

Separating the process makes it a smoother process:
- Generate Grid Voxel, bake out BMesh MK2
- Load the Grid Voxel, Separate, out again, and colorize.

![screen shot 2017-01-24 at 12 59 14](https://cloud.githubusercontent.com/assets/3952687/22231022/08b8292a-e235-11e6-9d0c-9b0348e3baca.png)

**Comment by kalwalt** [comment]
@enzyme69 with the polyvox lib this should be possible, and maybe easyer, though with a result a bit different i think. Maybe if i time i will do an example.

**Comment by enzyme69** [comment]
@kalwalt I am watching with expectation :) 

With voxelation, I think Blender might be chocked if we spits out every objects as box voxels? Unless it is a single mest.

Remesh is ok, but losing all the texture, unless we retransfer it to point color.

**Comment by kalwalt** [comment]
> With voxelation, I think Blender might be chocked if we spits out every objects as box voxels

Honestly i don't know this, voxelization is a consuming task but you can do large infinite terrain with it.

>Unless it is a single mest (do you mean mesh?)

yes, as i know voxelization build a single mesh, but with Polyvox lib you can assign also a material and a color to a single voxel, and so should doable something like you are expecting to get. 
See this(from the Polivox examples):
![schermata del 2017-01-27 23-41-17](https://cloud.githubusercontent.com/assets/1275858/22390262/3f2eb7e6-e4ea-11e6-8ea8-e9e7ebe77c29.png)

this is a simple sphere with different layers and other boxes intersecting the sphere, every voxel as a own material and color. I have not tested this feature with python bindings, but as i have a result i will show to you. Unfortunately ther is some bug in the python bindings (i can't import the LargeVolume class for example..) because at the moment is not updated to the latest source code. But i hope that this can be solved in a near future.
