### ISSUE TITLE
Script node sockets limits questions

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1262]
Can the script node have its input/output sockets be set to have limits ? 
Could such limits be set dynamically based on values of some other inputs ?

**Comment by ly29** [comment]
It can be set dynamically but requires using extra props like float/int node does or creating a dynamic class like monad group does. Neither option is that that appealing...
For script node we have thought the limitations is reasonable. 

The sane option is implemented in redux with the extra socket types but due to legacy it isn't so simple here...

**Comment by zeffii** [comment]
The min/max/soft_min/max etc (all useful parameters) can't be changed after the property is declared, the extra props that _can_ be used to limit the final value of a property add a fair amount of complexity to the simple concept of limiting a property. I never bothered implementing it in SN1 / SNLite. As it stands currently you still have to sanitise input into your algorithms anyway _and_ can't rely on socket limits because they don't force limits on the incoming data when a socket is linked and getting data from a different node.

**Comment by ly29** [comment]
When you do it for node group the class is unregistered and then registered again and all instances are updated to the new definitions. The property parameters are per class and only the value is per instance.

**Comment by ly29** [comment]
Anyway this unlikely to get addressed in the short term.
