### ISSUE TITLE
Scene and Object ID Raycast Experiment

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1272]
![screen shot 2017-02-27 at 13 56 18](https://cloud.githubusercontent.com/assets/3952687/23347208/96c531e8-fcf4-11e6-902d-bb8df254b604.png)

https://gist.github.com/4e035dc2a7e337d5c2b1a6b2a96a47c5

Experimenting with @Kosvor2  and @kalwalt setup to do this raycasting. This is super fun and for the first time my brain can compute what this raycasting and rendering is all about.

Now, with Scene Raycast, I noticed that it actually computes the mesh plane that I generated. It computes all objects in 3D scene. Hence, I am getting this weird vignette kind of effect (it's so realistic!)

But what if I wanted to specifically only computer Suzanne?

Using Object ID Raycast, looks like it does not compute the procedural animation that I am doing using Animation Nodes.

Object ID Raycast perhaps need a way to compute apply the transform?
[bbox_depth_mix_max_016_2017_02_27_02_59.zip](https://github.com/nortikin/sverchok/files/802567/bbox_depth_mix_max_016_2017_02_27_02_59.zip)

**Comment by Kosvor2** [comment]
Vignette most likely because lenght mode of vector math node finds distance from one set of vectors to the origin point of object. Try to use a distance mode to find distance between origin points and hitpoints.

Object ID Raycast have some chekboxes on side panel which controls how it uses input vectors and converts output vectors, try to change this. Over than that, there not much i can do.

**Comment by enzyme69** [comment]
Ok then thanks @Kosvor2 !
