### ISSUE TITLE
How must vert input react to string output?

### ISSUE THREAD

**Issue by Kosvor2** [nortikin/sverchok#1315]
Does it must reshape [[f,f,f,f,f,f]] data to [[(f,f,f),(f,f,f)]] vector data?
Or it must just take data and trying to work with it?
Or let's just stay with only matrix socket converting verts?

![exec11](https://cloud.githubusercontent.com/assets/22656834/23677292/5b9577c8-03a1-11e7-8c1b-29d84c49f6b0.png)

**Comment by zeffii** [comment]
Vdmk2 has this line

        vertex_links = inputs['vertices'].is_linked and check_origin('vertices', ('v', 'm'))

**Comment by Kosvor2** [comment]
Does check_origin() really worth it? @ly29 , @zeffii

**Comment by ly29** [comment]
No. 

If incoming data is badly formed failure is ok. 

The interface face that check origin has to use is potentially very slow. Adding more semi automatic guessing is a bad idea. 
Just because the inconsistencies. 

I am okay with adding something like a some automatic guessing to socket converter but I think that the exec node should have the right output type anyway... that goes for a bunch of nodes that are basically to thin wrappers around exec. 

Well formed type data is a part of sane computing experience. ( I doing JavaScript work at the moment...)


So to conclude. 
No automatic reformatting. 
No check incoming sockets. 
But fail in sensible ways. Raise a exeception

**Comment by ly29** [comment]
Worst kind of failure is a silent return

**Comment by zeffii** [comment]
> I think that the exec node should have the right output type anyway.
that should happen anyway.

> No check incoming sockets.
those are from a time where Blender would close to desktop is sverchok was trying to draw incomplete data in a bgl call, if those can go.. they should.
