### ISSUE TITLE
Should SV adopt Quaternions ?

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1452]
I noticed there is no quaternion handling in SV other than the Rotation node. Was this left out on purpose, was it an oversight or was not really needed so far ?  (There seem to be about 18 different quaternion nodes in AN)

If quaternions are to be added to SV I would think that new QuaternionsSockets may be needed along with some conversion nodes to say the least.

**Comment by zeffii** [comment]
we seem to have preferred 4x4 Matrix.

**Comment by nortikin** [comment]
maybe matrix socket can handle both with autoconversion?

**Comment by zeffii** [comment]
yeah, that would require QuatSocket.

**Comment by zeffii** [comment]
new sockets ( Color, Quaternion ) would share most of the internals with the StringsSocket. The only outward difference would be perhaps the `draw label` of the socket and `bl_idname` and node `socket color`.

It' s not a massive undertaking, but many small changes are needed. Surveying the needed changes is probably more work than the actual code modifications. This generates automatic pushback/reluctance. 

Unless this feature is really needed- i'd like to resist a little bit longer (because matrices are pretty awesome already).

**Comment by DolphinDream** [comment]
How do matrices handle gimble lock? Isn't this one issues that quaternions are known to solve ?

**Comment by zeffii** [comment]
Do you agree with this statement:

> The end product of a quaternion can be converted to a 4d matrix.

**Comment by zeffii** [comment]
4*4 i mean :)

**Comment by DolphinDream** [comment]
Can a 4X4 Matrix math handle gimble lock?

**Comment by zeffii** [comment]
In the 4 years i've been involved with Sverchok no-one has asked this, or made it clear that they need it. You are welcome to work on nodes that solve such problems for you.

I think (admittedly without proof) that a 4*4 matrix can handle any rotational requirement. Maybe not continuous.. but it seems to me that with resetting it should be at least able to handle the final orientation.

**Comment by zeffii** [comment]
https://en.wikipedia.org/wiki/Gimbal_lock#Alternate_orientation_representation

**Comment by nortikin** [comment]
question here is how you rotate matrix itself. maybe we need some new approach for rotation. How to rotate matrix without euler?
