### ISSUE TITLE
Sverchok as Modifier

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1563]
Maybe a very silly question, but can Sverchok already able to pass in the data from Object A back directly into Object A? Instead of making Object B (after baking or Bmesh Viewer).

{One could always manually change the Mesh Data, but maybe Object ID node can do this?}

In such a way that Object A does not cause weird cyclic data dependency. Instead what's happening in the background is like this:

Object A -> Store original data -> pass in new modified data -> have some kind of intermediate object which it can always revert to -> Object A

Because with Blender Modifier, typically use expect it to be able to Chain Stack Modifier, and then when they change mind, they just delete Modifier and get the original object.

I am pretty sure I saw Zeffii or Kosvor made some kind of node that simply pass in the Mesh Data into the original object?

**Comment by zeffii** [comment]
I'm not sure I understand, so can't answer. Try editing the question..maybe add some small images.

**Comment by zeffii** [comment]
Unfortunately python can't currently (or maybe ever) define Modifiers, so whatever you're looking for .. it won't be integrated into the Modifier stack. (even tho that would be great ....)

this means at present any attempt to implement something like a Sverchok based modifier stack would mean someone 

  - creating a panel much like the Modifier tab and implementing 
  - all the UI to add a NodeTree (monad..) / move node tree updown.
  - have the order in which the various node trees are stacked, determine which node pipes into which other node tree.
    
        Object  -> Monad 1 -> Monad 2 -> Monad 3 -> End Object / or GL Drawing 

and once we did that... we'd realize that hey... monads can already do that quite conveniently. The question is really, should we make something because we can (but don't necessarily need)... or focus on stuff that we can't currently do. I'm in the set of people who try to focus on the latter.

**Comment by nortikin** [comment]
waiting for `all in nodes`
