### ISSUE TITLE
BVHTree Inside Outside

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1617]
I noticed @Kosvor2 update to KDTree, does Sverchok has similar thing nodes but for BVHTree, such as if we have bunch of points but want to get inside or outside volume?

**Comment by zeffii** [comment]
just as a quiz @enzyme69  

>  does Sverchok has similar thing nodes but for BVHTree, such as if we have bunch of points but want to get inside or outside volume?

use the search -- https://github.com/nortikin/sverchok/search?utf8=%E2%9C%93&q=BVHTree&type=

currently that will return limited results, but that's good in a sense because there's less files/code to scan through to get an idea of what is and what is not currently implemented. This is a habit  i wish to cultivate in you.

**Comment by enzyme69** [comment]
I see... I think I should get deeper from now on. Thanks for pointing me
out. This changes the game.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/issues/660
