### ISSUE TITLE
Face / Edge indices are changing after a Modifier node?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1696]
I am making this procedural spoon and at some needing to extrude polygon face by index, occassionally I found a very strange glitch, where the index is changing for no reason. Like I don't touch anything or move the vertices, I only make a new node to mesh join everything, but the result is changing again and again.

gist:
https://gist.github.com/7e18fa870bd95f0c08d0e62e408a1dbb

blend zip:
[sv_spoon_002_2017_06_02_01_45.zip]
(https://github.com/nortikin/sverchok/files/1046462/sv_spoon_002_2017_06_02_01_45.zip)
![screen shot 2017-06-02 at 11 45 47](https://cloud.githubusercontent.com/assets/3952687/26707574/302f2756-4789-11e7-8741-fd7a8b3bd43e.png)

**Comment by zeffii** [comment]
So? Stick an index viewer on the spoon, figure out which node is shuffling face indices internally. Nodes that internally convert to bmesh first have an unstable face and edge indexing (  bm sacrifices continuity for speed ). Mask elements by Index will be stable.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/26715067/77c3a2dc-4774-11e7-9d20-26e995705557.png)

you understand now why the face indices you are passing are not matching up with your expectations? I know it doesn't solve the problem, but the first step towards that are figuring out where the problem is.

**Comment by enzyme69** [comment]
Gotcha 🥇 Ok I will try troubleshooting this in a bit.
