### ISSUE TITLE
"ctrl+enter" not working for refreshing profile parametric node, unless...

### ISSUE THREAD

**Issue by geniusupgrader** [nortikin/sverchok#1750]
Connected with a Text file and enabled with "extended parsing" in the properties panel of a Profile Parametric Node and a Viewer Draw Node for displaying: the shortcut "ctrl+enter" for refreshing the textfile and the 3D View is not working, unless an (empty and even unconnected) scripted Node is added (in the Node editor). Is someone able to reproduce this?

**Comment by zeffii** [comment]
i'll have a look at this tomorrow. (i have not been paying close attention to all modifications to that node since i wrote it)

The ctrl+enter combo triggers an operator, you should look at the code in that operator if you want an idea of whats going on.  From memory the operator should do the following.

```
- am i in texteditor && am i in a text loaded by the a profileparametric / script node?
- if yes, trigger an update from that node, downstream.
```
it may be that the operator doesn't include recent bl_idname for the updated profileparametric node.

**Comment by zeffii** [comment]
see: https://github.com/nortikin/sverchok/blob/master/utils/text_editor_plugins.py#L306-L309

and yes, that should include `SvProfileNodeMK2`

**Comment by geniusupgrader** [comment]
I've created a Pull Request: https://github.com/nortikin/sverchok/pull/1752
