### ISSUE TITLE
Joining Mesh that contains just Edges or just Poly with points?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1772]
Is it possible to merge objects that contain Points + Either Edges or Polygon data? Looks like it gives error exception.

![prtscr capture_81](https://user-images.githubusercontent.com/3952687/30146317-a97d834e-93da-11e7-83a6-43a929b7cd8d.png)

**Comment by enzyme69** [comment]
Hmm... it's just either one or another... unless I am missing a trick?
![prtscr capture_83](https://user-images.githubusercontent.com/3952687/30146360-e92810e0-93da-11e7-9500-51988024a09b.png)

**Comment by zeffii** [comment]
nope. not possible - that's why I allowed edges and polygons sockets separately for BMViewer. I'm sure if VDMK is rewritten for B2.8 it will be more flexible

**Comment by zeffii** [comment]
i think that the "edge_pol" and "PolyEdge"  socket might be a misnomer, altho they can carry mixed data (because they are just lists at the end of the day) it is easy to make mistakes/slowdowns using them and coding nodes that have to parse each element to check if it's an edge or a face.

**Comment by zeffii** [comment]
i think that the "edge_pol" and "PolyEdge"  socket might be a misnomer, altho they can carry mixed data (because they are just lists at the end of the day) . They currently should just be used for one or the other, that's what all sverchok nodes expect.

Datastreams that carry mixed types of data mean you have to parse each element to check if it's an edge or a face, that's a slowdown.

**Comment by enzyme69** [comment]
Gotcha, will keep that in mind. Reading the code is a good idea <-- I always forgot the source code is readable. Cheers, Zeff.
