### ISSUE TITLE
Square and diamond socket shapes for pynodes (commited to Blender master).

### ISSUE THREAD

**Issue by Kosvor2** [nortikin/sverchok#1781]
https://developer.blender.org/D2814

**Comment by enzyme69** [comment]
Do I need to update Blender and Sverchok for this?

**Comment by zeffii** [comment]
Read it carefully jimmy.

**Comment by enzyme69** [comment]
Got it now cheers.
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by zeffii** [comment]
We don't have to use something just because new API is implemented.

i'm a little on the fence about if this is useful to Sverchok. We have a different way of handling socket data than AN does. Maybe a different drawpath _is_ a nice way to inform users that the socket doesn't expect multiple lists... i dunno

I'd rather have socket-socket noodle drawing with styles.. like the strokes for noodle in max/msp
![image](https://user-images.githubusercontent.com/619340/30318077-5ab3182a-97ac-11e7-9e3f-bd34c0e0325d.png)

where the `dashed line` represents audio rate single ( sample rate ) vs `regular line`  control rate (20hz..or whenever update is triggered)

**Comment by zeffii** [comment]
useful to know .. but not sure we need to take any action here. closing for now.

**Comment by DolphinDream** [comment]
Would different socket types help with distinguishing between 4x4 Matrix socket and  5x5 Matrix socket (used for 4D manipulation) ?
