### ISSUE TITLE
SV Rayvast Inverting

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1808]
![prtscr capture_32](https://user-images.githubusercontent.com/3952687/31363376-b4d8b702-ada9-11e7-8caf-fd6272d48c3b.png)
![prtscr capture_31](https://user-images.githubusercontent.com/3952687/31363378-b5104eb0-ada9-11e7-9fb7-d3a90b017fc2.png)

Thanks @zeffii for new SV Raycast node. I am wondering how to invert the resulting points? And also wondering how to use the Index Out?

**Comment by enzyme69** [comment]
Zip Blend:
[ray_thing_008_2017_10_09_23_57.zip](https://github.com/nortikin/sverchok/files/1370115/ray_thing_008_2017_10_09_23_57.zip)

**Comment by zeffii** [comment]
i reused an older bvh_raycast node by kosvor, and kept the output sockets the same - I can easily add a `success` socket.

**Comment by enzyme69** [comment]
Got it! Cheers Zeff!

**Comment by enzyme69** [comment]
Oh btw, the Object ID Raycast MKII does not see Text Object as something with mesh data.

**Comment by zeffii** [comment]
but in the meantime : we do have nodes that convert a list of indices to a datamask

![image](https://user-images.githubusercontent.com/619340/31373778-a00348e6-ad9b-11e7-8a75-3295cfd16620.png)

> the Object ID Raycast MKII does not see Text Object as something with mesh data

yes, because Blender's Text Object is really a Curve/Surface and doesn't have a query-able Mesh to raycast into until it is turned into a Mesh. If you are saying "maybe object Id raycast node should know about objects of type Text and do special stuff when found" -- i think you'd be correct.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/blob/1dbba4a85585de546d5af1e8860bc434951fbde7/nodes/object_nodes/object_raycast2.py#L56-L61

Objects of type _Text_ don't have raycast method, this means things like `OB.raycast` in the above snippet won't work as expected. There would need to be a separate bit of code to get the Text Object data into a form that can handle being raycast.

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/31384548-be49dc1a-adbf-11e7-8a45-ce0f2ecfb330.png)
