### ISSUE TITLE
.5.9.6(15760ce)  Vertex color new   bug  

### ISSUE THREAD

**Issue by fxzt** [nortikin/sverchok#1888]
.5.9.6(15760ce)  Vertex color new   bug

**Comment by portnov** [comment]
Could you please elaborate?

**Comment by zeffii** [comment]
I think @Kosvor2 's [proposed code modification](https://github.com/nortikin/sverchok/issues/1842) should be merged regarding the vertex color node, internally Blender's Vcol map takes Alpha now, previously it was only RGB.

This bug has nothing to do with the referenced commit. Most likely fxzt has not updated in a while or used Vertex Color node.. since @Kosvor2 proposed the code change. (2 ..3 weeks ago)

**Comment by zeffii** [comment]
@fxzt  thanks for bringing this to our attention . it'll be fixed shortly.

**Comment by zeffii** [comment]
closing this issue because it is a;ready known, and we can further discuss it here:  https://github.com/nortikin/sverchok/issues/1842
