### ISSUE TITLE
List Pair Key-Value input as Dictionary then output based on Key

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1900]
Just like the Subject, I am wondering if Sverchok has this kind of method of LIST -> MATCH -> FILTER -> NEW LIST.

For example I have list of 100 data, it is a pair key value list like dictionary:
- Apple: 10
- Banana: 25
- Orange: 33
- Durian: 12
- and so on

Now, I have objects in the scene with just 10 data or varying numbers of data that matches the 100 data. Such as:
- Object A: Apple, Banana --> 10 + 25 = 35
- Object B Orange, Banana, Durian --> 33 + 25 + 12 = 70
- and so on.

Supposedly with Python, I think we can convert the LIST PAIR into Dictionary that can be called to then provide the value.

Wondering how to do this automatically as node? I supposed maybe Exec Node Mod can do this somewhat. But one object at a time...

In the past, I think the closest similar example is when we have LIST ITEMS and then we actually pick the ITEM based on the provided list of index, per object.

**Comment by Durman** [comment]
Something like that?

![2017-12-04_13-07-09](https://user-images.githubusercontent.com/28003269/33544493-6560ecb4-d8f4-11e7-9422-fbea319eee29.png)
https://gist.github.com/178a31616d7399f8ec5f292d03f27271

**Comment by zeffii** [comment]
> Supposedly with Python, I think we can convert the LIST PAIR into Dictionary that can be called to then provide the value.

so... what have you tried?!

**Comment by zeffii** [comment]
What i find frustrating about this question is you don't provide exactly the input.. 

1.

like.. is it a file in `bpy.data.texts` that reads
```pyhon
{
"Apple": 10,
"Banana": 25,
"Orange": 33,
"Durian": 12
}
```
because that is "as dictionary" , whereas
```
Apple: 10
Banana: 25
Orange: 33
Durian: 12
```
is "like dictionary". it could be interpreted into a dictionary with basic python string/dict manipulation.

But jimmy, what kind of data are you exactly starting out with? each variant requires different kinds of code to read and process. So i'll assume you can get that data into the form of a dictionary..

2. you want to get the sum of the values returned after multiple dictionary lookups:

```python
# setup code... this would happen outside of Exec Node
my_dict = {"Apple": 10, "Banana": 25, "Orange": 33, "Durian": 12}
my_lookups = [
    ["Apple", "Apple", "Banana"],           // object A
    ["Apple", "Apple", "Orange", "Durian"]               // object B
}

# my_dict is passed to V1 socket
# my_lookups is passed to V2 socket

my_lookups = V2
my_dict = V1[0][0]
for lookup in my_lookups:
    stored_value = 0
    for item_name in lookup:
        value = my_dict.get(item_name, 0)
        stored_value += value
    append([stored_value])
```
![image](https://user-images.githubusercontent.com/619340/33557937-ee7c3bb6-d908-11e7-9abe-011a7c08d1c6.png)

3, No we don't have nodes specfically for working with converting text to dicts and the rest. I'd suggest getting more familiar with Python and use Exec Node, and you'll have a lot more fun with Sverchok.

**Comment by enzyme69** [comment]
After overnight thinking, this morning, this pops in my mind "List Mask", isn't it like List Masking, but then with List Mask the data needs to always come in order.

![screen shot 2017-12-05 at 12 18 34](https://user-images.githubusercontent.com/3952687/33585058-72fe849a-d9b6-11e7-8302-cfadd1418c39.png)
[list_mask_001_2017_12_05_01_18.zip](https://github.com/nortikin/sverchok/files/1529349/list_mask_001_2017_12_05_01_18.zip)

Thanks a lot for some suggestions, I am studying it.

**Comment by enzyme69** [comment]
But of course my setup will fail when list grow or repeat. So @Durman  and @zeffii answers are much better. Thanks again.

**Comment by enzyme69** [comment]
Keyword is: dictionary, lookup.
