### ISSUE TITLE
Replace zip with gzip?

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#1915]
Currently sverchok allows to export blend files in zip archive. But, Blender can open .gz archives, but not .zip. Maybe replace archiving type by default?

**Comment by zeffii** [comment]
maybe..  but the operator to load the zip from an online source already automatically unzips and loads. so there will need to be handling of the existing blends that are zipped by sverchok.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/blob/master/utils/sv_load_zipped_blend.py

**Comment by enzyme69** [comment]
This feature has not been working for a while actually. Github does not
like it.
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by zeffii** [comment]
[permanent_2017_12_09_08_55.zip](https://github.com/nortikin/sverchok/files/1544504/permanent_2017_12_09_08_55.zip)
works for me.. both export and import.

**Comment by enzyme69** [comment]
Oh! I forgot, the gist is okey, but the zipped loading has been failing for a while now.

![screen shot 2017-12-09 at 22 57 38](https://user-images.githubusercontent.com/3952687/33795380-62eda906-dd34-11e7-8b99-fad228410627.png)
![screen shot 2017-12-09 at 22 56 36](https://user-images.githubusercontent.com/3952687/33795382-635312dc-dd34-11e7-9d49-caeef8ec0c64.png)

![screen shot 2017-12-09 at 22 57 33](https://user-images.githubusercontent.com/3952687/33795381-631fcd14-dd34-11e7-95e3-63d190506960.png)

**Comment by zeffii** [comment]
well.. jimmy..  what happens if you try this one? The following zip is a valid file
https://github.com/nortikin/sverchok/files/1544504/permanent_2017_12_09_08_55.zip

the url you're showing is not even a valid .zip url. 
```
https://api.github.com/gists/elfnor_tree_mirror_001_2017_12_04_23_54.zip
```
just throws the following message in a browser:
```json
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/gists/#get-a-single-gist"
}
```
i suspect you are trying to copy this portion " elfnor_tree_mirror_001_2017_12_04_23_54.zip " into the GIST import area. or something.

that tree zip is not a `gist.` zips are not `gists.` 
I think you mean this zip url 
https://github.com/enzyme69/blendersushi/files/1529184/elfnor_tree_mirror_001_2017_12_04_23_54.zip

the way to load that into sverchok is to 

 - copy the url directly to your clipboard
 - in nodeview press space
 - type ' ur ' (it will display: 
   
    ![image](https://user-images.githubusercontent.com/619340/33795772-d649c530-dce7-11e7-8b25-5cfc28d84a1d.png)
 - hit Enter, and bam! it loads after a few seconds.

**Comment by zeffii** [comment]
you're using it wrong @enzyme69. can't really do much about that - there's only so much we can do behind the scenes to guess the intentions. In this case the error message was pretty helpful. "doesn't appear to be a valid url.... "

Back to the topic, since github does also support `.gz` uploads to the issue tracker we could certainly move away from .zip

**Comment by zeffii** [comment]
the current operators/functions 
  - zip the blend to a directory, using a naming convention.
  - allow a valid .zip url (a zip generated by sverchok - mostly) to be downloaded, unzipped and hotloaded simply by [following these instructions](https://github.com/nortikin/sverchok/issues/1434)

a lot of files are already shared as zips this way, adding .gz is fine. The operator can easily detect if the clipboard/url ends in .gz or .zip.

**Comment by zeffii** [comment]
```python
import os
import gzip
import shutil
from time import gmtime, strftime

import bpy


def propose_archive_filepath(blendpath, extension='zip'):
    """ disect existing filepath, add timestamp """
    blendname = os.path.basename(blendpath)
    blenddir = os.path.dirname(blendpath)
    blendbasename = blendname.split('.')[0]
    raw_time_stamp = strftime("%Y_%m_%d_%H_%M", gmtime())
    archivename = blendbasename + '_' + raw_time_stamp + '.' + extension

    return os.path.join(blenddir, archivename)


def compress_blend_as_gzip(self):

    blendpath = bpy.data.filepath

    if not blendpath:
        msg = 'you must save the .blend first before we can compress it'
        # self.report({'INFO'}, msg)
        print(msg)
        return {'CANCELLED'}

    with open(blendpath, 'rb') as f_in:
        gzip_filepath = propose_archive_filepath(blendpath, 'gz')
        with gzip.open(gzip_filepath, 'wb') as f_out:
            shutil.copyfileobj(f_in, f_out)
        print('saved to', gzip_filepath)

    return {'FINISHED'}


compress_blend_as_gzip('dummy')
```

**Comment by zeffii** [comment]
see the pull request: https://github.com/nortikin/sverchok/pull/1922

**Comment by zeffii** [comment]
well, i pushed the option for users to pick zip or .gz , some UI finesse could be forthcoming ( feel free to tackle that )
