### ISSUE TITLE
Invisible mode in viewer BMesh.

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#1930]
It is uncomfortable behaviour with an objects. (
https://gist.github.com/acb82109f11375e3da42c1968b4c38a2
![invisible mode](https://user-images.githubusercontent.com/28003269/33992718-1e9266e0-e0ed-11e7-957b-c5927428b033.gif)

**Comment by zeffii** [comment]
yeah, i see.  that's not super helpful.  we will fix soon (not looked yet)

**Comment by zeffii** [comment]
if i recall correctly, the only time objects are hidden is when the user pressed that Boolean switch on the ui. on off on off. etc. There is no point in the `process` function that checks the state of that Boolean to make sure the other objects that are generated afterwards will also adhere to that property.

**Comment by zeffii** [comment]
In general we will not hide/unhide continuously throughout the lifespan of the nodetree, these things are usually only modfied infrequently. This is the reasoning behind not including a step to do this automatically in the process function.

we could add a final cleanup step towards the end, in between these two calls.
```python
        if self.autosmooth:
            self.set_autosmooth(objs)

        if self.outputs[0].is_linked:
            self.outputs[0].sv_set(objs)
```
i'd maybe keep the default behaviour initially. I'll always assume that adding extra checks for each object will introduce some slowdown. So by default it would behave exactly the same as now, but if we add a boolean (f.ex `auto_set_hide_in_process` ) then when we consciously need `process` to really perform those checks then we can switch it on.

If it turns out that there's no significant slowdown, we remove the option ..and just perform the checks by default.

**Comment by zeffii** [comment]
you'll see this is the code that reacts to the booleans being toggled. `n` reference to a reference to the specific viewer node. You'll notice this code is present only the Operator (SvBmeshViewOp2) and absent from the node class..
```
        if type_op in {'hide', 'hide_render', 'hide_select'}:
            op_value = getattr(n, type_op)
            for obj in objs:
                setattr(obj, type_op, op_value)
            setattr(n, type_op, not op_value)

        elif type_op == 'mesh_select':
            for obj in objs:
                obj.select = n.select_state_mesh
            n.select_state_mesh = not n.select_state_mesh
```

**Comment by Durman** [comment]
@zeffii 
> So by default it would behave exactly the same as now, but if we add a boolean (f.ex auto_set_hide_in_process ) then when we consciously need process to really perform those checks then we can switch it on.

I would like to have this check. I try to split my node tree by sheets and use scene as place for exchange between node tree's sheets.

![2017-12-15_10-45-16](https://user-images.githubusercontent.com/28003269/34030148-2ba78b4c-e185-11e7-925f-b4e0c7372583.png)

**Comment by zeffii** [comment]
this will be addressed in the SvObjHelper mixin, where a reference implementation will be included as a standard method.
