### ISSUE TITLE
Viewer BMesh Fails if not Matrix is suplied

### ISSUE THREAD

**Issue by vicdoval** [nortikin/sverchok#2211]
## Problem statement

Viewer Bmesh returns error when plugging any geometry until you plug the matrix socket. 
Although it is easy to avoid maybe it would be interesting to provide a default matrix
## Steps to reproduce

1.  Connect a Box Node to a Viewer BMesh Node

## Expected result

A cube in the centre of coordinantes should be created
## Actual result

An error.

( until I plugged a "matrix in")

## Sverchok version
Today's  0.5.9.6 updated from blender

**Comment by zeffii** [comment]
today @Kosvor2 pushed a massive change to sverchok to force matrix socket to use mathutils.Matrix(), this involves changing many nodes. It's something we maybe should have done from the start. The problem is however that because it's a big change, it would have been wiser to not merge that pullrequest until a number of people agreed that it was good to go. 

I have no time to test it, and judging by the luke-warm response by other devs here prior to pushing the PR to Master, not many other have time to test either. 

we can revert... i would have no problem.

**Comment by Kosvor2** [comment]
I will look.

**Comment by vicdoval** [comment]
Great!
Thanks!

**Comment by nortikin** [comment]
goood

**Comment by nortikin** [comment]
@Kosvor2 
have you email?

**Comment by Kosvor2** [comment]
@nortikin  Есть, но не заглядываю туда уже давно.

**Comment by nortikin** [comment]
тогда как с тобой связаться? Я на БА напишу
