### ISSUE TITLE
Refactorisation/Tidy up

### ISSUE THREAD

**Issue by 0xD34DC0DE** [nortikin/sverchok#2225]
Features/Recommendation

I downloaded Sverchok after seeing some limitation with animation nodes when creating meshes but when I saw the state of Sverchok nodes arrangement... I got a little bit surprised at how disorganized it looked...

I think a refactor is needed at this point or just a tidy up of the nodes menus as well as standardization of the mk1,2,3 stuff its too much confusing for newcomer,

Taking animation Node for example everything is clear and sub categorized easily so just using common sense is enough to know how to work with it

**Comment by zeffii** [comment]
Why not go back to Animation nodes and modify that so that if fits your requirements, rather than proposing to impose a menu reorganization unto us? serious question (not a combat)

**Comment by Durman** [comment]
@0xD34DC0DE 
Can you say what we have to fix to improve understanding of structure of SV nodes? 

From my point of view we have more or less normal structure now.

May be some nodes are contained in not quite right categories such as `SN` and `SNL` node, `Exec Node Mod`. Perhaps it's better to move at list `Lamp` and `Empty out` nodes to Viz category. Tree `interpolation` nodes looks like more than we need. 

In general as i see it's possible combine functionality some nodes as like `a number` node. But it's separate long work. 

I would recommend to look through this [guides](https://github.com/nortikin/sverchok/tree/master/docs) (unit_00, unit_01) it can help understanding Sverchok.

**Comment by unwave** [comment]
The point is that SV is difficult to understand for newcomers because of lack of encapsulation. It has everything in sight(just as blender does). It takes quite some time to get into it. But I would say the real problem is the lack of vectorisation and its standards. It is really annoying to realize that it is not going to work the way you want and you have to build a very big tree to perform a simple idea.

**Comment by zeffii** [comment]
@unwave 

>  It is really annoying to realize that it is not going to work the way you want and you have to build a very big tree to perform a simple idea.

if you can show cut down versions of these scenarios as .blend files to demo such problems, those are interesting for us to look at. 

I don't expect massive changes to Sverchok for `Blender < 2.80`, after 2.8 settles down and gets a good drawing API and more refined event handlers i think more effort will go into that than anything else.

**Comment by Durman** [comment]
According last comments that I heard about Sverchok, all agree that it is powerful addon but which hard to use. It looks like huge work was done vainly because only few people can use Sverchok. If it's true it's very sad. 

I think we can do something for improving this situation. We have monad node that can be very useful in this issue. We can create set of monads for solving different tasks. If Sverchok included such monads this would give loads of benefits:

- As I see it is easy to do.
- It would be great educational material for newcomers, because we can unfold monad any time and try to investigate how it works. 
- Users would get more possibilities for solving their goals. 
- We can get more developers because creation of monads is much more easier task than coding on Python with knowing of Blender API. 

All that we have to do is try to understand what users want to see.))

**Comment by enzyme69** [comment]
At some point, if Blender 2.8 has a compatible Sverchok, maybe I can redo
some of the tutorials. Rethinking nodes understanding.

Sverchok is not hard :)
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by nortikin** [comment]
@unwave 
some things hard to recreate in any of soft.
Non the less it is possible. SNL is often in use on current stage.
