### ISSUE TITLE
Final Sverchok for b.279 release should be soon.

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#2338]
over the last few weeks i've ported most of Sverchok to b.280. There are several deeper changes in Blender that prohibit the add-on from being backward compatible. I just wanted to get a working version of the add-on to use as a platform to further improve/develop Sverchok.

some viewer nodes are rewrites, or experimental / demonstrative
some scene object nodes will need dedicated attention
gists/examples/json that use (`old nodes` / or `removed nodes`) will fail to fully load
old .blends for 2.79 will not load in 2.80
automated testing with Travis will require some considerable attention soon.

Perhaps what we can do soon is:

1. 
  - branch current `sverchok for b2.79 master` as `sverchok_for_279`, 
     - and hardwire the zip update function there (first) to only download `sverchok_for_279` if we update that ever again.
  - then fully merge `b28_prelease_master` into `sverchok/master`.  

or!

2. 
  - commit `b28_prelease_master` to `Sverchok/sverchok_for_b280`

there are new features in Blender 2.80 that i've not tried to work with (like collections and new GP stuff) that might be useful for the instancing and grouping objects.

I don't want both versions of sverchok to drift apart to the extent many new nodes get introduced into the Svb2.79 version that then have to be ported to Svb2.80.

**Comment by zeffii** [comment]
## Pre Release notes. (subject to being updated)

### new viewer draw implementation ( s ).

my demonstrative node "VD_Experimental" is really only an attempt to make it possible to show the geometry as we develop the viewers further. During the past 4...5 years we've had requests for features that are a little easier to implement now. The mechanism for callback removal/placing and setting custom draw functions now allows for convenient experimentation and a whole new set of bgl/gpu viewer nodes. 

### Index Viewer

well, this was the most fun :) die-hard geometry constructors who get down and dirty with vectors and indices and compose their own meshes with the basic nodes will have fun seeing the indexviewer mask out the occluded faces (as an option)

### Stethoscope

probably the least effected node

### bmesh nodes

some nodes use one or more `bmesh.ops` internally, some of those .ops have vanished at present from bmesh module, so we await their reimplementation. Other bmesh reliant nodes will likely still be broken, but I think i got most of them.

### Object / Scene nodes

internally stuff has changed in Blender, it's hard to track those things down when my interest doesn't lie directly on blender objects. Someone will have to do that initially, and i'll help if needed.

### BMeshViewer / curve Viewer / SkinViewer / nodes

these work mostly, but do need a bit of tweaking for 2.80 (to make use of new collections features). These nodes have not been a priority because Blender internally is still a little too fluid to consider it anything other than a 'moving object'.

### Scalar Math 

this node has a few new features

**Comment by DolphinDream** [comment]
@zeffii are you suggesting no new nodes should be created for 2.79 ? I’m working on a suite of quaternion nodes and a bunch of others .. should these not be pulled into SV 2.79 version, but rather wait for SV 2.8 ? On that note, once SV 2.8 becomes ready do you expect users will switch to blender 2.8 if they want to use newer SV nodes or will we continue to provide both 2.79 and 2.8 versions?

since Blender 2.8 is not official yet i’m having some hesitation to start using it on a daily basis.. but maybe I should. :)

**Comment by portnov** [comment]
My proposals:
* while 2.8 is not yet officially released, and even some time after that (for example, 1 month after release): "pre-release" period. Our current master should be for 2.79. For this period, I'd suggest to declare a "partial feature freeze": features that are already being developed for 2.79 are ok, but let's not plan creating new nodes and other features for 2.79. This is just to do less work on 1) porting things to 2.8, 2) supporting two versions.
* After some time (for example, 1 month after 2.8 released: do "master switchover": branch current master to "sverchok_279", and merge all developments for 2.8 to master. Since that time, master will be for 2.8.
* For some time after "master switchover": I think we have to support both versions (sverchok_279 and master); but sverchok_279 should be in "total feature freeze": no new features, no new nodes, only bugfixes. All new features should go to master only. We just do not have so much human resources to support new features in both versions.

I'm proposing a lag of ~1 month after 2.8 release, because I think that even after 2.8 will be declared official there will be much more users that are still on 2.79 that ones who already use 2.8. Users will start migrating "en masse" only after some time after release.

**Comment by zeffii** [comment]
my position, new nodes are fine for 2.79 until 2.80 is out of beta. Then 2.79 is frozen except for bugfixes. 
with 2.80 officially released we should have a while where we experiment with 2.80 and try 
- port the new nodes to 2.8
- to remove as much cruft from Sverchok.
- examine nodes that deserve reimplementation
- fix all early typos
- experiment with new 2..80 features
- don't be too worried about breaking layouts in the first period, else we end up sticking effort into being compatible with everything but the codebase will snowball.

**Comment by enzyme69** [comment]
When can I start filing bug for SV 2.80? Vector Turbulance, Vector Noise, Vector Fractal all seems to fail to work.

**Comment by zeffii** [comment]
don't do bug reports for Sv for 2.80. also you should read the items without tickmarks in https://github.com/nortikin/sverchok/pull/2299 (these nodes use the noise module..)
