### ISSUE TITLE
Viewer Draw priority issue

### ISSUE THREAD

**Issue by alessandro-zomparelli** [nortikin/sverchok#2366]
Hi everybody,
I'm experiencing something unusual with the Viewer Draw:
- In "Solid" mode, it's hidden by other geometries
- In "LookDev" and "Rendered" it's hidden by other geometries, but if I disable the overlays, then it is drawn on the top.
I'm also experiencing some flickering in "Solid" with hidden overlays.

(sorry for the combo-issues :P )

thanks
Alessandro

**Comment by zeffii** [comment]
the VD experimental node is a little wonky, i'll be the first to admit. It's really just my effort to get some quick geometry drawing code working to test/implement the nodes. take the word 'experimental' as "hard fact" :)

overlays are something i have turned off, so i've never noticed that : /  and i'm reluctant to actively get into bgl/shader recodes because 2.80 is still so volatile/fluid.   (also a lot of stupid debug printing going on on the windows build..getting in the way of debugging other stuff.. --- i've effectively paused porting for a while)

**Comment by zeffii** [comment]
after recent SV bgl commit does this still play up ?

**Comment by zeffii** [comment]
it looks like some of these issues have resolved. If this (or other related ) issue still plagues you, feel free to reopen, and elaborate.
