### ISSUE TITLE
Viewer draw : Anti-aliasing Blender 2.80.74

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#2455]
Can i adjust this like with Blender 2.79 with 2.80.74 the line edges  looks verry jagged 
With bmesh live view they look smooth but not with the VD experimental node is there maybe a solution For ?

![image](https://user-images.githubusercontent.com/49908008/59557315-31567100-8fd7-11e9-92bb-705c98b43144.png)

**Comment by zeffii** [comment]
i'd love to have finer drawing control on the experimental viewer, but there are several reasons why this may not happen. I don't know if viewer draw is any less aliased than vd_experimental.

1. in order to draw edges and faces, where the edges aren't z-fighting the faces, would require the vectors of each edge to be offset by their normal - that's a pre-processing step which will slow down the initial cache-creation for a static frame - and will need to be re-processing whenever the input geometry is updated.  ( so.. python speed being somewhat prohibitive here ) -- the BMeshviewer doesn't have this limitation because all we do is feed it mesh data, and it hands off the 3dview representation to Blender (which is done in a much faster language. maybe even using your GPU )

2. the vd_experimental is really meant for getting an idea about the geometry you've generated, consider it a sketch where speed is more important than whether it renders nicely or not. Last time i looked it doesn't even render when you render using `openGL`.

i appreciate it's not very pretty,, maybe eventually it will get better - but someone with greater openGL skills will need to step up.

---
no there's nothing you can toggle on your end to make that look better @BennyGovaerts , really sorry.

**Comment by BennyGovaerts** [comment]
Yes , you are right 

But for some reason with blender 2.79 it looks just better, but maybe it works slower i have no idea 

![image](https://user-images.githubusercontent.com/49908008/59564330-bb3d2300-9045-11e9-978b-7ba50e2af4a6.png)

**Comment by zeffii** [comment]
i appreciate these side-by-side shots btw :)  (i don't have 2.79 installed anymore )

under the hood a lot changed between 2.79 and 2.80, especially regarding how add-ons draw to the 3dview - i think the drawing API is still subject to change so we'll keeping an eye on any improvements.
