### ISSUE TITLE
Set Material node

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#2460]
Task: for given object (provided from Object socket, for example from BMesh Viewer), assign different material indices for different faces.
This will require inputs:
* Object
* FacesIndexes
* MaterialIndexes

Parameters: list of materials to assign to object
Outputs: none.

I have a draft for such a node, will make a PR this week.

**Comment by portnov** [comment]
@Durman  FYI.

**Comment by Durman** [comment]
I also have thought about this node. I will share some thoughts about it. 
I see three ways of putting index of faces:
- First is put indexes of faces which should be dyed `[4, 115, 26, ...]`. In this case this node can assign only one material.
- Second to put mask like `[0,0,1,1,0, ...]` where zero means do not dye face with current index and on the contrary for one. In this case this node also can assign only one material. 
- Third is put mask like `[1,1,0,2, 4, ...]` where figures mean index of material which should be assigned to face with same position. In this case the node can assign several materials simultaneously. Also there is no need in any material socket. It can be more convenient to have different node for assigning materials to objects. Downside of last approach is lack of possibility to apply material only to half part of object. Also it can be too tricky to prepare such mask. 

One more important feature as I think the node should include is to lead an object back to previous conditions. Probably it is fairly about first and second described aproaches above.
For example we assign material to part of object. But after a while we decided to do the same to another part of object. In this case we should restore object in previous condition otherwise it will be dyed entirely in one material.

About material socket. I think we can keep them in two ways:
- First is just a flat list. It is actually how they are stored in Blender data base. 
- Second way is distribute them by objects like this. `[obj1[mat1,mat2, ...], obj2[mat1,mat2,...]]`. In this case it is easy to apply materials two objects. Mat1 means material for first slot and so on.

According to this we can have several nodes or modes for handling with assigning materials. 
It is looks like there is sense make different node for `assigning materials to objects`. `Assigning materials to face` can use materials which object already has or assign material to object too. 
Also assign materials node can have feature working with different types of mask. 

Creating mask is separate issue. Now I m thinking about `selection gruber` node.))

**Comment by portnov** [comment]
In my draft, I have
* object
* list of materials (specified as just a setting of the node for now). I will assign all these materials to the object
* list of face indexes
* list of material indexes

and then, for each pair of (face index, material index), I do face[face_index].material_index = material_index.

**Comment by Durman** [comment]
From my point of view there is no sense of having face indes list. It is always will be `range(len(faces))`. And it is impossible to assign more than one material per face. 
So it is enuff to have list of material indexes - `face[index(material_index)] = material[material_index]`. 

In your implementation will node be able to assign different sets of materials to different objects simultaneously? And should the node be capable of doing such thing?

**Comment by portnov** [comment]
> From my point of view there is no sense of having face indes list. It is always will be range(len(faces))
Not always, because BMesh Viewer by default assigns all faces with a single material.

> In your implementation will node be able to assign different sets of materials to different objects simultaneously?
Currently, no, because list of materials is specified in node settings, not passed from socket. But it is possible to implement if required.

**Comment by portnov** [comment]
We can make "FaceIndexes" input optional: if not connected - behave as range(len(faces)) was passed.

**Comment by portnov** [comment]
Closing the issue. We may continue discussion in #2462.
