### ISSUE TITLE
Group and Collection Blender 2.80

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2479]
## Problem statement

In the past, Grouping is simply linking objects into Group. With 2.80 we now have Collections. The way currently Sverchok handles Collection seems to not accounting the already existing Collections. 

## Steps to reproduce

1. Using BMesh Viewer
2. Output into Collections
3. Collection being generated but with *.0000 naming 
4. Cannot geometry output already existing Collection

## Expected result

Expecting to see dropdown of existing Collection list

## Actual result

Collection.0000 is where the geometry is placed

## Sverchok version

0.6.00 for Blender 2.80 beta

**Comment by enzyme69** [comment]
Screenshot of what happens:
<img width="643" alt="Screen Shot 2019-06-30 at 09 42 31" src="https://user-images.githubusercontent.com/3952687/60391581-db77e200-9b1b-11e9-8a56-78bf5090b38d.png">

**Comment by zeffii** [comment]
This is mentioned in the  [`pull request`](https://github.com/nortikin/sverchok/pull/2299)

![image](https://user-images.githubusercontent.com/619340/60397019-a635b900-9b48-11e9-802c-434973f1a883.png)

it's on the radar, for now... don't group stuff :)

**Comment by zeffii** [comment]
maybe this collections stuff has settled down now enough to implement a permanent strategy. Since "groups" are now gone.

The question is 
- should each `******ViewerNode` automatically generate it's own collection by default, and just grow/shrink that, rather than adding objects to the default collection ( if that's even a thing ) ----without option to "ungroup".
- or.. only create a dedicated collection if indicated explicitly

having objects in a dedicated collection by default has at least one favourable argument, one that i like a lot;  it's vastly simpler code.
