### ISSUE TITLE
To make Pipe Node actually Working...

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2503]
I am using Pipe Node in Blender 2.80 Sverchok. And I found to be quite strange. It has potential to be a node that works as actual pipe making, but it seems to have "twist" issue and also for actual Pipe to work, maybe when it is facing a corner, it should bend like "bevel".

I tried using Bevel at corner, but the resulting Pipe is wrong, maybe because the order as wrong. 

My feeling is that we can find a way around this twist and weird pipe with some other nodes hack. 

[sverchok_pipe_study_004.blend.zip](https://github.com/nortikin/sverchok/files/3513868/sverchok_pipe_study_004.blend.zip)
<img width="1051" alt="Screen Shot 2019-08-19 at 11 39 58 am" src="https://user-images.githubusercontent.com/3952687/63233914-1ffb4080-c276-11e9-9964-1f6b0191d724.png">

**Comment by enzyme69** [comment]
List sorting and connectivity ... 

<img width="958" alt="Screen Shot 2019-08-19 at 11 44 19 am" src="https://user-images.githubusercontent.com/3952687/63234029-b596d000-c276-11e9-99a4-bc59c03e2f3f.png">

**Comment by enzyme69** [comment]
Still I think Pipe has "Twisting Issue" between the parts...

**Comment by enzyme69** [comment]
Here I am using Circle and it's obvious the Pipe is twisting...

<img width="1095" alt="Screen Shot 2019-08-19 at 11 50 34 am" src="https://user-images.githubusercontent.com/3952687/63234188-93518200-c277-11e9-9c09-3ea765710d78.png">

**Comment by zeffii** [comment]
you'll need to start taking screenshots of the same setup in 2.79. so we can see side-by-side if the problem is related to the Blender implementation of bmesh.ops or something..

**Comment by zeffii** [comment]
in the mean-time.. i would use `SvSmoothLines` and then pass it to a curve outputter node ..

**Comment by zeffii** [comment]
Because Bevel users a `bmesh.ops` the order of the output is not going to be what you expect. Hence you are forced to reorder the topology using the Sort node. 

A lot of these BMesh ops (spplied by Blender as part of their bmesh API) come back to bite us in the ass. Not that they aren't good, but they are coded for speed-performance and not topological consistency. In an add-on like Sverchok where these nodes/ops are often intermediary processing steps that is unsatisfactory.

luckily some time ago I wanted a similar thing, it's what `SvSmoothLines`  can be used for. You can even set the Fillet/Bevel per vertex.

I really don't know about Pipe node..

but this seems to work..

![image](https://user-images.githubusercontent.com/619340/63639321-03a23e00-c692-11e9-9d93-999305dec9da.png)

**Comment by zeffii** [comment]
sv SmoothLines does expect continuous input (ie.. no breaks in the jungle of lines you feed it.. )

**Comment by portnov** [comment]
![Screenshot_20190824_213537](https://user-images.githubusercontent.com/284644/63640232-2430bf00-c6b7-11e9-8baa-1c6f5ae24912.png)
