### ISSUE TITLE
Undefined Sockets everywhere!

### ISSUE THREAD

**Issue by morph3us-net** [nortikin/sverchok#2505]
## Problem statement
I opened a sverchok scene I made with the Beta version and my nodes have undefined sockets all over the place...
![sverchok_nodes_problem](https://user-images.githubusercontent.com/43741267/63352926-3da5d400-c362-11e9-8c1a-fb6ab07d2c76.jpg)

Edit:
Ex- and then importing the node tree fixes this issue, I still wanted to write it down somewhere...
I am closing this now, thanks for reading :D

## Sverchok version
I just freshly downloaded the 2.8 branch about 15 Minutes ago.

**Comment by morph3us-net** [comment]
When importing the exported .json there are some connections and nodes missing however...

**Comment by zeffii** [comment]
yeah, this bug is the inevitable consequence of progress. In this case we renamed several socket types to be more easily identifiable as owned by Sverchok. It is less likely that other node based add-ons will interfere with this part of sverchok in the future. 

if you have a json that won't load correctly, then you could rename the following in the file
```
VerticesSocket -> SvVerticesSocket
StringsSocket ->SvStringsSocket
MatrixSocket ->SvMatrixSocket
```
we could maybe offer a script that automatically renames these before loading, a pre-processing step in  the json loader..
