### ISSUE TITLE
New categories for svb28

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#2523]
just thinking out loud here.

To make this more intuitive for new and current coders, we should make menu categories correspond with the file structure (without exceptions). Ideally it would be obvious which categories to use, but some nodes perform very unique tasks, while other nodes perform a great variety - this means it's not always clear in which category to put a node for maximum logical coherency. 

Doing that in the Sverchok app structure is not trivial, but it will happen eventually - What i want to do is have a `Lite Menu`, which is a subset of the main Menu (maybe `Shift + ]`... ) , where a start can be made to re-categorize the nodes, and hide a few nodes

**Comment by vicdoval** [comment]
I have been thinking about this lately, not so much thinking in the coders but in the noders..
Some ideas that maybe could be done straight in the standard menu:
_Y propose moving:
   - Random Vector to the `Vector `Category
   - Bend object along path and along surface to `Transforms`
   - KDT closest edges and KDT closest Path to `Modifier Make`..

_Categories that could be added: 
   - Modifier Sanitate: Delete Loose, Remove Doubles (recalling it Merge by Distance), Limited Dissolve, Recalc Normals...
   - Randomness: Noise, Turbulence, Random Num Gen...
   - Script: SNL, SN Fuctor, Formula, Excec Node Mod, Deform by Formula....

_ Maybe we could offer more than one menu arranging things in a different way for example one by topic and the other by place in the node tree ( for example text_in could be in `text` category in one menu and in the other in `Inputs` category) or offer partial menus (one Inputs menu and one Outputs menu)

**Comment by zeffii** [comment]
i also think Stethoscope should be in Viz node.

i'll add Text socket to indexviewer. sooon.

**Comment by zeffii** [comment]
"sanitize" would be the correct term I think?..

anyway,,, categories are hard.. so expect progress to be slow -- we might not even reach consensus.  for instance i'm not settled on the categories and i've been thinking about this a long time.

but something has to be done.  We could also just have two menus, and put all Blender related interaction nodes in one menu , and all pure sverchok nodes in their own menu.

**Comment by vicdoval** [comment]
I know is a hard topic but as you said something has to be done
I think #2528 is one step and to me it looks far more organised than what we have right now   

We could have a master menu with everything and smaller menus with parts of it (Inputs, Outputs...)

**Comment by zeffii** [comment]
for the time being I would like to suggest keeping that `archaic index.md` derived menu, for simplicity and something to fall back on.

i'll open also a PR, but i wish to experiment/show first how we might make a more dynamic menu, using built in Blender features instead of relying on Python's dynamic instancing.

**Comment by DolphinDream** [comment]
It would be nice if the index.md goes away. 😃 often time I add different nodes to the same category in different branches and when merging and rebasing I always have to fix conflicts. These are small conflicts of course, so no biggie, but I always wish I didn’t have to monkey around with fixing these small conflicts. 

As the nodes (files) are added to dedicated category folders as they appear in the index.md, couldn't the menu info be derived from the node file locations?

**Comment by portnov** [comment]
I think we would like to order nodes in each category kind-of-logically, not random or even alphabetically - which we would get if we would just list `*.py` in directories. Separators in menus are also useful.

As an option, we could split one big `index.md` to several index files — one per category/directory, for example `generators/index.md`, `vector/index.md` and so on. Root index.md would just list categories in order which we like to see in the menu.

**Comment by Durman** [comment]
Instead of making up our own categories we can take Blender existing categories, look [here](https://docs.blender.org/manual/en/2.80/modeling/meshes/editing/duplicating/index.html). 
I have tried to categorize some nodes among 4 Blender categories and  It looks like many of them are fittable in this categories. Probably more categories can be taken from there. Using Blender existing categories has benefits such as that it is something with which users are already familiar.


**Transforms**
All nodes that already are in there.
- `Smoth vertices`
- `Transform select`
- `Bend object along surface`

**Duplicating:**
- `Extrude region`
- `Extrude edges`
- `Extrude separate faces`
- `Extrude separate faces lite`
- `Inset special`
- `Duplicate objects along edge`
- `Adaptive edges`
- `Adaptive plygons`
- `Bevel a curve`
- `Fractal curve`
- `Solidify`
- `Pipe`
- `Matrix tube`
- `Iterate matrix transformation`
- `Lather`
- `Offset`
- `Offset line`
- `Contour 2D`
- `MultiExtrude alt from addons`
- `Wireframe`

**Subdividing**
- `Bevel`
- `Bisect`
- `Cross section`
- `Smooth lines`
- `Subdivide`
- `Subdivide lite`
- `Triangulate mesh (heavy)`
- `Triangulate mesh`
- `Split edges`
- `Delaunay 2D`

**Clean up**
- `Limited dissolve`
- `Join triangles`
- `Unsubdevide`
- `Remove doubles`
- `Mesh beatify`
- `Delete loose`
- `Fill holes`

Modifiers category can be occupied by nodes such as `CSG Boolean 2`, `Wafel`, `Voronoi 2D` which do some hard work.

Cad category can be dedicated to 2D nodes.))

**Comment by vicdoval** [comment]
I don't think there is a better way to find a node than in the search bar,  so the menus are more used to explore and to learn, in that case I agree that using the Blender Catergories is the way to go.
A couple of notes of the above list are: 
Delunay 2D I think should go with the modifiers because it does not create new geometry
Although i like the CAD category would try to find another name or it could be merged with the new Modifiers category
