### ISSUE TITLE
Viewer BMesh MK2 outputs objects in a wrong order

### ISSUE THREAD

**Issue by ashumikhin** [nortikin/sverchok#2541]
## Problem statement

The order of objects output from Viewer BMesh MK2 node  does not match the input order, which makes it difficult to identify output objects for further processing.

## Steps to reproduce

![nodetree](https://user-images.githubusercontent.com/54604667/65189918-a0ca7980-da7a-11e9-8862-9930441f58f4.png)

1. Make 11 or more meshes
2. Instantiate them with Viewer BMesh MK2
3. Apply different matrices to the original meshes
4. Apply same matrices in the same order to meshes from steps 4 and 5
5. Visualize meshes from steps 3 and 4 with Viewer Draw
6. Connect a Stethoscope to Viewer BMesh MK2

## Expected result

![expectedresult](https://user-images.githubusercontent.com/54604667/65189916-a0ca7980-da7a-11e9-918c-740f94fae7ef.png)

Equal results from steps 4 and 5
Objects in Stethoscope in creation order

## Actual result

![actualresult](https://user-images.githubusercontent.com/54604667/65189914-a0ca7980-da7a-11e9-83b4-3991ff1d31a6.png)

Different results from steps 4 and 5
Objects in Stethoscope sorted by name

## Sverchok version

0.5.9.6 release ZIP

**Comment by ashumikhin** [comment]
Fixed this for myself by changing lines 51 and 104 of _viz\viewer_bmesh_mk2.py_ from
`    name = node.basemesh_name + "_" + str(idx)` 
to
`    name = node.basemesh_name + "_" + "%04d"%idx`

**Comment by zeffii** [comment]
glad you managed to solve it for yourself @ashumikhin . This particular feature is fixed in `b28`.

technically the code you changed doesn't make a difference to the order in which the objects are written to (..updated in) the scene.  Name will still correspond to the real index of the object internally to the node, each object produced is according to the items in the incoming vertex or matrix lists...).

The output of objects from the node's `SvObjectSocket`, does (you are quite correct) output in the order which is not so useful in your case.

I propose instead of adjusting the naming convention, to instead adjust the way "get children" is implemented.

https://github.com/nortikin/sverchok/blob/master/nodes/viz/viewer_bmesh_mk2.py#L432-L436

that way we don't break/(cause issues with) existing Blends

**Comment by zeffii** [comment]
or even this line could resort the objects based on natural sorting...
```
        if self.outputs[0].is_linked:
            self.outputs[0].sv_set(objs)
```
`objs` above is sorted like `0. 1. 11, 12, 13, 14, 15, 16, 17, 18, 19, 2. 20, 21 ....` (alphanumeric sorting)

**Comment by zeffii** [comment]
because objects have ID properties of `idx`, the resort would be something like
```python
        if self.outputs[0].is_linked:
            sorted_objs = sorted(objs, key=lambda x: x['idx'])
            self.outputs[0].sv_set(sorted_objs)
```

**Comment by ashumikhin** [comment]
> because objects have ID properties of `idx`, the resort would be something like

Thank you, @zeffii ! I suppose I can use a List Sort node to fix the order until I move to b28 then.

**Comment by zeffii** [comment]
I am willing to apply the fix i suggested, and it will solve the issue without breaking the (admittedly silly) existing naming convention.

**Comment by zeffii** [comment]
Thanks for bringing this up btw, there are things related to this which I have not yet wanted to implement in `svb28`..

**Comment by zeffii** [comment]
i've pushed the code-correction

https://github.com/nortikin/sverchok/commit/13c5937623fc9fdc27e5a47d45a7b254e45d03fc

similar would probably need to be done for the other nodes that output objects (to the scene, and then to the object socket)
