### ISSUE TITLE
SVG sources for custom icons?

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#2640]
Currently for custom icons we have only PNG files in the repo.
I'd suggest to add:
* SVG sources for these icons
* Optionally - a shell script which converts SVG icons to PNG by calling inkscape.

**Comment by vicdoval** [comment]
Some thiughts about this:
What do you think is better a single Svg with all icons or individual files?
It would be awesome if the color could be dynamic way but no idea about how to do this.
What should i do with the icons that are from blender. Repeat them? Ignore them?
What about the ones that haven't done (as the Knot one for example)

**Comment by portnov** [comment]
Imho individual files are better.

icons from blender - no need for them, they are available in blender itself.

Abount icons from other authors - I think it's better to ask authors of those icons...

**Comment by vicdoval** [comment]
I see from the quad_spline.svg there is plenty of information that would be repeated in every file... and even some personal data (line 19) If we have one of this for every icon maybe is a little redundant, but maybe worth keeping it...
also maybe it would be possible to keep just the relative export path
 https://github.com/nortikin/sverchok/blob/5d73a7c21a632710174d2e1804695ca22e0a2007/ui/icons/svg/sv_quad_spline.svg#L5-L58

Another question is about visibility, I guess you are using a light blender theme because on the default theme (dark) the quad_spline icon is almost invisible. 
I see two alternatives: 
making the icons visible in both cases with outlining
or supplying two versions, light and dark icons (right now the icons folder is 350 Kb that would be doubled)

I think it would be great to get a unified iconography, for that we need a unified opinion. That is why I was asking about Blender icons. If we go for the outlining solution the Blender icons will look different unless we replace them by our icons...

**Comment by vicdoval** [comment]
Another little detail is that some of the icons I did had GIMP at the end of the pipeline so to create a proper svg I would need to vectorize them back to svg or make them again only in Inkscape

**Comment by portnov** [comment]
* There should be some "svg sanitizers", which remove unnecessary information from svg. Inkscape's option to "save as plan svg" also worth trying.
* if you use gimp/whatever to do final steps (like polishing icon to be "pixel-perfect") — that's ok; svg sources are mainly useful not for reproducing the existing icon, but for creating new ones based on existing.
