### ISSUE TITLE
replace_socket function

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2699]
I see the function is rather widely used. It deals with removing and adding sockets. It has different protection from updating node tree unlike latest solution with throttling updates during change sockets of a node. 
@zeffii  Should approach of ignoring update events of this function reconsidered?

https://github.com/nortikin/sverchok/blob/37daa92d2e8bea138bf76c98a28e86c39a6f3143/data_structure.py#L794-L829

**Comment by zeffii** [comment]
nope, i was going to add throttle to that too, and remove the freeze part..

**Comment by zeffii** [comment]
that's my next pass of the update system.. no ETA.

**Comment by zeffii** [comment]
it's tricky.

if we have a wrapped throttle function, and we are inside it.. and the replacesocket "unthrottles" after exiting replacesocket, the state is False.. while still inside the wrapper function. This is why i'm leaving the freeze/unfreeze for the time being.

**Comment by zeffii** [comment]
i think it might be useful to wrap / decorate the following functions from datastructure

- multi_socket
- changageble_sockets
- replace_socket.

instead of using freeze for these functions, a "context sensitive" decorator can 
1. enter these functions, and make sure `node.id_data.skip_tree_update = True` 
2. leave these functions, in the same `node.id_data.skip_tree_update` that we encountered when entering them. 

but really, this is a little cosmetic..
