### ISSUE TITLE
Matrix In does not understand Vectorisation

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2734]
## Problem statement

Plugging multiple values into Matrix In for Viewer but getting only 1 output. 

## Steps to reproduce

[strange_matrix_behaviour_001.blend.zip](https://github.com/nortikin/sverchok/files/3958247/strange_matrix_behaviour_001.blend.zip)
<img width="1317" alt="Screen Shot 2019-12-13 at 10 41 01 am" src="https://user-images.githubusercontent.com/3952687/70757865-3d0fce00-1d95-11ea-94a5-62ff9e2f615a.png">
<img width="1358" alt="Screen Shot 2019-12-13 at 10 40 55 am" src="https://user-images.githubusercontent.com/3952687/70757866-3d0fce00-1d95-11ea-8c34-9f2c96c4d641.png">

**Comment by enzyme69** [comment]
This one works however... maybe something to do with Bounding Box node?

<img width="893" alt="Screen Shot 2019-12-13 at 10 44 04 am" src="https://user-images.githubusercontent.com/3952687/70757958-83652d00-1d95-11ea-91bc-b60df929b3e4.png">
<img width="881" alt="Screen Shot 2019-12-13 at 10 44 09 am" src="https://user-images.githubusercontent.com/3952687/70757959-83fdc380-1d95-11ea-9440-40b36124b994.png">

**Comment by Durman** [comment]
I think that this issue is proving that my thoughts about generators are correct. 
#2649

@enzyme69 The thing is that when you treat generators (`rounded box` in particular) with multiple values they start to generate mesh into seperate objects. I think that such behavior of Sverchok is inconsistent and has more downsides than benefits. Just join all objects into one after the generator node.

**Comment by vicdoval** [comment]
Fixed in #2735
