### ISSUE TITLE
Question : is there a way to activate or use some default uv mapping with sverchok 

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#2779]
For example if you use one off the generators they have no uv's except for the polyline is there maybe a solution so that you can use the default uv mapping like with blender 2.82 generators ( sphere / cyclinder etc)
Or is the only way to use the polyline ? or to fake it with cycles if you have no deformation ?

**Comment by zeffii** [comment]
the BMeshViewer is a tricky one to implement auto UV for, because - of all the Object viewers it is the one that outputs a Mesh directly. The other viewers, Polyline / Curve / Type / SkinMesh all output their own mesh as a function of the input geometry; in the case of the Polyline viewer, it takes a sequence of vertices, and generates a Curve from it, which is turned by Blender (via parameterization) to a "Solid Curve".

We pass this 
```
X ----- X -----X -----X
```
Blender extrudes it by a given radius (per point), and can auto generate UV
```
   -----------------------
 /                     /   \
|   x -----x------x----| x  |
 \ _____________________\  /
```

For those nodes that generate Object data that can generate it's own UV, we can certainly add that feature (as was added with PolyLine), But for BMeshViewer i'm really not sure what the options are. Maybe @portnov ? 

I'd be surprised if we can't offer some solution, but it's not my area of interest.

**Comment by BennyGovaerts** [comment]
Is there maybe a easy way to make a sphere with the polyline

**Comment by zeffii** [comment]
as for UV data from our generators:

Our generators are python implementations, and do not get automatic UV generation from Blender. They are similar to the Blender Objects operators (Circle, Cylinder...etc) only in name, not under the hood.

At the moment our generators do not output data other than Vertex/Edge/Face , but I think we could offer an `UV mapper node` , that can generate the UV Data required. (my preferred option for most generators) or update certain generators to output FaceData/Dict with UV data, and give the BMeshViewer node a new UV input socket.... maybe.

**Comment by zeffii** [comment]
i suspect you can make a sphere from polyline, at at least something that will render as a sphere :)

**Comment by portnov** [comment]
I believe we have two options here:
1) Simplest one: add a node, that takes Object (generated by BMesh viewer, for example), and generates "simple UV" (by cube, cylinder or sphere projection) for it. I'm not familiar with Python API for UVs, but afaik it exists and can be used.
2) Add "UVData" socket for at least some of our nodes (generators, for example, can generate correct UVs); at least BMesh-based nodes could correctly transform UV mappings (bmesh operators probably do it already, but I didn't check). "BMesh viewer" could have "UVData" input. This is more work, because 1) we would have to modify many nodes, 2) we would have to study Mesh UV API for BMesh Viewer, 3) we would have to figure out the correct way to pass UVData between nodes...

**Comment by zeffii** [comment]
something like this .. but you'll need to tweak it 
![image](https://user-images.githubusercontent.com/619340/71717627-f0aa3200-2e18-11ea-8017-a094680f60f1.png)

**Comment by BennyGovaerts** [comment]
Another solution could be the cast modifier , but this is not working if you use a matrix , because the modifier is not used for the other objects

**Comment by BennyGovaerts** [comment]
1. Sphere projection /cyclinder /cube projection would be fine for me

**Comment by Durman** [comment]
According my experiments with UV mapping here #2218, I see that Sverchok should have simple node which just create default UV mapping for given objects. Default UV is being created by Blender with putting every polygon of given mesh inside quad with sides equal 1. This functionality could be alredy useful in many cases. 

Actually I can create script for SNL which would create default UV maps right now but does not feel creating normal node for this yet.

**Comment by zeffii** [comment]
here's a nice one:

![image](https://user-images.githubusercontent.com/619340/71719283-20a80400-2e1e-11ea-9f85-05a4cba57606.png)

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/71719342-55b45680-2e1e-11ea-80c8-0c4d609d6626.png)

**Comment by BennyGovaerts** [comment]
Excellent , one minor problem i think there is a  problem with blender 2.82.6 
![image](https://user-images.githubusercontent.com/49908008/71719791-b98b4f00-2e1f-11ea-9b51-b7b138889dd3.png)

**Comment by BennyGovaerts** [comment]
Sorry, i have made a mistake with the circle degrees settings , excellent solution zeffi , thanks 
![image](https://user-images.githubusercontent.com/49908008/71721208-81d2d600-2e24-11ea-8854-941ec739708e.png)

**Comment by zeffii** [comment]
so, to sum up.

in some Object Nodes yes, but BMeshViewer not yet.

**Comment by Durman** [comment]
Probably I will merge this before sunday #2797 
[node documentation](https://github.com/nortikin/sverchok/blob/f28e511558ddd94e126d6165eeb9f22f5f9a362a/docs/nodes/object_nodes/set_custom_uv_map.rst)
