### ISSUE TITLE
Monad & duplicate socket names cause interference

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#2791]
With Blender 2.81 or Blender 2.82
1.Make a Monad  group off  2 map range nodes 
2.Go inside the monad -group connect all the input output nodes 
3.Go out side the monad 
4.Move the sliders from map range 1 and for some reason it change the map range slider from node 2 & 1 together 
![image](https://user-images.githubusercontent.com/49908008/71780954-3c9bd900-2fc9-11ea-965f-90cf185cd3a1.png)
![image](https://user-images.githubusercontent.com/49908008/71780970-8dabcd00-2fc9-11ea-9794-1d4735033ecc.png)

**Comment by zeffii** [comment]
it's a naming issue, and a logical issue too. Imagine if our standard nodes had multiple inputs with the same name, it would be easy to get confused. Only socket index is what differentiates them then. The same happens with any other node arrangement of nodes that have input sockets with the same names connecting directly to the Group Inputs node.

![image](https://user-images.githubusercontent.com/619340/71781197-26dbe300-2fcc-11ea-8c37-cf538c6486fd.png)

you are better off creating properties from scratch when you find yourself in this situation. We have a whole feature that lets you add sockets and force properties of the properties :) but the UI for that is arguably a little obfuscated..  you double click on one of the property names ( like i show with the two dots )

![image](https://user-images.githubusercontent.com/619340/71781314-7ec71980-2fcd-11ea-8826-7707ac9dbf3a.png)

please note, that this is another area of limited development of monad,  not just 2.8 related.

**Comment by zeffii** [comment]
there are several bugs that relate to this issue, it's an area of pretty abstract code which is a little hard to get excited about .. so no ETA.

**Comment by zeffii** [comment]
my advice is to rename the sockets directly after connecting them. that way at no point will there be identical socket names on the Monad. if i recall correctly, that avoids the bug

**Comment by BennyGovaerts** [comment]
ok , i give this a try , thanks for the feedback

**Comment by BennyGovaerts** [comment]
With one map range node this works but not if you use 2 map range  nodes , works this better with animation nodes or do i have then the same problem

**Comment by zeffii** [comment]
animation nodes is completely unrelated to sverchok, they may share similarity in uI only because SV and AN both use the Blender UI API. Implementation details of "node groups" / "Monads" are left up to the developers.

I don't think the issue is that you are using two map range nodes, but rather than the two nodes create a socket with same name (maybe even renaming directly after connecting doesn't avoid the bug )

**Comment by BennyGovaerts** [comment]
yes you are right , renaming is not correct update inside the monad

**Comment by zeffii** [comment]
A few things/thoughts:

1. renaming directly after attaching should avoid the bug, which means that the _renaming operation_ is the most useful feature to fix.
2. I would consider an automatic renamer, so that your SvGroupExternal (and inputs) interface can never have duplicate socket names.
    - the options are `Nodename.PropertyName` , but that makes long socket names which could be useful.. but might be terrible too.
   - 'Capital' + propname , where capital letter bumps to the next available letter

**Comment by zeffii** [comment]
something we should add is a `+` button to create a socket from scratch without first connecting a node.
