### ISSUE TITLE
Monad: Loop: sockets identification

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#2799]
Currently do_process_looped puts data from outputs into inputs, matching them by index only. This can give unpredictable result, if the order of inputs is different from outputs, or if number of inputs differs from number of inputs...

I propose either to
a) Match inputs with outputs by names, or
b) Match them by index, but additionally check that names are equal.

Also, I propose to add explicit check that number of inputs equals to number of outputs.

**Comment by zeffii** [comment]
this is also an intentional implementation detail, it's a loop where order should be explicitly consistent, and not inferred by code - which will also fail depending on the user's alertness. I intentionally do not feel touching this is helpful, the UI allows the user to rearrange the sockets on the input/output nodes to match in indices, instead of immediately forcing the user to rename sockets.

The issue may be more directly a consequence of lack of documentation. Because i like to keep that code from getting more complicated.

**Comment by zeffii** [comment]
but i get where you are coming from, the inputs / outputs could be implemented as if they were `keyword-arguments`, rather than the `place-dependent arguments` as currently.

but i feel this feature may not really be worth the code change.

**Comment by zeffii** [comment]
i've thought about this more. I think this falls into the "wont fix" category, because i don't feel that it's broken, but I'll reiterate that perhaps the docs require creating or updating.

**Comment by zeffii** [comment]
i have not changed my mind. but I will update the documentation to be more explicit (if it's not already)
