### ISSUE TITLE
SV Animation Remote Control can no longer override keyframe 

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2898]
I noticed that since Blender 2.82, SVerchok Bmesh Viewer or Matrix Remote Control can no longer override keyframe animation. In the past, the behaviour is that if I change keyframe, SVerchok will still be calculated last. But not with 2.82. Once keyframed, SVerchok can no longer control the object. --> Animation Nodes can still do it and bake 

SV Object ID Set can actually still override the Matrix of object, but slightly tricky.

<img width="818" alt="Screen Shot 2020-02-24 at 2 28 27 pm" src="https://user-images.githubusercontent.com/3952687/75127208-039efb80-5712-11ea-8248-687649cde2ef.png">

[object_remote_control_001.blend.zip](https://github.com/nortikin/sverchok/files/4243032/object_remote_control_001.blend.zip)

**Comment by enzyme69** [comment]
Video:
https://www.youtube.com/watch?v=tuHeiG8RE9g

In 2.82, when object keyframed, it's pretty much locked and SVerchok no longer transform the object. In the past, if I use arrow key and stepping, I can still see the object moving, hence I can keyframe and bake.

**Comment by enzyme69** [comment]
I have a feeling it's the Frame Info node that's not reacting / locked.

**Comment by zeffii** [comment]
> I have a feeling it's the Frame Info node that's not reacting / locked.

unlikely, all that nodes does is read the current frame.

i think whats happening is that Sverchok is updating the location data before the frame change (using frame_change_pre ) , this is a setting in the preferences ( POST/PRE ) , try POST.  no guarantee.

**Comment by zeffii** [comment]
## What i really think.
I know the following is not your question directly, but i think you're having this problem because you are forced by the current paradigm to approach animation with Sverchok in an arse-backwards way. it's not that I don't want to help you here, Blender dev have not added keyframe support for PyNode Nodetree sliders (last time i checked..).

maybe when add-on's are allowed to set keyframes from their UI (like sliders on nodes in a material...) you'd have more fun doing animation from the UI sliders/graph editor.

## Untill such time...:
i'm not sure it's a good feature tooverwrite keyframes. it feels so unintuitive.  How about using the FCurve In node, and reading evaluated values from that, and using an keyframed-Empty  ?

```
Sverchok =/= Animation Nodes 
```

**Comment by enzyme69** [comment]
It's not Pre and Post thing, I tested it. I should logically this one. Calculate SVerchok last...

Even if I use F-Curve over it, if I plug Frame node, and assign keyframe, SV Bmesh Out or Remote no longer have control...

<img width="1057" alt="Screen Shot 2020-02-26 at 10 36 31 am" src="https://user-images.githubusercontent.com/3952687/75297390-db370e80-5883-11ea-94d5-117379d6a657.png">

I know one thing that seems to "calculate last" it's the Object ID Set, and if I use matrix-world.

**Comment by zeffii** [comment]
at some point we will need to take another look at the _update system_ and the _handlers_, I think a partial rewrite is on the horizon. Sverchok was hoisted from 2.79 to 2.8+ with as few changes as possible, to get our use-cases addressed.

> Even if I use F-Curve over it,

ah..still with the keyframes. controlling objects that are already keyframed sort of breaks the reason-de-etre of having keyframes on those objects. convince me otherwise. or explain better.

What i meant by the FCurve node, is you have an Empty, which you keyframe, and you control the Sverchok nodetree with that, the Sverchok nodetree should not be controlling objects that are already keyframed. ...

is Animation nodes is changing the existing keyframe? maybe what's happening (and Sverchok does not do this) is animation node is looking if the object had a keyframe at a given frame, and removes is and updates the node and resets the keyframe to the new state?  i don't know.

**Comment by zeffii** [comment]
hold on.. something simple might be possible.  let's look at the code.

https://github.com/nortikin/sverchok/blob/8773d11847e1bac66e6fe35527d87700e998826f/nodes/scene/obj_remote_mk2.py#L41-L52

this code might not be doing what it thinks it's doing, anymore. it may require
```
     for obj, mat in zip(objects, matrices): 
          with self.sv_throttle_tree_update():
              setattr(obj, 'matrix_world', mat) 
              obj.data.update()  
```

**Comment by zeffii** [comment]
now .. if that object has a keyframe and you want the sverchok node to change the state of the keyframe, there would need to be additional code.. I think.

i'll poke around with it.

**Comment by zeffii** [comment]
note to self.. to determin the first and last keyframe

![image](https://user-images.githubusercontent.com/619340/75335264-78487600-5889-11ea-86c4-00f7a940e742.png)


```
>>> cube.animation_data.action.frame_range
Vector((0.0, 36.0))
```

**Comment by zeffii** [comment]
if you want this resolved keep asking questions.

**Comment by enzyme69** [comment]
Thanks so much Zeffii!! Reading your last response before closing, and will try~~

**Comment by enzyme69** [comment]
[matrix_anim_001.blend.zip](https://github.com/nortikin/sverchok/files/4309825/matrix_anim_001.blend.zip)

Ok here is another simple animation, default box looping in circle, that I wish to keyframe bake and done with. Keyframe cannot be overridden as for now. In the past it works. 

<img width="665" alt="Screen Shot 2020-03-10 at 1 02 30 pm" src="https://user-images.githubusercontent.com/3952687/76272393-7215b900-62cf-11ea-91e0-1ca2527e17f2.png">

My current solution is to try using Matrix_World of Object ID Set.

**Comment by zeffii** [comment]
just to get this straight,  in this scenario
- you are using BMV to generate an object, then switching it off 
    - (Live-> Not Live)
- you are keyframing it from Blender, by scrolling around the timeline and keyframing manually
     - at this point, when BMV is no longer live, it will no longer be processing and no longer try to do anything to the objects it is associated with.
- then you pass a matrix using matrix socket on Object Remote.
    - and here you want Sverchok to "update" the obj.matrix_world if that frame has a stored keyframe

Q. the reason you are doing this is to let Blender take care of the interpolation between states ?

a few thoughts here..
- maybe Object Remote control also needs a Live/Not Live mode so you can prohibit the node from updating nodetree.
- in object 
------

remember i am not an animator. and don't animate (even for fun...) so it is important if you want this feature to behave more friendly/useful that you take more time to describe the problem step by step.

**Comment by zeffii** [comment]
why are you setting keyframes on an object generated by Sverchok in the first place?

**Comment by enzyme69** [comment]
Lots of convenient nodes that generate matrix from Sverchok beyond just Animation Nodes. I am especially always wanted to work with Shapes and modifying shapes with SV.

**Comment by enzyme69** [comment]
A. Yes, the reason I manually step frame by frame is so that SV can hopefully update and override the object transform positions, or pose bone positions, etc so that I can keyframe.

I was hoping Object Remote Control to override and works more like Object ID Set "matrix_world"
