### ISSUE TITLE
SN : UI curves manual 

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#2985]
How can i use more then one Ui curve manual with the updated  Sn lite node 👍
 
- For example i: if i use more then one SN lite node with curve manual it use the same settings from the other SN lite node

- Load a new SN lite node make no difference 
- Reset node etc... they still use the same settings & move together if you change these nodes etc...

![image](https://user-images.githubusercontent.com/49908008/76922350-b8bb7280-68d0-11ea-94a9-f0e3f7cf476d.png)

![image](https://user-images.githubusercontent.com/49908008/76922387-d7216e00-68d0-11ea-9aad-02978223d3ca.png)

**Comment by zeffii** [comment]
due to the nature of the "hacky" method used to display the curve UI you must understand a little how it works.

The interaction with the curve-ui  on the snlite node will as you've realized, not update the sverchok node tree, because actually the snlite node is merely displaying a UI element for an RGBCurve node of a automatically created Shader NodeTree (behind the scenes).

by default the example snlite script will create a shadernodetree + rgbcurve node for us, and this is what you'll see in the `directives` part of the snlite script (the part between the quotes)

```
"""
in floats_in s .=[] n=0.0
out floats_out s
ui = my_temp_material2, RGB Curves2
"""
...
...
<snipped>

```
by default this will create a material called "my_temp_material2", and an "RGB Curves2" node inside that material.

what you want to do is make a copy of the `UI_curves_manual<copy>.py` script in the text editor. and change those two names ..to something like
```
ui = my_temp_material3, RGB Curves3
```
and then load the script into a new SNlite. Then you will have two independant curves.

---
but really, if this seems a bit of a kludge.. i'm totally there with you, it blows hard.. it was merely added to show what can be done from SNLite (but the breakability might be out of your comfort zone..)

**Comment by zeffii** [comment]
because Blender ui toolkit does not offer a super convenient way to do that, without automatically creating a shade nodetree for "borrowing" the rgbcurve ui element, that "lite" implementation is acceptable, and better than nothing.  But because i'm not super happy about it.. i don't go out of my way to advertise it.

an altogether more stable way would be conceive of ... and i'm just thinking here ... a dedicated Collection composed of a quad empty and a Curve Object.  where we use the quad empty as the bounds of a curve, and the Curve itself as the evaluator of an input.

![image](https://user-images.githubusercontent.com/619340/76941684-c129a280-68fc-11ea-9135-20ae1560bf04.png)

it would be also a kludge, but i think supremely more controllable than the UI of the rgbcurve.

**Comment by zeffii** [comment]
actually, the plane isn't even needed there..

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/76942237-b0c5f780-68fd-11ea-9dad-fc91d855f9b7.png)

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/76942651-6133fb80-68fe-11ea-867b-d9bef86169a5.png)

it's not super difficult to make a Curve Evaluator node, that automatically gets the X/Y bounds (ignoring Z) and accept an incoming list of floats (0.0....1.0) as X and for each X inputted, return the Y value.

**Comment by zeffii** [comment]
this may persuade me to implement a quick'n'dirty version of such a node, with graph drawing in the nodeview (not editable in the nodeview... just to see whats going on)

**Comment by zeffii** [comment]
but back to the SNLite ui curve snippet..  the SNlite will always create that shadetree+rgbnode .. even if they are deleted.. i think. You might even be able to have multiple nodes use the same shadetree.. (can't remember if this is what I implemented)
```
# one node
ui = my_temp_material2, RGB Curves2

# another node
ui = my_temp_material2, RGB Curves3

# another another node
ui = my_temp_material2, RGB Curves4
```

they all would reuse the same material (shadetree) but generate new RGB Curve nodes, inside the one material.

**Comment by vicdoval** [comment]
Another approach:
The Oscillator node on the 'Custom' mode does this evaluation of the Y coordinate
![image](https://user-images.githubusercontent.com/10011941/76955467-8c284a80-6912-11ea-84e9-f99a7bd21a43.png)

**Comment by BennyGovaerts** [comment]
> but back to the SNLite ui curve snippet.. the SNlite will always create that shadetree+rgbnode .. even if they are deleted.. i think. You might even be able to have multiple nodes use the same shadetree.. (can't remember if this is what I implemented)
> 
> ```
> # one node
> ui = my_temp_material2, RGB Curves2
> 
> # another node
> ui = my_temp_material2, RGB Curves3
> 
> # another another node
> ui = my_temp_material2, RGB Curves4
> ```
> 
> they all would reuse the same material (shadetree) but generate new RGB Curve nodes, inside the one material.

After changing the script for every new node this works fine .  Thanks for the tip .
 # one node
 ui = my_temp_material2, RGB Curves2
                                          RGB Curves.002
etc....

**Comment by enzyme69** [comment]
@vicdoval Victor I tried your method on Cylinder Meridirian but somewhat it does not give accurate representation of the line shape... wonder why

<img width="753" alt="Screen Shot 2020-03-19 at 10 33 42 am" src="https://user-images.githubusercontent.com/3952687/77016997-58f6c180-69cd-11ea-9705-48a0ba34a8e4.png">


<img width="1353" alt="Screen Shot 2020-03-19 at 10 33 46 am" src="https://user-images.githubusercontent.com/3952687/77016989-53997700-69cd-11ea-8465-7e83650635f6.png">

[sv_curve_sampling_004.blend.zip](https://github.com/nortikin/sverchok/files/4351899/sv_curve_sampling_004.blend.zip)

**Comment by enzyme69** [comment]
Yeah it seems to be less precise around beginning and end.

<img width="630" alt="Screen Shot 2020-03-19 at 10 41 42 am" src="https://user-images.githubusercontent.com/3952687/77017299-3add9100-69ce-11ea-88ee-43e7299cc1f7.png">

**Comment by enzyme69** [comment]
[sv_curve_sampling_005.blend.zip](https://github.com/nortikin/sverchok/files/4351955/sv_curve_sampling_005.blend.zip)


Hmm... maybe it's kind of ok, it seems to smooth it or something. ¯\_(ツ)_/¯ 

<img width="602" alt="Screen Shot 2020-03-19 at 10 49 06 am" src="https://user-images.githubusercontent.com/3952687/77017726-5006ef80-69cf-11ea-94ad-5906298a6a7c.png">

**Comment by vicdoval** [comment]
@enzyme69 From Oscillator  docs:

> Advanced Parameters
> -------------------
> 
> In the N-Panel (and on the right-click menu) you can find:
> 
> **Wave Interpolation**: (On Custom mode) Define how the wave should be interpolated (Linear or Cubic)
> 
> **Wave Knots Mode**: (On Custom mode) Define how the wave knots should be interpolated (Manhattan, Euclidan, Points or Chebyshev)
>

**Comment by BennyGovaerts** [comment]
Or i can do it like this,  ( ![image](https://user-images.githubusercontent.com/49908008/77024777-b704b400-698f-11ea-9fec-16ec5aed0f9a.png)

**Comment by enzyme69** [comment]
Great!! Thanks!

**Comment by BennyGovaerts** [comment]
Hmm , i think the idea from vicdoval works correct , my idea is just the fast way hmm need some finetuning .....

**Comment by BennyGovaerts** [comment]
![image](https://user-images.githubusercontent.com/49908008/77025867-870ae000-6992-11ea-883a-030a048731c4.png)

**Comment by nortikin** [comment]
also my lovely profile node
