### ISSUE TITLE
Presets and BMesh Viewer Autonaming Does Not Work

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3039]
I am starting to use Presets more often, and realized nodes like BMesh Viewer will not auto name the output. If I specified "Alpha" it will always be "Alpha" and it will clash with whatever output Bmesh already there.

Is there any work around this?

<img width="1257" alt="Screen Shot 2020-04-05 at 11 41 38 am" src="https://user-images.githubusercontent.com/3952687/78464916-90d26880-7732-11ea-87b5-e85a13ca4ff1.png">

**Comment by Durman** [comment]
#3028

**Comment by zeffii** [comment]
i didn't implement presets, @portnov will have a better idea of what's happening there.

- sv_init will automatically `+1` the scene name index counter we use to select the next greek letter 
     - if that index is not incremented, then sv_init of the new node was not called (which is possible, the blender node 'copy'/'duplicate' operator also does not call the `sv_init` of the new node
     - if that index is increment and yet the viewer still gets an existing name, `sv_init` has been called but the `basedata_name` of the new viewer has been assigned the name it got when it was stored (this results in multiple nodes with the same `basedata_name` 

a way around this is to give your objects better unique names before storing the selection as a preset. In this sense the problem is one of bookkeeping. At some point sverchok must stop holding your hand, or the amount of defensive code we would need to add will start to be less fun to maintain.

A solution will catch some scenarios, but almost certainly not be able to anticipate all name conflicts. A preset could be relatively complicated, have several disjoint graphs and some manually picked object_id_selection nodes pointing at an object which a specific name.

**Comment by portnov** [comment]
"Preset" mechanism actually just imports nodes with all settings from json files, using our standard "iojson" code. Maybe it could call some "node.after_import()" method on each node which was imported, so that each node can do something fancy, as renaming Alpha to Beta.

**Comment by zeffii** [comment]
iojson would be able to offer a supreme level of customization there.

ah ha.. i think.. maybe the `basedata_name` will have to implement `the set/get attribute`... or a wrapper for the updateNode function attached to that property.

**Comment by zeffii** [comment]
- it could automatically switch off the Live feature,  turn the basedate_name field into the warning color
     - I can imagine a scenario where that is not preferable, especially when there are nodes downstream that depend on the output of that node

or

- if you failed to name objects with the anticipation that they will be used as presets later, then automagic only allow the new node to have a basedata_name not shared by any other node in the tree, or indeed in `bpy.data.node_groups`

the whole issue of having to test names is a royal pain, and a main reason to use the VD drawer for most presets.

**Comment by enzyme69** [comment]
Yeah, that makes sense, I can live with VD for now, I supposed. Automating creation of VD and BMV will be handy too. Anything, if can improve is greatly appreciated! Thanks~

**Comment by zeffii** [comment]
i don't mean to be dificult here either btw. (altho ofcourse i'm naturally inclined to avoid any kind of coding that I don't think is necessary..and I might seem obtuse)

but here it's a classic "the remedy will kill the patient" with a bit of "whackamole"

when we introduced nodes that generate scene-meshdata (ie real geometry objects), i should have dropped the autonaming..to force users to think about the names . There are autonames purepy because i am lazy.
