### ISSUE TITLE
BUG: Obj Instance MK2 Axis Angle Anim not working

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3118]
[axis_angle_not_working.blend.zip](https://github.com/nortikin/sverchok/files/4535389/axis_angle_not_working.blend.zip)

I tested the Obj Instance MK2 node, the Matrix Input for rotation Axis Angle does not seem to be working when I try to animate it under 1 axis. I mean I can pipe it random axis, but it does not rotate. Euler one works.

<img width="974" alt="Screen Shot 2020-04-26 at 11 27 39 pm" src="https://user-images.githubusercontent.com/3952687/80309036-a577bd00-8815-11ea-8903-f1d5171482e0.png">

**Comment by zeffii** [comment]
i'm not sure what you're talking about
![image](https://user-images.githubusercontent.com/619340/80310495-4f862380-87db-11ea-9111-c573968871e1.png)

it's possible that the torus you are inputting has a matrix_world that is transformed.

**Comment by zeffii** [comment]
and rotation around the Z axis seems like an operation that you won't really appreciate with a torus...rotating around it's central axis...

**Comment by DolphinDream** [comment]
@enzyme69 can you clarify what the problem is? show an animated gif maybe? 

If you set an axis different than Z (0,0,1) (say: (1,1,1)) you will notice a rotation.

Also, note the angle units for the Matrix In node on the Property Panel (currently set to Degree). In general, if you think you enter a 1 radian angle in one node and it didn’t rotate much, it’s because 1 is probably in degree. Check the PP panel for this angle units to set them to your desired units (Default = degrees)


<img width="1151" alt="SV-matrix-in-rotation" src="https://user-images.githubusercontent.com/2083719/80312011-ebe70080-87b0-11ea-9018-ae8fb4e851a1.png">

**Comment by enzyme69** [comment]
Ok I think my bad, the rotation was 0,0,1 by default and that torus was indeed spinning and I missed to see it.
