### ISSUE TITLE
Sanitize utils

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3121]
There is list of modules which usage I did not find:

- cad_module.py
- debug_script.py
- group_tools.py
- loadscript.py
- sv_git_connection.py
~- sv_load_archived_blend.py~
- sv_prefs.py
- sv_vector_utils.py
~- text_editor_plugins.py~
~- text_editor_submenu.py~

I think they should be deleted.

**Comment by zeffii** [comment]
i think these can go:
- sv_git_connection
- group_tools, is deprecated but interesting
- loadscript, is also deprecated but interesting

must stay:
`sv_load_archived_blend`  registers the operator that loads the archived zip from an url.

**Comment by zeffii** [comment]
file | status
----|-----
cad_module.py | dunno
debug_script.py |  kill
group_tools.py  |  kill, but has interesting code
loadscript.py     |  kill, but has interesting code
sv_git_connection.py |  kill deprecated since we use tokens
sv_load_archived_blend.py |  keep i use this every day.
sv_prefs.py  |  kill
sv_vector_utils.py |  keep
text_editor_plugins.py  |  dunno
text_editor_submenu.py |  dunno

**Comment by zeffii** [comment]
text_editor_plugins.py  is used for  refreshing f.ex snlite using ctrl+enter while in the TextEditor. it stays!

**Comment by zeffii** [comment]
`text_editor_submenu.py`  also keep. i will fix that code to add snlite templates to the TextEditor.

**Comment by zeffii** [comment]
`cad_module` was entirely deprecated from what I can tell. cool !  kill it.

**Comment by portnov** [comment]
You can mark some methods with `@deprecated` decorator from `sverchok.utils.decorators` if you want to remove the method in future but suspect that someone may be using it in a script node

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/3280 resolves this
