### ISSUE TITLE
gists from turtle PR are not loading

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3228]
I am trying to download example from gist from portnov
https://github.com/nortikin/sverchok/pull/2760

It does not work. I feel sad whenever that happens. Such a good example but broken. I wonder if we need to post a screenshot of node tree or make video about it so that it does not lost forever.

I would also recommend zipped blend.

**Comment by zeffii** [comment]
I agree. .blends would be preferred for these examples, but at the time of making that example SNLite had different behaviour, and probably worked perfect.

the top one
![image](https://user-images.githubusercontent.com/619340/82033068-77f79400-969c-11ea-902c-98c8751d43ed.png)
and manuall edited the gist:  https://gist.github.com/zeffii/07e4c9ecfb8ebf1d961351204cd37d39

i suspect the rest too, will experience similar issues. The problem here is that the script loaded into SNLite expects to be fully connected, and does not stop further processing early enough, therefore it throws an exception, and that exception prevents the rest of the gist from loading.

the solution, if you look at the `diff` in my gist are simple, but important. The additions make it so that even when the node is not connected fully , it will not throw an exception.

**Comment by zeffii** [comment]
the second one... this almost works. https://gist.github.com/zeffii/09093e5ecca584def83fb36616dfabf2

**Comment by zeffii** [comment]
but those things are a WIP (work in progress, you know..) prior to that PR being merged, so you have to expect gists to not work, and be pleasantly surprised if they do work. Nothing is broken here.

**Comment by zeffii** [comment]
but i might revert / fix SNLite's process_script function to not Raise an exception like that.

**Comment by zeffii** [comment]
the original gists should work again if you update sverchok
https://github.com/nortikin/sverchok/pull/3230
