### ISSUE TITLE
GP Object ID Access - How to Split Strokes?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3277]
Since GP+ Macro is still broken from last time... I cannot get to the frame or strokes so I am trying to recreate it using Object ID nodes, but stuck in "how to split strokes".

<img width="1193" alt="Screen Shot 2020-05-25 at 12 21 29 pm" src="https://user-images.githubusercontent.com/3952687/82772429-6d9a7e80-9e82-11ea-8d51-cb2ad3af689a.png">

[gp_test_003.blend.zip](https://github.com/nortikin/sverchok/files/4674953/gp_test_003.blend.zip)

**Comment by zeffii** [comment]
why you no show error message? :)
```
location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_extra_search.py", line 155, in execute
    getattr(DefaultMacros, handler)(self, context, term)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_default_macros.py", line 253, in verbose_macro_handler
    n = nodes.new(node_bl_idname)
RuntimeError: Error: Node type SvGetAssetProperties undefined
```
fixed by  https://github.com/nortikin/sverchok/pull/3279

![image](https://user-images.githubusercontent.com/619340/82790597-9a439b80-9e6c-11ea-9cc3-04c3695029e3.png)

**Comment by zeffii** [comment]
i am aware that in the Pick Frame node, the list of available frames (gp_frames property dropdown) does not re-populate automatically . you must press Pick Frame again or something to update the tree 

also the node that turns red even when you expect the layout to work, will need you to press f5 to refresh the tree.

because sverchok is not a "first class citizen" in the Blender ecosystem there are things that will always be a bit fiddly, until someone who uses these things finds the energy to understand the underlying code.

**Comment by zeffii** [comment]
we can simplify that macro.

![image](https://user-images.githubusercontent.com/619340/82791651-6ec1b080-9e6e-11ea-851d-ff9c5712318b.png)

**Comment by enzyme69** [comment]
Thanks @zeffii it works again~ I am trying to use it with Voxel Remesher

<img width="461" alt="Screen Shot 2020-05-26 at 12 15 38 am" src="https://user-images.githubusercontent.com/3952687/82820747-17f7bd80-9ee6-11ea-8854-8b1418a6ccc3.png">
