### ISSUE TITLE
Node groups instead of monads

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3319]
Monads are very complex and difficult to support. They does not use dedicated for creating node groups Blender tools. Last Sorcar updates proves that this tools can be used.

![2020-06-05_08-31-13](https://user-images.githubusercontent.com/28003269/83837233-ee6d3c00-a706-11ea-931e-caa6123c96da.png)

Here is the code of `node group` [node](https://github.com/aachman98/Sorcar/blob/master/nodes/utilities/ScNodeGroup.py).
And here is the code of creating node group [operator](https://github.com/aachman98/Sorcar/blob/master/operators/ScGroupNodes.py). It is nearly all code I guess which is needed for handling node groups.
How had seen the code of monads know that this code is much simpler.

What I don't like in current implementation in Sorcar is that sockets in node group node do not have parameters. They should be plugged to other nodes for managing node group node.

@aachman98 Did not you try to use this class [NodeSocketInterface](https://docs.blender.org/api/current/bpy.types.NodeSocketInterface.html) for creating sockets of node group trees? Probably it could solve the problem.

I Had tried it but faced with Blender crash. Here is [bug report](https://developer.blender.org/T76591) but it has low priority and probably will be fixing for years.

**Comment by zeffii** [comment]
i welcome a simpler implementation of node groups in Sverchok. It _must_ be possible.

**Comment by aachman98** [comment]
> Here is the code of `node group` [node](https://github.com/aachman98/Sorcar/blob/master/nodes/utilities/ScNodeGroup.py).
> And here is the code of creating node group [operator](https://github.com/aachman98/Sorcar/blob/master/operators/ScGroupNodes.py). It is nearly all code I guess which is needed for handling node groups.

The current method is incomplete, and is somewhat unstable (frankly the whole of Sorcar is, at the moment xD). It relies on copying selected nodes to the new group and making the connections with the default `NodeGroupInput` & `NodeGroupOutput` classes. They handle the interface connections internally, and I can't seem to figure out how to add custom classes inherited from `NodeSocketInterface` (see more info below)


> What I don't like in current implementation in Sorcar is that sockets in node group node do not have parameters. They should be plugged to other nodes for managing node group node.

This states another problem with the current setup. If you look in the `ScNodeGroup` class, you'll find that the input data is copied to the node group inputs and the tree is evaluated in isolation. Once complete, it return control back without ever needing to know which node was responsible. So I can't really know which prop to draw on the `ScNodeGroup` node, that is why it requires input data from other nodes such as `Number`


> @aachman98 Did not you try to use this class [NodeSocketInterface](https://docs.blender.org/api/current/bpy.types.NodeSocketInterface.html) for creating sockets of node group trees? Probably it could solve the problem.

Yes, I did try to, but I couldn't figure out where the class was supposed to act. Apparently, it is used internally in Blender when a new input socket is created.
Sorry, this comment could become lengthy, but the following is one major problem I am facing with the API:

---

![Screenshot from 2020-06-06 02-50-34](https://user-images.githubusercontent.com/26548023/83928854-d81abb00-a7ae-11ea-9831-f0f1e7693645.png)
(Just for ref, these are the variables used in console)

---

1. If I create new inputs based on classes `NodeSocketInterface` or its subclasses, nothing happens
![Screenshot from 2020-06-06 02-55-02](https://user-images.githubusercontent.com/26548023/83928992-5d9e6b00-a7af-11ea-9931-60150284ca7f.png)
(See the length remains same in each case)
2. But if I check the type, then bl_rna shows `NodeSocketInterface' for input 'Size'. The interface layout on N-panel also shows the input, but the layout isn't being drawn because of an error.
![Screenshot from 2020-06-06 02-55-44](https://user-images.githubusercontent.com/26548023/83929036-89b9ec00-a7af-11ea-81e4-91dfee81a340.png)
![Screenshot from 2020-06-06 02-57-16](https://user-images.githubusercontent.com/26548023/83929081-c7b71000-a7af-11ea-8f96-e64a38ac38f9.png)
3. Now if I add a new socket based on derivatives of `NodeSocketStandard` class, it creates the new input just fine (also with the correct draw colour and name)
![Screenshot from 2020-06-06 02-56-35](https://user-images.githubusercontent.com/26548023/83929189-24b2c600-a7b0-11ea-9eb6-5c0e81da5efb.png)
4. This time, the type of socket changes accordingly (to `NodeSocketInterfaceFloat` in this case). The other sockets remain same as before though.
![Screenshot from 2020-06-06 02-59-00](https://user-images.githubusercontent.com/26548023/83929249-4f048380-a7b0-11ea-8450-3a3610772657.png)
5. Now the funny thing is, `NodeSocketInterface` is supposed to have draw_color method by default, as listed here: https://docs.blender.org/api/current/bpy.types.NodeSocketInterface.html. But I can't see it in `NodeSocketInterface`, or even in `NodeSocketInterfaceStandard`:
![Screenshot from 2020-06-06 02-59-48](https://user-images.githubusercontent.com/26548023/83929325-95f27900-a7b0-11ea-85b5-cb4d8b77a5fa.png)
![Screenshot from 2020-06-06 03-00-05](https://user-images.githubusercontent.com/26548023/83929330-9a1e9680-a7b0-11ea-9fc7-fbadb9b3db3d.png)
6. Same goes with the socket derived from Sorcar base class. **But**, the socket using Blender's standard sockets DOES have that method:
![Screenshot from 2020-06-06 03-01-28](https://user-images.githubusercontent.com/26548023/83929375-d05c1600-a7b0-11ea-9d15-9eaf0c84cdc9.png)
![Screenshot from 2020-06-06 03-01-50](https://user-images.githubusercontent.com/26548023/83929378-d2be7000-a7b0-11ea-9c97-db179345cf19.png)
7. Another funny thing: If I specifically create a function and assign it to a non-existent `draw_color` method, it starts to display the name and socket colour just fine. (Makes sense though...)
![Screenshot from 2020-06-06 03-17-55](https://user-images.githubusercontent.com/26548023/83929462-13b68480-a7b1-11ea-83c1-5cc1db6eaf78.png)
I can even rename it by double clicking..
![Screenshot from 2020-06-06 03-18-15](https://user-images.githubusercontent.com/26548023/83929485-23ce6400-a7b1-11ea-905a-1da9d398dc11.png)
![Screenshot from 2020-06-06 03-18-39](https://user-images.githubusercontent.com/26548023/83929491-2761eb00-a7b1-11ea-857e-6cdf0b215ef9.png)

---

Sorry, again, for the rant-like comment, but this one problem is getting very annoying. Will see if registering a node socket interface class with similar name pattern (like `ScNodeSocketInterfaceNumber`) would work or not. Maybe the sockets have a property which specifies which interface type to use..

**Comment by Durman** [comment]
Yes, next code looks working, but how to draw properties on a node group node still is the issue.
```Python
class ScNodeSocketInterfaceNumber(bpy.types.NodeSocketInterfaceStandard):
    bl_idname = "ScNodeSocketInterfaceNumber"
    bl_socket_idname = "ScNodeSocketNumber"
    bl_label = "Number"
    color = (0.0, 1.0, 0.0, 1.0)

    default_value: FloatProperty()
    default_type: StringProperty(default="NUMBER")

    def draw_color(self, context):
        return self.color

    def draw(self, context, layout):
        layout.prop(self, 'default_value')
```
![2020-06-06_11-46-28](https://user-images.githubusercontent.com/28003269/83939128-657c0080-a7eb-11ea-8131-0fa4a22022d7.png)

**Comment by aachman98** [comment]
Created a new property of same type as `default_defualt` in the socket class. Now it can be drawn and used to update nodetree. You can also draw `default_value`, but in case of Sorcar, it doesn't have an update function.
![image](https://user-images.githubusercontent.com/26548023/83939505-29e93280-a7fb-11ea-9ecc-cddec3709e18.png)
![image](https://user-images.githubusercontent.com/26548023/83939551-88aeac00-a7fb-11ea-968a-b60132b8feef.png)

One problem with this is that the prop data is fixed. For example, you can't default change value, min/max, soft_min/max, etc unless using standard sockets. Also, the integer & float types have different bpy.props but are bundled as one (`ScNodeSocketNumber` class).

**Comment by Durman** [comment]
The problem is which property should be shown by socket. I guess that in Sorcar as in Sverchok a socket shows property of a node where it was initialized. This property can't be use in case of node groups because several node groups can have different parameters for one socket. 

The solution can be to reconsider using properties. So all default values should be kept in socket classes. But this can increase number of sockets types and in case of Sverchok it is quite significant changes which will touch very many parts of code.

@aachman98 Thanks for help. I will think probably simpler solution exists.

**Comment by zeffii** [comment]
much of the complexity in ScriptNode and Monads came from the inability to dynamically set the min/max of Float and IntProperties.

**Comment by aachman98** [comment]
> The problem is which property should be shown by socket.

I added an extra property in all socket classes which is of the same type as `default_prop`:
![image](https://user-images.githubusercontent.com/26548023/83940093-9fef9880-a7ff-11ea-9a90-b4566419a061.png)

Then, that property can be drawn in the special case of node groups:
![image](https://user-images.githubusercontent.com/26548023/83940073-7e8eac80-a7ff-11ea-9767-a07142b6f0ed.png)

**Comment by aachman98** [comment]
> much of the complexity in ScriptNode and Monads came from the inability to dynamically set the min/max of Float and IntProperties.

Would it help if you simply changed the parent class of all the Sverchok sockets to `ScNodeSocket...`? They already have dynamic min/max functionalities along with default values.

**Comment by Durman** [comment]
In Sverchok we have `String` socket which can be float array, int array, edges array, polygons array and how know what else it can be because it some sort of generic socket type and in this case it is problematic to determine which default property should be used.

**Comment by zeffii** [comment]
using set/get is not ui friendly, we do however use those in A Number and a few other places. This is a problem that could be resolved relatively easily by blender devs.

**Comment by zeffii** [comment]
ideally, if my socket has a limit, i don't want to let the user think that when the slide beyond that value that it will stick. they only realize after letting go of the slider than it jumped back to the value allowed my set/get . i consider it a kludge.         but we could do that. I am not in favour.

**Comment by zeffii** [comment]
but a special socket-class that can mimic all socket types, just for the Group Node, is a possibility i do like. it could ofcourse have dynamic min/max using set/get

**Comment by Durman** [comment]
It impossible because sockets are created automatically by Blender and their type is determined by type of sockets which was connected to group input node.

**Comment by zeffii** [comment]
historic context. https://github.com/nortikin/sverchok/issues/785  :)

**Comment by Durman** [comment]
Reroutes can't be connected.

![reroutes in groups](https://user-images.githubusercontent.com/28003269/83940623-9ada1b80-a7f6-11ea-8f2a-1a1c2afbac7b.gif)

**Comment by aachman98** [comment]
> @zeffii i don't want to let the user think that when they slide beyond that value that it will stick

I get your point. Somehow, standard node sockets manage to set the slider limits, without letting users to go past them. Just tried it on a `NodeSocketFloat` in a material node group:
![image](https://user-images.githubusercontent.com/26548023/83940809-68371f80-a804-11ea-8f16-c7ef81dcf752.png)
![image](https://user-images.githubusercontent.com/26548023/83940938-f90dfb00-a804-11ea-8ee2-82324d97663f.png)
![image](https://user-images.githubusercontent.com/26548023/83940944-ff03dc00-a804-11ea-803c-6f4910d4702d.png)

**Comment by zeffii** [comment]
pynodes is a cool abstraction, but in practice when we try to push the boundaries these issues are all undocumented and therefore a massive time sink.

**Comment by aachman98** [comment]
I already have a half mind to replace all custom sockets in Sorcar with standard sockets ;)
Have you seen this: https://github.com/wonderworks-software/PyFlow ?
Wish they could integrate all of this in Blender someday... It's like visual scripting of UE4, Houdini and Blender combined!

**Comment by zeffii** [comment]
in some respects a lot of non-sense would be solved if we would fully define our own nodetree UI external to Blender maybe `imGUI`.  I have been tempted on several occasions, but lack incentive.

**Comment by Durman** [comment]
It is also interesting (node based) project: https://www.luna-lang.org/

**Comment by zeffii** [comment]
pyflow is really cool :)

**Comment by zeffii** [comment]
also yes!! luna looks spectacular.

**Comment by aachman98** [comment]
Created all the interface classes with default properties. Working for now... 
![Screenshot from 2020-06-06 23-09-04](https://user-images.githubusercontent.com/26548023/83950983-42356d80-a84c-11ea-9981-7dd705e514e5.png)
No problems with nested groups too. Sorcar uses object references (from scene) so there are some cases where I will have to restrict selection, but Sverchok should be fine. Updating the code asap.

Thanks for all the help!

**Comment by Durman** [comment]
With properties it looks much cleaner, my congratulations. 

If to think of it is strange how in Sverchok properties are bound to sockets. 
A property belongs to nodes. But during `sv_get()` method we are calling socket from node and socket calling node back. It looks like that properties should belong to sockets not to nodes. But too much done.

**Comment by aachman98** [comment]
This shouldn't be a problem when creating node groups, as the link class contains from/to_socket as well as from/to_node data members. You can make the node interfaces in such a way that they link to the node rather than the sockets created in the "node group" node. It would look like a bypass where the output sockets would serve no purpose but to call `sv_get()` on the "group output" node. The "group input" node will call the same function on the inputs of the node actually calling the group.

**Comment by aachman98** [comment]
![image](https://user-images.githubusercontent.com/26548023/86542250-a7ef4500-bf31-11ea-9f29-2df6b5c40174.png)
Would probably need to add exception to sockets in case of "Group Input/Output" node. The nodes will get/set data in the same manner (sv_get & sv_set), but the "Node Group" node will need to call the sv_set of the sub-group (custom "Group Input" node, to be precise)
How many types of sockets are there in Sverchok?

**Comment by zeffii** [comment]
@aachman98  this code is present for all nodes. , we could exclude if for nodes of type `Group Input`.

https://github.com/nortikin/sverchok/blob/32b697d3d94c733c94424fc776b017d13f7e6a2d/ui/development.py#L321

**Comment by zeffii** [comment]
```python

def idname_draw(self, context):
    if not displaying_sverchok_nodes(context):
        return
    if self.idname in { ...... }
         return
    ...
```

**Comment by Durman** [comment]
All type of sockets can be found here.
https://github.com/nortikin/sverchok/blob/a0231bd70c5b933fc9467fb2394a693452e06bbe/core/sockets.py#L767-L772

For using node groups sockets should be fixed but this will be minor changes I guess. It looks like that main problem is fixing update system. 

Current implementation could be split into two parts now. First is aware of evaluating main tree and second is responsible for evaluating the monads. I think such splitting should lead to redundant code. I would prefer to see update system which could handle any tree. In this case it would be possible to evaluate all net recursively.

**Comment by Durman** [comment]
We have a chance to got official documentation about creating node groups.
https://developer.blender.org/T80827

**Comment by Durman** [comment]
![2020-10-06_14-42-29](https://user-images.githubusercontent.com/28003269/95191808-53828c80-07e2-11eb-8c8f-30bdced532d0.png)

**Comment by Durman** [comment]
I think group node can show properties of a tree which it possesses.
![2020-10-06_19-52-04](https://user-images.githubusercontent.com/28003269/95226101-986fe880-080d-11eb-973d-2e71c08cbe42.png)

**Comment by Durman** [comment]
![add group property](https://user-images.githubusercontent.com/28003269/95289546-081cbc80-087c-11eb-9a2b-1eb4b17f7c7e.gif)

**Comment by portnov** [comment]
@Durman could you describe, will there be any difference between monads and group nodes from user's perspective? Or is this just a question of how they are implemented?

**Comment by Durman** [comment]
I'm not going implementing loops, split and vectorization features of monads. Also i'm thinking about using viewer nodes inside groups. In the rest they should be the same.

**Comment by Durman** [comment]
There is problem which I still not sure how to solve. The only role of update system at the moment is to call `process` method of outdated nodes in appropriate order. Nodes themselves get information from previous nodes. But the same group trees can be used several times and in this case `process` method of the same node can be called several times and `socket.sv_set` method just will erase preivous result. 

I see two ways of solving the problem. It is possible to modify `sv_get` and `sv_set` methods so they take into account context of processed node. But the problem is that context is known only to update system. Node itself can't know to which group node its belong at the moment of processing. 
Second solution could be that update system should give input data and store output data. Here problem is how to pass this data into process method.

**Comment by portnov** [comment]
As far as I remember, we store contents of outputs in a dictionary, something like `outputs[node_name][output_name]`. We could modify this to store it like `outputs[node_path][output_name]`, where node_path is a path to the node in the tree of node groups, like `Group1/NestedGroup/NodeName`.

**Comment by Durman** [comment]
Probably then a node could has `update_path` (`update_context`?) property which should be changed before calling `process` of the node.

```Python
for node in outdated_nodes:
    node.update_path = base_group_node.node_id  # it looks enough to distinguish the context
    node.update()

Socket:
    def sv_get(socket):
        if socket.node.id_data.bl_idname == 'SvGroupTree'
            return sockets_data_dictionary[socket.other.node.update_path][socket.other.socket_id]
```

**Comment by portnov** [comment]
It is possible too. But I was thinking about calculating the path to the node at the moment we write into `sockets_data_dictionary`. Not sure if it will take much time.

**Comment by Durman** [comment]
How the path can be calculated at that place?

**Comment by portnov** [comment]
don't we have a reference to the node there? Node has a reference to it's tree. Node group tree should have a reference to it's parent, I think...

**Comment by Durman** [comment]
A node tree can have multiple parents (base group nodes) but the tree does not know from which parent, update system is calling a node.

**Comment by vicdoval** [comment]
I think that has been the main unsolved bug of the monads, if you find a way to fix it probably it could also applied to them

**Comment by Durman** [comment]
I think if node groups will work we won't need to have monads.

**Comment by vicdoval** [comment]
I agree, but they will need "vectorize" and "loop" to replace them

**Comment by Durman** [comment]
Goal of group nodes is to hide part of a tree under its interface. So tree could be splitted into simple parts and more complex trees could be builded. Loops is different conception which has nothing in common with node groups.

**Comment by vicdoval** [comment]
So you plan to add some other nodes to handle looping? 
And what about the 'vectorize' i find both features super useful

**Comment by Durman** [comment]
If I will add node groups I would like to delete monads. After that I could make refactoring of json importer again because monads are builded in that way that I had to use recursion during importing. Also after deleting monads refactoring of update system will be doable. No other plans at the moment.

**Comment by portnov** [comment]
We could think of several special "flow control" nodes... for example...
* new socket type — "control". Most usual nodes do not have such sockets by default.
* new node "Loop", with inputs: "Control", "LoopsCount"
* special operator, that allows you to connect other (controlled) node to Control input of Loop node. Like select these two nodes and press a key (or a button in the N panel). This works only if controlled node has enough outputs to be "looped" (for example, if it has Verts/Edges/Faces inputs and Verts/Edges/Faces outputs), otherwise an error is shown. When this key is pressed,
  * matching inputs and outputs of controlled node are automatically hidden
  * new output socket "Control" is automatically added to the controlled node
  * this new "Control" output is connected to Control input of the "Loop" node.
  * In the Loop node, new input and output sockets are created — the same as were hidden from the controlled node.
* then the user connects inputs / outputs of this Loop node to others, like he would work with controlled node.
* `process` method of the Loop node is something like
```python
controlled = self.inputs['Control'].linked_node
# put values from inputs of the Loop node to inputs of controlled node
for i in range(n):
    controlled.process()
    # put values from outputs of controlled node to it's inputs
# put values from outputs of controlled node to inputs of the Loop node
```

**Comment by Durman** [comment]
I was thinking about something like this. In this examples sphere is extruded by 10 random selected masks and masks are creating with taking in account previous extrusions. And keep in mind that it is possible to create nested loops.
![2020-10-22_20-00-34](https://user-images.githubusercontent.com/28003269/96899654-39af9d80-14a2-11eb-84a3-ebf9b95220f1.png)

**Comment by portnov** [comment]
Not quite clear, how Input and Output Loop nodes will know they are paired? And where looping logic itself will live?

**Comment by Durman** [comment]
It is possible to add property input or output nodes with name of another node or they can be connected via special sockets to each other. Logic of evaluation such things should be in update system or at least it should be aware of it and be able to pass responsibility of tree evaluation to those nodes.

**Comment by Durman** [comment]
Node groups `Hello world`

![circular array](https://user-images.githubusercontent.com/28003269/97435260-a1019d80-1939-11eb-9187-59fd94045104.gif)

**Comment by Durman** [comment]
Monads are able to trigger update of several trees I think node groups should do the same.

![update several trees](https://user-images.githubusercontent.com/28003269/97805704-d45d6880-1c68-11eb-9cfd-52623a3be616.gif)

**Comment by Durman** [comment]
Group nodes can become a tool of prototyping new nodes or probably can be presented in nodes menu by themselves. 
`Random color` approach.
![random color2](https://user-images.githubusercontent.com/28003269/98449882-257dc880-2151-11eb-8919-5d9a6c007e3d.gif)

**Comment by Durman** [comment]
As I already was saying current `sv_get` and `sv_set` was not design with taking into account using group nodes (subtrees). It is possible to add context execution information to nodes (make them work properly) but such solution will be really fragile. It can work as temporal solution for now. In future I think those method should leave node object and join update system which possesses actual information how to use them properly. It shoul be really huge change. I'm actually not enthusiastic about fixing 600 nodes.

**Comment by nortikin** [comment]
> As I already was saying current `sv_get` and `sv_set` was not design with taking into account using group nodes (subtrees). It is possible to add context execution information to nodes (make them work properly) but such solution will be really fragile. It can work as temporal solution for now. In future I think those method should leave node object and join update system which possesses actual information how to use them properly. It shoul be really huge change. I'm actually not enthusiastic about fixing 600 nodes.

What exactly it should be?
are there lines of code? Maybe i will have some time in december to go through all nodes. and maybe not olny with your issue.

**Comment by Durman** [comment]
Proper moment to fixing what I'm talking about is somewhere far in the future. First things first. And we should have some plan first for such architectural changes so we could do this once and not return to the issue again. Probably we could create separate issue to discuss who and which changes would like to see.

**Comment by nortikin** [comment]
i'd like to handle messive changes if there are so.
