### ISSUE TITLE
How to clamp a curve (cubic spline) to an axis?

### ISSUE THREAD

**Issue by ricardomatias** [nortikin/sverchok#3340]
![Screenshot from 2020-06-12 11-48-57](https://user-images.githubusercontent.com/8850708/84506051-04f33480-acbf-11ea-9ede-fe34d52c194b.png)

The image shows some curves extruded and solidified, which started out as a closed path curve. I'm just interested in the segment of the curve >= than z == 0. Currently to achieve this, I used the mirror node which allows me to mirror the shape at z == 0 and then I went with logic statements to get rid of the vertices where z < 0. 
This leads to having curve segments which don't have z == 0 vertices, so my question is how to I cut or intersect with the XY plane where z == 0 in order for me to have the first and last vector of the segment at z == 0 position?

Hope that made sense and that it's okay to ask these kind of questions here.

Full geometry:
![Screenshot from 2020-06-12 12-31-45](https://user-images.githubusercontent.com/8850708/84506701-096c1d00-acc0-11ea-9032-b4afdca7ecb5.png)

**Comment by Durman** [comment]
![example](https://user-images.githubusercontent.com/28003269/84514172-9ec8da80-acdb-11ea-8355-48570aab9569.gif)

**Comment by portnov** [comment]
As far as I understand, the problem is that however dense vertices you make, there always will be a gap between the plane and the nearest vertex, at least for most planes.

I have to say I don't know a general solution for this problem, that is good in all cases; however for some cases there may be good-enough solutions.

One approach is just to make as many vertices as possible and hope that they will approach the plane near enough for your task. I think this is what @Durman is trying to show us :)

Another approach is possible in some cases. It may appear you somehow know or calculate values of curve's T parameter, at which it intersects the plane, from your particular setup - in some cases you may know that just by analyzing how do you build your curves. Once you know these T1 and T2  (let's hope your curve intersects the plane in two points exactly), you can then use "curve segment" node or just "evaluate curve" with manually defined set of T values.

In [Sverchok-Extra](https://github.com/portnov/sverchok-extra) there is "intersect curve with plane" node (requires scipy library); it can calculate these T1, T2 values numerically.

![Screenshot_20200612_194950](https://user-images.githubusercontent.com/284644/84515624-2b789600-ace6-11ea-8625-c6e548ff6cab.png)

https://gist.github.com/7ef63d217c28aaf3d49b400c1d6c0f02

(requires sverchok-extra from current git master).

**Comment by portnov** [comment]
Ah, or you can take a totally different approach: just take first and last vertices of your curve and move (project) them to the plane. They then obviously will not be exactly at the curve anymore, but for some cases they may be near enough for your task.

**Comment by vicdoval** [comment]
If you are using the mirror node I understand you are not using a "curve" object at that point, in that case you could use the "Bisect" node to cut the geometry through a plane defined by a Matrix
![image](https://user-images.githubusercontent.com/10011941/84518243-b3ec3c00-acd0-11ea-9d4e-cbbf2e9b3127.png)

**Comment by ricardomatias** [comment]
Thanks for all the replies, I reckon I should have attached some screenshots to make the issue more clear. As @vicdoval suggested, Bisect was the "clamping" I was looking for.

I'll share some screenshots in case someone else comes here with the same issue.

This is the starting point:
![Screenshot from 2020-06-12 21-54-47](https://user-images.githubusercontent.com/8850708/84541713-31777280-acf8-11ea-89bb-0e88fa4e6766.png)

Using a `Symmetric Mesh Node` gives a fair approximation, but also does more than what is needed:
![Screenshot from 2020-06-12 21-54-18](https://user-images.githubusercontent.com/8850708/84541537-e8272300-acf7-11ea-9a29-f25775635322.png)

With Bisect:
	
![Screenshot from 2020-06-12 22-08-43](https://user-images.githubusercontent.com/8850708/84542230-4ef90c00-acf9-11ea-97ba-15e02a63914d.png)
