### ISSUE TITLE
mesh created with BV node, breaks when seen from below

### ISSUE THREAD

**Issue by javismiles** [nortikin/sverchok#3383]
Good day,
I use latest version of Blender, 2.83
I use viewer BMesh to create a mesh from some vertices and faces, etc
when I look at the created mesh from above all looks great, but when I look at it from below it looks broken,
some issues with normals maybe? but this never happened to me using the very same nodes and very same everything in previous versions of blender, any suggestions? thank you :)

**Comment by javismiles** [comment]
solved

**Comment by javismiles** [comment]
Actually it still happens, but only in eevee, it doesnt happen in cycles
only in eevee, any idea?
thank you

**Comment by zeffii** [comment]
any object?  or only a cube ?  give us more to work on.

**Comment by zeffii** [comment]
maybe the object has flipped normals, or inconsistent normals. that's what it sounds like. Use Blender's own debug view to show the normals of the Mesh.  (turn of BMviewer's live mode... )

**Comment by zeffii** [comment]
is it happening only in viewport or also Renders

**Comment by javismiles** [comment]
@zeffii here I am zeffii:
- it happens only on evvee, not on cycles
- it happens both in viewport and also in render, in both
- its an object created from x,y,z points, point cloud, like I always did, ending in your BV node, so the normals should be ok I think, in cycles all looks good
- arbitrary objects, they are arbitrary shapes, x,y,z point clouds, so it can be any shape, happens with all of them

**Comment by javismiles** [comment]
@zeffii 
I showed normals, I dont see much there,
I tried with a normal cube and no problems, all good,
problem happens to me when I generate mesh from point cloud through your BV node and only on eevee but both in viewport and render

**Comment by zeffii** [comment]
there is no bug that i am aware of in BmeshViewer that would cause this - it's a complex node, that really (in the end..ultimately) does a really simple scene operation. ( takes verts/edges/faces and generates the mesh from them, nothing smart there. )

A. If you'd like me to take a look you can do this:
- (temporarily) link the blend here in it's entirety (ie fully dynamic with all data) or 
- link a blend here, just a single frame with Sverchok essentially abstracted away by removing all nodes, and just keep the Objects it created.

or 

B.  You could prove this to yourself that the problem is in your scene by making a super super simple demo .blend , for example:
- with a icosphere for example instead of your object, 
- and do all the same things to that icosphere that you do in your problem .blend
- stick to one frame

There are many things that i don't know about your setup / nodetree / incoming data , that are more likely the problem. I say that because it seems like if there was an issue like that with BMView,  people would have encountered it ages ago. 

also remember to remove any duplicate stale/hidden objects from your scene, like the last time ( https://github.com/nortikin/sverchok/issues/3169#issuecomment-635635111 )

**Comment by zeffii** [comment]
> extraordinary claims demand extraordinary evidence.

**Comment by zeffii** [comment]
also, what happens if you transform the object (flip over Z axis)  ? :)

**Comment by javismiles** [comment]
@zeffii good day Zeffii and thank you for all the comments :) here is my update:

- Problem doesn´t happen with any blender primitive or other object created or imported by itself.

- if I flip the object no the Z axis, the problem reverses. Then it looks good from below, but bad from above. Things then disappear from above and not from below. This means that the problem happens specifically just from one of both sides

- I guess that may suggest that maybe there are problems with the normals. But what I don´t understand is that I have been creating the exact same kind of shapes with the same kind of procedure for 2 years and never had this problem until now. And it only happens in Eevee and not cycles. So something broke somewhere but my code etc has never changed.... and this was not happening before...   so is this a problem with blender? Sverchok? or something else? but if it is the normals generated then why did this never happen before to me when nothing has changed in my pipeline? :) that´s what I don´t understand :)

- I´m going to do more tests and will let u know what I find, and will also see if I can share here something as well

thank you :)

**Comment by zeffii** [comment]
i can't help you until you provide a blend with a massively reduced example of the situation.  so that I too can see. Right now i don't even really have a mental image of the situation.

if you can produce this effect with a 

1. Sverchok Torus 
2. bmview
3. random vertex_colors
4. whatever else like material.

even if you've changed nothing in your setup, that's nullified by the fact that BMViewer also hasn't changed since... 2 months, and that was only to fix a material reference. https://github.com/nortikin/sverchok/blame/master/nodes/viz/viewer_bmesh.py

i am eager to understand what's happening, but realize that i do not have superpowers :)

**Comment by zeffii** [comment]
if you are using a new .blend build and recent sverchok, it might help to delete the bmviewer and recreate it.

**Comment by zeffii** [comment]
> if I flip the object on the Z axis, the problem reverses

so it's not the viewing angle,  it's the mesh.     -- this is why i'm suggesting that you try to recreate the problem with a different mesh (a torus has a nice overal shape for debugging)

**Comment by zeffii** [comment]
> why did this never happen before to me when nothing has changed in my pipeline? :) that´s what I don´t understand :)

i work the other way around, i 
- try to figure out _what's_ happening, 
- then how did it happen ( superficially this is the same question as 'why did it happen..' )
- what can be done
- what do we expect we can achieve  ( total fix ofcourse )

**Comment by javismiles** [comment]
@zeffii yes Im investigating the issue ;)

**Comment by javismiles** [comment]
@zeffii by the way is there a way to delete this cache 
"node Viewer BMesh (socket vertices) not found in socket_data_cache"
sometimes when exchanging data files through the same pipeline, I get this error and it goes away after I repeat the connections a few times I wonder if there is a way to just refresh delete that cache or something

**Comment by javismiles** [comment]
@zeffii and I have good news, I loaded a blender from two weeks ago and the problem doesnt happen there with the same mesh so now Im thinking that it could be some parameters in blender that I may have tweaked in the last 2 weeks, Im trying to compare both files to detect whats the difference

**Comment by javismiles** [comment]
@zeffii things get more interesting, if I move the created shapes that dont look good to the file where the same mesh recreated with sverchok looks good, the imported ones keep looking bad, I now suspect that in the process of creating the bad ones I must have changed some sverchok parameter or something, Im checking

**Comment by zeffii** [comment]
> "node Viewer BMesh (socket vertices) not found in socket_data_cache"

the update system is slightly in flux;  there have been modifications since about 2 months ago..up to 3 few weeks ago i think, will could impact the socket cache.   There are a few ways to update the node tree, `F5` and `Ctrl+F5` ( forced update )

**Comment by javismiles** [comment]
@zeffii I cannot find the difference, all I see is that:
- if I reload a blend from 2 weeks ago and I import through sverchok same data to create same mesh, it looks perfect
- if I import the created meshes from blend created this week to the one of 2 weeks ago, they keep looking bad and broken
- but I cannot detect any difference neither in blend settings neither in sverchok settings
- but the good news is that taking the blend of 2 weeks ago I can reconstruct that I did and now they look good
- would be great to know what happened since a few days ago that made them break, but I cant find it

so we can close this as I found the solution going back to the blend of 2 weeks ago, thank you for the help @zeffii  :)

**Comment by zeffii** [comment]
`¯\_(ツ)_/¯`
