### ISSUE TITLE
Viewer Index+ doesn't work as expected

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#3412]
Something major changed after commit 543d145 ("testing verbose for debug"). 
Lots of my NodeTrees using this node are not working. It looks like the text input changed the format it wants, so I guess an explanation of the new functionality will be a good start.

![ViewerIndex_TextInput](https://user-images.githubusercontent.com/66558924/87987102-bd926c00-cae6-11ea-9585-dd3c5cf5e70b.jpg)

I am worried it also changed the way this node will operate on text, so my question is also - is it possible to replicate the old behavior somehow?
Thanks

**Comment by nortikin** [comment]
https://github.com/nortikin/sverchok/commit/c0c282dd0f9d6ff8683bc00f83441de38a50f236
try this

**Comment by rendetto** [comment]
It works. Thanks!

**Comment by zeffii** [comment]
@rendetto , the new functionality was two fold
- provide a background polygon for the indices ( to enhance contrast )
- provide an object index "prefix" so that it is possible to know which object an index is associated with.

i failed to test the Text stuff, and that's what @nortikin 's patch addresses. The object prefix might be useful for Text input to indexviewer, but it is not essential functionality. so this is ok. 

totally my fault :)

**Comment by rendetto** [comment]
No worries. It looks fine now. Keep up the good work. 
I'm not sure where to post some feature requests about the node - I thought that option for changing the font size, and ability to offset the text will be very useful. Now I just do some cheats for the last one, but if there is a functionality it will be much easier.
Thanks

**Comment by zeffii** [comment]
you must first realize that the node was first designed only to display the indices of verts/edges/faces. But because it only needed a small change to include the ability to display arbitrary text, there was no good reason to break that functionality into a separate node. Sadly when a node becomes more feature rich, it will become more complex to maintain. We have a lot of tolerance for complex nodes, but this node is in danger of crossing a boundary where it might make sense to do a 2dTextViewer for more control over text.

# feature requests
I think we're pretty clear about being in favour of discussing new features. A vast majority of requests are within the realm of "possible to implement" and "yes, that;s a good idea". I think offsetting text falls into both of those. On top of that it really depends on who is available to code it, and who wants to. That's where requests go stale sometimes. 

-----

the text is drawn in 2D, and the offsetting would happen in `screenspace` (ie the 3d world is translated into 2d, 3d locations of a vertexl have a 2d location of a pixel in the screen)
    - do we implement a socket to accept a list of offsets, so each point/text can be offset by a unique 2d value 
       - how that will look will depend on the viewing angle of the geometry. This may or may not matter.
   - how does baking text respond so such offsets ( i think we implemented baking text using the default font?.. )

**Comment by rendetto** [comment]
I hope a font size control could be easier to implement.

I guess an offset in screen space is a lot harder than my cheat which works only as a horizontal offset, but is enough to move the label so it doesn't obscure the labeled object. 
What I do now is adding additional white space after or before the text, using "text in+" node to overcome the way index+ node splits the input.
The label stays always in the same position to the object in space no matter how you orbit around.
It's a viable option if this is easier to implement it using just one float input (choosing negative or positive numbers to control the direction of the offset)  
The cheat I do works only for static text, but not for dynamically changing inputs, so it's just a halfway solution.

![test_offset](https://user-images.githubusercontent.com/66558924/88047726-bd33b880-cb5a-11ea-8958-94d524e6836d.jpg)

**Comment by zeffii** [comment]
i see, your solution is acceptable, but does show the limitations of the ad-hoc nature of Text display in IndexViewer.

a `2D Text Viewer` would have the following features
- [ ] pick text size , individually per "string" if needed
- [ ] pick text anchor point ( N, NW, W....etc..) , per "string" if needed
- [ ] pick 2d offset, individually or per string.
- [ ] add beauty rendering features like
    - dropshadow
    - change font

- [ ] drop edges/faces/matrix input, user can use other nodes to transform the 3d locations of the desired text.

**Comment by zeffii** [comment]
it would be similar to Typography Viewer, which you might want to check out too, it offers anchor and offset already, but the drawback is that it creates real Typography (Curve/Font) objects in Blender Scene and they do not face the "camera"

**Comment by rendetto** [comment]
I checked the Typography Viewer but as you said it creates Blender objects and I can't imagine how heavy it could be labeling, for example, all vertices in a complex mesh. 

On the other side this 2D Text Viewer you are describing sounds really cool.

**Comment by rendetto** [comment]
...I found another case that didn't work for me after the changes. Should I open new issue about that or just continue posting here?.. 

I'm trying here to plot some T values along the length of a curve. It was fine before, but now throws an error.

![t_values](https://user-images.githubusercontent.com/66558924/88330702-73062f00-cd34-11ea-89d6-4bd85d200472.jpg)

**Comment by zeffii** [comment]
new issues is fine, i've opened one here https://github.com/nortikin/sverchok/issues/3417

**Comment by rendetto** [comment]
Thanks

**Comment by zeffii** [comment]
@nortikin   i also don't know where `text_item[0]` came from. in just appeared in code - out of the blue:)
