### ISSUE TITLE
GEOMDL Surface Issue

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#3521]
When using "Curve on Surface" and "Iso U/V Curve" nodes over GEOMDL patch the output seems odd when the calculations include negative domain values. 
![GeomdlSurface](https://user-images.githubusercontent.com/66558924/92413326-2d70ba80-f158-11ea-91ff-afeabe2cc7fc.jpg)

Using the same setup over a generic "Plane Surface" the results seem fine.
![GenericPlane](https://user-images.githubusercontent.com/66558924/92413330-33ff3200-f158-11ea-9cbf-d10639a30bd3.jpg)

Here's the setup I'm using so you can also test it:
[GEOMDL_Surface_Issue.zip](https://github.com/nortikin/sverchok/files/5184740/GEOMDL_Surface_Issue.zip)

Thanks

**Comment by portnov** [comment]
Well, while trying to evaluate surfaces outside of their domain, there are different options, each of which may seem weird in different situations; Especially with such complex mathematical thing as Nurbs. If you try "Sverchok" implementation, you will see different behaviour, which is weird too :)
Since lately, there is "FreeCAD" implementation available for "build nurbs curve / surface" nodes (available only when you have FreeCAD libraries installed). In this particular case, this implementation works the same way as with simple "Plane" surface.
But, in general, I would advise not to try to evaluate the surface (or curve) outside of it's domain. It may work with some implementations, but usually implementations do not guarantee any specific behaviour in such cases - it can change with new version of FreeCAD / Geomdl / Sverchok, so better do not rely on it.

**Comment by rendetto** [comment]
I understand. Now I tried the FreeCAD implementation and the output looks most intuitive for me. 
I felt that the GEOMDL implementation could have a bug, because it does behave ok for positive values outside T>1.0, 
![GEOMDL_CoS_positiveT](https://user-images.githubusercontent.com/66558924/93013990-cd45a280-f5b5-11ea-82c4-2c52930159d7.jpg)

but for T<0.0 resulting data is thrown above 1.0 instead of being below 0.0(which doesn't seem very intuitive for me). 
![GEOMDL_CoS_negativeT](https://user-images.githubusercontent.com/66558924/93014041-4fce6200-f5b6-11ea-9903-7a52373bc896.jpg)

I thought that it could be just a wrong sign somewhere, but I don't have the expertize :)

**Comment by portnov** [comment]
Well, I can't say if this is really a bug. In Nurbs maths, when you go outside of bounds, mathematically you have division by zero, but different implementations use some "quirks" to work around it. It can be that these "quirks" do not work as intended in Geomdl, or it can be that no one just never thought about how it should be in this implementation — "say thank you if it does not crash" :)
By the way, you can try switch "curve type" toggle from NURBS to BSpline (BSpline is the same as NURBS, but without weights, so mathematically it does not involve division). It may help. Or may not :)

**Comment by rendetto** [comment]
It didn't :), but I guess I can stick to the FreeCAD implementation when I need the particular output it does. 
As a side effect I found that BSpline surface is not working for some reason: #3536 

Thanks

**Comment by rendetto** [comment]
Those issues are now fixed in the latest GEOMDL `5.x-dev` branch.
