### ISSUE TITLE
Nearest Point on Curve issue for Approximated Curve

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#3529]
I tried the "Nearest Point on Curve" node on an approximated NURBS curve, and I got an error:
"...geomdl.exceptions.GeomdlException: GEOMDL ERROR: Parameters should be between 0 and 1"

If I reparametrize the input curve to ..say (0.0, 0.99999) or (0.00001, 1.0) or (0.0, 1.00001), or anything that doesn't include one of the domain boundaries the node does not throw the error. 

Here's the file I used for testing:
[Nearest_Point_on_(approximated)Curve_Issue.zip](https://github.com/nortikin/sverchok/files/5209453/Nearest_Point_on_.approximated.Curve_Issue.zip)

Thanks

**Comment by portnov** [comment]
Does it work with "Sverchok" implementation?

**Comment by rendetto** [comment]
The "Approximate NURBS" node doesn't offer such implementation, only GEOMDL.

**Comment by rendetto** [comment]
...or you mean the "Approximate Bezier Curve", as the native Sverchok implementation for approximating points? If so, it doesn't give such error, but the results are somewhat different.

Thanks

**Comment by portnov** [comment]
Ah, sorry, stupid me :)

**Comment by rendetto** [comment]
No worries :)

**Comment by portnov** [comment]
Well, it appears there is not much I can do: I use two external libraries, scipy and geomdl, and only can tweak their parameters.
In this particular case, when I use "Bounded" solver instead of "Brent", it works. But I saw cases when "Bounded" method did not work. So, I'm going to add a parameter to the node, so that the user can select the solver which works in each particular case.

**Comment by rendetto** [comment]
Thanks a lot. Exposing those "method" parameters is of a great use. Not only for this particular node but for all the nodes I tested so far.
