### ISSUE TITLE
show icons description in sv Preferences

### ISSUE THREAD

**Issue by ppaawweeuu** [nortikin/sverchok#3600]
## Old description

There is in SV Preferences checkbox with old description. Works fine, just old description.
I think there should be "shift+a" menu. In b3d 2.8 "ctrl+space" if for maximize workspace.

![show_icons](https://user-images.githubusercontent.com/61344631/94703596-4c213600-033f-11eb-9aa2-fc6280bcf284.JPG)

Windows 7, SV 0.6.0.0

**Comment by onerawartist** [comment]
In 2.90.1 it shows in ''shift+a'' menu and i really like it, cuz it helps looking for the icons instead of reading , specially for some one like me ''one month old in sverchok''. but i noticed a small delay in the ''shift+a'' menu.
 It shows the text but takes a second to start loading the icons, i thought it was just my laptop but i noticed it is much slower than the ''shift+a'' menu in the 3D viewport. Its like loading the icons each time i use it

**Comment by onerawartist** [comment]
Ps: im always updating using this way , i update everytime i open blender '' daily '' ^^
