### ISSUE TITLE
We need to update how Sverchok look to the blender community !

### ISSUE THREAD

**Issue by onerawartist** [nortikin/sverchok#3688]
i see everyone excited about geometry nodes coming to blender in the future but i see no one talking about how sverchok can already do all that with more than 600 nodes !
 i feel like all your work is being ignored by the community , i'm an architect and im very new to sverchok and i wish i was better so i can make videos about it, the documentation is almost not existing.
this is all i could find:

---
http://nortikin.github.io/sverchok/#Lessons
https://poneill.co/thelab/%D1%81%D0%B2%D0%B5%D1%80%D1%87%D0%BE%D0%BA/
https://www.youtube.com/channel/UC7ED1eB6DET3fPOWxcDJ1lw 
http://nikitron.cc.ua/sverch/html/main.html#

---

and most of what i could find was in 2015 and earlier 

i tried to contact all the blender youtubers to give sverchok a try, but all of them replied that they are not good at math "even someone i saw brag about studying coding and math at the university lol" so you guys are the only answer to this problem , people are afraid of sverchok because the lack of tutorials. and i promise i will start making tutorials once i learn enough to be able to teach others

Sverchok is amazing and i feel sad when i google "parametric design" and all i see is photos and videos of grasshopper and no sverchok at all

**Comment by onerawartist** [comment]
![Annotation 2020-11-04 034726](https://user-images.githubusercontent.com/71472224/98063712-f6194400-1e50-11eb-87e3-6707785cba2d.jpg)

**Comment by zeffii** [comment]
I think you describe the core of the problem accurately, a lot of people are afraid of math on a conscious level, this is a failure in their education, not our fault. Of the total thing we call math, only a small subset of concepts need fundamental internalization to use sverchok for interesting results. Everything else in math builds on a few core principles. KhanAcademy has detailed lessons about Vectors and Matrices, if people can get through those then they already posses enough information to grasp the concept that underpin Sverchok and the likes. They will also have shown a level of commitment to their intellectual progress. 

Remember the old saying "you can lead a horse to water, but you can't make it drink".

if you have question about efficient ways to do something for a planned video, feel free to ask here. We have an open culture of support, and often you'll get a variety of answers Each approach will have pros and cons: usually a compromise between 

- speed
- complexity
- flexibility

finally i want to say that i completely empathize with the emotion that drove you to open this issue in the first place. Sverchok has achieved many "firsts" in blender node tree ecosystem, but has not been recognized to any great extent - but if we had done any of this for large scale recognition the project wouldn't have survived much. I can't speak for everyone in team-sverchok, but primarily we do this because we need it, and occasionally users show us that they've understood the software by producing impressive content - this provides secondary enjoyment for us.

Writing good tutorials takes time, which is an expensive commodity. Most nodes have documentation, some extensive, others not so much.

**Comment by zeffii** [comment]
The twittersphere ( `#sverchok #b3d ` ) has some excellent examples of what users/contributors are achieving, despite the not-super-comprehensive documentation. Especially (in no particular order, and this is not an exhaustive list)

- https://twitter.com/erindale_xyz
- https://twitter.com/portnov9
- https://twitter.com/bluefox_3d
- https://twitter.com/VicDoval
- https://twitter.com/msurguy
- https://twitter.com/3drwny
- https://twitter.com/SoluSerg
- https://twitter.com/ricardomatiaspt
- https://twitter.com/asahidari
- https://twitter.com/BennyGovaerts
- https://twitter.com/ChamerlatL

we also curated a few galleries with screenshots + zips, because being able to load a node tree on your own machine and adjust variables will provide more insight in a shorter space of time, than a full tutorial about that node tree. People are generally well able to detect patterns in information, this includes abstract complicated stuff like nodetrees/sverchok.

- [gallery one](https://github.com/nortikin/sverchok/issues/1342)
- [gallery two](https://github.com/nortikin/sverchok/issues/2357)
- [gallery three](https://github.com/nortikin/sverchok/issues/2666)
- [gallery four](https://github.com/nortikin/sverchok/issues/2814)

(well the original intention was to provide a screenshot and a nodetree download... but not everyone does that)

**Comment by onerawartist** [comment]
@zeffii thank you so much for everything, and yeah i will be asking more and more questions when i find problems making something, 
The thing is i thought asking you guys for help each time felt selfish and youtube tutorials seems like less selfish because its for the entire community ^^ 
I guess i will be making tutorials as soon as possible. And that will be my contribution to the sverchok community

**Comment by Moult** [comment]
I've started retweeting and following those accounts :) Every bit counts I guess!

**Comment by zeffii** [comment]
@onerawartist , we embrace beginner questions here. Sometimes questions are hard to formulate but easy to answer, conversely other times questions are easy to ask but difficult to provide solutions for, usually due to the following:
- a gap in our node list (_may_ or _may not_ require domain specific knowledge to code such a node/script)
- it is not strictly sverchok territory
- you are encountering an unreported bug, and a node should be behaving as expected but isn't.

> And that will be my contribution to the sverchok community

these kinds of contributions are appreciated, it will divide the workload. The more you use Sverchok, the more untraveled paths you'll take, and the more unusual stuff you'll see. The more you'll start to get a feel for things that are bugs and things that you straight up aren't using as designed - but only time and persistence gets you there, and i've not seen many users pass those hurdles.  But the ones that have  blow my mind :)

**Comment by hitrpr** [comment]
Just personal view after some practice with different node systems (vanilla, Sorcar, AN+, Sverchok, Mathnodes…)

Sverchok looks much more complex and difficuilt for user. 
For example. I want to add geometry input and output.

There is no such nodes as «Object input» or «mesh input».
And all what new user can find is Bmesh in:
![57384001](https://user-images.githubusercontent.com/21099918/98233014-77ff8f00-1f6f-11eb-9e1f-ec70a5482287.png)
What is is? How to use it? Is is it?

Objects in? Okay. I need one. Okay, I selected. Should i subdivide only edges or faces too? How to do it?
If I selected two, how to split their data?
![57401310](https://user-images.githubusercontent.com/21099918/98233864-a762cb80-1f70-11eb-99f3-2acd7edb5f27.png)
How to output? How to subdivide same fasion as Subsurf do?


![57441941](https://user-images.githubusercontent.com/21099918/98240001-d893c980-1f79-11eb-9467-177b3577c0b9.png)
![57454015](https://user-images.githubusercontent.com/21099918/98239994-d6316f80-1f79-11eb-8c90-7d0fb1c3e49c.png)

In the Sorcar most of options just hidden by default, and do not confuse user.
In Sverchok there is no way to hide em even if i want (Ctrl H is not the same)
![57462320](https://user-images.githubusercontent.com/21099918/98240456-7d160b80-1f7a-11eb-8a12-ad1de2da0874.png)

So interface and names are complex and counter-intuitive. Videos and tutorials will not help much. UI redesign will.
I call it «programmer`s design», it can be described as «It works, I know how it works, and I don`t care if it looks bad or if somebody don`t see as I see».

**Comment by zeffii** [comment]
@hitrpr   why are you using sverchok?

**Comment by Durman** [comment]
@hitrpr It is true that Sverchok is not ideal. The problem is that Sverchok has loads of code and architectural things can't be fixed easily. But even slow it's getting better. If you have some ideas for sverchok you can open new issue where we could discuss thier.

**Comment by onerawartist** [comment]
@hitrpr you have to remember that sverchok is open source and free. And is getting better each day thanks to the amazing developers working on it. And our job as end users is to use sverchok and report anything we don't like, one thing at the time.
But don't forget that we must learn how it works and meet the developers half way ^^
.
Last time i checked, grasshopper is not a walk in the park too

**Comment by harisreedhar** [comment]
Hi, What about having a mesh structure in sverchok? Many modifiers and other nodes in sverchok uses combination of vertices, edges, faces. I think a mesh structure which packs vertices, edges, faces would be nice. which also reduces number of sockets of node and looks clean.

**Comment by Durman** [comment]
@harisreedhar Yes, there was such attempts but I did not find enough time to finish them. The problem was that I did not find solution how effectively work with old and new nodes (with mesh sockets) togather because it will be to hard to reright them all at once so they would use only mesh sockets or probably not all nodes can be even rerighten in this way. In Houdini for example solution is to use different more abstract node editor which is so to speak wrapper over low level node editor which deal with vertex elements.

Pevious attemts:
#2767 #2927

This module could be base for next attempt
https://github.com/nortikin/sverchok/blob/master/utils/meshes.py

**Comment by harisreedhar** [comment]
@Durman Good to hear it was a plan. Yeah compatibility with old nodes will be an issue. Rewriting nodes gradually will be good i think.

**Comment by nortikin** [comment]
made youtube channel great again.
beginning translations.

**Comment by portnov** [comment]
> ![Annotation 2020-11-04 034726](https://user-images.githubusercontent.com/71472224/98063712-f6194400-1e50-11eb-87e3-6707785cba2d.jpg)

To be honest, most of pictures that google shows by such keywords are almost trivial in sverchok...

**Comment by hitrpr** [comment]
> @hitrpr you have to remember that sverchok is open source and free. 
I remember.
And I want to remind, that making tutorials for too complex UI isn`t as effective as making UI better.

@zeffii I use it rarely, when I need something complex, when sverchok`s complexity is suitable.
And I prefer to not touch it, when I need just arrays, grids and booleans.

ATM there is no handy solution for node-modifiers in Blender.
Sorcar — lot of bugs, crashes, abandoned.
AN — about motion
SV — very complex even with simpliest tasks.

As I see, SV do not have «mesh» channel, only separate vertices/edges/polys
It triples routes.
So I hope, mesh socket and socket hiding will appear once. It can make node trees more neat.

**Comment by onerawartist** [comment]
i watched the blender today live and i feel like they are reinventing the wheel lol 
so i commented sverchok everywhere ^^ and created this:

https://blenderartists.org/t/geometry-and-modifiers-nodes-were-already-in-blender-the-free-addon-sverchok/1264436
and this:
https://blender.community/c/today/tzgbbc/

**Comment by Durman** [comment]
Sverchok target first of all is architectural design but not to procedural modeling in general. There is difference.

**Comment by enzyme69** [comment]
I tested Geometry Node for Blender 2.92a experimental. Pretty natural to use and reminiscent of SV and Sorcar and AN. It's like maybe ideally SV node tree could behave like Geometry Node too as Modifier so the geo can go in and out and processed at will.

What would be great is if the Node Tool in Blender works like in top level (object mode?), with direct interactive interface. A bit like Maya or Houdini, when selecting component poly face and extrude, we suddenly get nodes in the background, and so on. Maybe it will take years until it become like that.

But anyhow, let see how Geometry Node grow. 

Durman made a good point about SV being like grasshopper for parametric architecture design, not procedural modeling. I often get those two mixed. All I know is that for a lot of things, SV nodes help me to do the impossible without coding.

I have not read the whole thread here, I might read it again at later time.. Thanks onerawartist.

**Comment by enzyme69** [comment]
And yes, years ago, I did talk about Blender SOuP to Peter Shipkov :) 
https://soup-dev.websitetoolbox.com/post/blender-soup-5394333?pid=1321547227

I don't know it might be another future addon. SV is a bit like SOuP (Maya), which is like SOP (Houdini). But SV is also very different.

**Comment by portnov** [comment]
I've created a wiki page with links to existing resources: https://github.com/nortikin/sverchok/wiki/Resources. Feel free to enhance it.

**Comment by nortikin** [comment]
Blender today - nodes geometry is not everything nodes, but nodified modifier.
Remind you, Lukas Tone said years ago - if blender wants nodes in everything the blender core need to be rewriten completely.
So nodes get to object creation and deps graph and so on.
For now we have fragmental nodification.
Lets wait for revolutionary refactorer come to Blender team and handle this giant job.

**Comment by hitrpr** [comment]
> 
> 
> i watched the blender today live and i feel like they are reinventing the wheel lol
> so i commented sverchok everywhere ^^ and created this:
> 
> https://blenderartists.org/t/geometry-and-modifiers-nodes-were-already-in-blender-the-free-addon-sverchok/1264436
> and this:
> https://blender.community/c/today/tzgbbc/

Sometimes if you need lighter and thinner wheel with new materials, you should reinvent it ;)

**Comment by paulofalcao** [comment]
I follow Sverchok for a very long time, apparently is now an explosion in node based procedural in 3D, probably because of the things people here able to do using the displacement node in nodevember, which is great, the more, the better! I agree Sverchok needs more attention

**Comment by onerawartist** [comment]
@hitrpr good point

**Comment by DuncanLithgow** [comment]
@nortikin I've added the YouTube channel to OSArch Free Software Playlist https://www.youtube.com/channel/UCoP6n8DdDajAM8YYDdFpQMQ/playlists

@zeffii OSArchOrg on Twitter now follows those account so will be sharing more of that content.

@portnov I've linked to your resources list on https://wiki.osarch.org/index.php?title=Sverchok#External_Resources

How about starting a hashtag #SverchokInsideBlender #SverchokInsideFreeCAD and so on?

Please, if you share something relevant on Twitter consider adding #osarch so I find it.

**Comment by DuncanLithgow** [comment]
okay, so I get impatient, I've added a reply to a bunch of tweets that look like they are Sverchok running in Blender https://twitter.com/search?q=%23SverchokInsideBlender

If anyone else thinks this is a good idea feel free to use the hashtag #SverchokInsideBlender

**Comment by onerawartist** [comment]
What we need is for people like erindale to do proper tutorials like the ones about grasshopper, 20 mnts videos with a precise goal '' making this or that'' using parametric key words in the title. Because all we can find is blender sushi doing random things in 2000 videos and other videos that are an hour long just chatting about random stuff, and that doesn't help any beginner.
We need short videos with precise goals ,i kept asking them for months with no answer, now i switched to rhino grasshopper , while waiting for geometry nodes to evolve. 
I feel sorry for all the hard work than the sverchok team has done thats going to b forgotten

**Comment by portnov** [comment]
As you probably can imagine, developers are good at writing code, not tutorials :)
Also, developers find fun in writing code (and not tutorials), and I think I will not be too wrong if I say that for most of Sverchok developers this fun is what makes them/us to continue the development.

So, if anyone is feeling himself good at making tutorials, and willing to do them, everyone is welcome! :)

**Comment by onerawartist** [comment]
We are at '' who's first : the egg or the chicken '' lol i want to do tutorials but can't find enough tutorials to learn sverchok in the first place.
Sverchok has been here for years. And only the devs master it. Obviously there's a problem somewhere.

**Comment by portnov** [comment]
@onerawartist I can suggest looking at Grasshopper's tutorials for starters. Some things are implemented differently in Sverchok, but many ideas are the same. You can watch Grasshopper tutorials and try to do the same in Sverchok. Some things will require more nodes, or some non-trivial jumping, but still...
"that's why we call it beta: it's betta than nothing" :)

**Comment by onerawartist** [comment]
i am, and im making so much improvement, and yeah, learning grasshopper made understanding sverchok easier

**Comment by DuncanLithgow** [comment]
@onerawartist may I suggest you team up with someone who is willing to show you show Sverchok work 30 minutes at a time over a video connection. Make a series of videos that way. Just agree on what the first couple should be about and take if from there. Maybe find a cool clip you've seen and ask them if they'd like to show you in weekly 30 minute steps how it's done for a beginner. It's much more fun showing something to someone you know is curious than making tutorial videos. Eventually someone who wants to make tutorials will, but it's a lot of work.

**Comment by onerawartist** [comment]
Im finishing a udemy class on Rhino and grasshopper is next, after that i will try to start a youtube channel about architecture concepts workflow and i will definitely be in contact with the sverchok team.
Sverchok is a great tool and it will always b part of my workflow

**Comment by brunoperdigao** [comment]
@onerawartist I totally agree with your thoughts. One of the things that kept me away from Sverchok is the lack of architectural content. The thing that got me started was Erindale's tutorial about the basics of Sverchok. Since I learned the basics I started to try some other things. As @portnov suggested, I started to watch Grasshopper tutorials and tried to replicate in Sverchok. I don't have any experience in Grasshopper and I already have had some success (at least for my expectations).
As I progress, I want to create some learning materials, maybe as blog posts. I guess we could start looking at some Grasshopper tutorials that are popular and create the same thing in Sverchok. We can create a list of goals like "How to make a parametric brick wall" or "How to create a twisted tower", that kind of stuff. Another thing that I am excited with is to combine parametric design with Ladybug, since we already have some initial implementation in Sverchok. Maybe we can help each other on this task

**Comment by onerawartist** [comment]
@brunoperdigao im in for sure , add my on instagram or facebook to stay in touch.
I go with the same name on insta and '' iheb berriche'' on facebook

**Comment by DuncanLithgow** [comment]
Here are are two specific use cases from architectural facade projects if someone needs inspiration for a tutorial or two. 

* Sheet metal perforation sizes based on a raster image
* Sun shading shutters with angles forming patterns.

Clumsy explanations, but I'm guessing you already know this type of thing. Those are two very basic and eye candy things architects can use Sverchok for on projects.

**Comment by nortikin** [comment]
>     * Sheet metal perforation sizes based on a raster image

[mushroom.blend.zip](https://github.com/nortikin/sverchok/files/5791727/mushroom.blend.zip)
![изображение](https://user-images.githubusercontent.com/5783432/104107551-0aa10f00-52ce-11eb-9b49-845dbc369685.png)

**Comment by nortikin** [comment]
![изображение](https://user-images.githubusercontent.com/5783432/104107625-c82c0200-52ce-11eb-986c-a8fbe7cbc607.png)
[reciprocal2.blend.zip](https://github.com/nortikin/sverchok/files/5791739/reciprocal2.blend.zip)

**Comment by nortikin** [comment]
![изображение](https://user-images.githubusercontent.com/5783432/104107648-e85bc100-52ce-11eb-9042-90cbfdce1400.png)
[orientation_matrix.blend.zip](https://github.com/nortikin/sverchok/files/5791748/orientation_matrix.blend.zip)

**Comment by nortikin** [comment]
![изображение](https://user-images.githubusercontent.com/5783432/104107666-117c5180-52cf-11eb-88ac-a6652b3ae27f.png)
[naming.blend.zip](https://github.com/nortikin/sverchok/files/5791753/naming.blend.zip)

**Comment by nortikin** [comment]
![изображение](https://user-images.githubusercontent.com/5783432/104107688-5dc79180-52cf-11eb-9c7e-428c150b086f.png)
[brick_wall1.blend.zip](https://github.com/nortikin/sverchok/files/5791759/brick_wall1.blend.zip)

**Comment by nortikin** [comment]
![изображение](https://user-images.githubusercontent.com/5783432/104107712-7afc6000-52cf-11eb-8784-f28815b39f85.png)
[lesson.blend.zip](https://github.com/nortikin/sverchok/files/5791760/lesson.blend.zip)
https://youtu.be/mDynylmjPFo

**Comment by Durman** [comment]
Well this is something like a tutorial but without words. Usage of the `adaptive polygons` node is shown.
https://youtu.be/BYgLlVJWN9c
![subnail](https://user-images.githubusercontent.com/28003269/104220373-d4dc6180-5458-11eb-9e91-932eb78897f4.jpg)
