### ISSUE TITLE
FreeCAD libraries distribution kit for Windows?

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#3780]
Currently the link to "Py3.7-win" from Dependencies wiki page leads to 404. It seems that developers have discontinued support of python3.7 for Windows? Maybe standard distribution kit of FreeCAD will suffice? Maybe "Py3.8" will do?
I don't have Windows constantly running, so I'm not sure how to install these libraries the best way. So this is the question for anyone around who is running Windows and is willing to experiment with FreeCAD libraries installation. @nortikin maybe you?

Also I found https://anaconda.org/conda-forge/freecad , there seem to be some distribution kit for Python 3.7. But I didn't try this either.

**Comment by rendetto** [comment]
The last FreeCAD win build I'm using is from here:
https://github.com/FreeCAD/FreeCAD/releases/tag/0.19_pre , specifically FreeCAD_0.19.23323-Win-Conda_vc14.x-x86_64.7z 

It uses Python3.8 and it's working with latest Sverchok master without problems.

Maybe this info is irrelevant to the topic since I'm not sure what libraries you are referring to. What you mean by "FreeCAD libraries installation"? Are those described here - https://wiki.freecadweb.org/Third_Party_Libraries ?

I'm not too much into this stuff, so please excuse me if I'm talking nonsense :)

**Comment by portnov** [comment]
I mean FreeCAD.dll, Part.dll and others, that Sverchok actually uses.

**Comment by rendetto** [comment]
Got it. Unfortunately I never explored such option. 
A quick search doesn't do much. I got (https://github.com/FreeCAD/FreeCAD-library) which apparently is not the thing.

Also there is the freecad-cli (https://wiki.freecadweb.org/FreeCAD_Docker_CLI_mode), but it looks complicated and it's targeted towards linux and mac.

The FreeCADLibs package (here: https://github.com/FreeCAD/FreeCAD/releases/tag/0.19_pre) contains only collection of dependencies if we need to compile FreeCAD

Is there a way to use FreeCAD just as a library under linux?

**Comment by maxim1967** [comment]
it can leave it as it is and change the broken link to freecad_0. 19. 23323-win-conda_vc14. x-x86_64.7z. I checked with this library everything works.

**Comment by portnov** [comment]
Ok, I've updated the link.
What is the directory with FreeCAD.dll for this distribution? Currently the wiki page refers to `...\conda-0.18.3\bin`, is this actual?

**Comment by maxim1967** [comment]
Yes, I downloaded from the previous link, and installed it.

**Comment by maxim1967** [comment]
Oops ... Sverchok doesn't work with freecad_0. 19. 23323-win-conda_vc14. x-x86_64.7z only works with conda-0.18.3 just found out today.

**Comment by rendetto** [comment]
FreeCAD_0. 19. 23323-Win-Conda_vc14. x-x86_64.7z worked for my own pc with the latest SV.

Now I'm testing another win pc and none of the FreeCAD win distributions worked.
I tryed everything from 0.17 up to latest FreeCAD_0.19.23463-Win-Conda_vc14.x-x86_64.7z
Even those listed at https://anaconda.org/conda-forge/freecad which are py37 specific.
I also tested official blender90 and the new blender91 - but there's no difference.

Is it possible that we need to set specific env PATH variable so SV can see FreeCAD?

**Comment by portnov** [comment]
For

**Comment by vicdoval** [comment]
I have added the file I downloaded from the old link to the assets of the [last Sverchok release](https://github.com/nortikin/sverchok/releases/tag/vstable3) I don't know if its the right place but maybe is the best one for the moment
https://github.com/nortikin/sverchok/releases/download/vstable3/FreeCad.0.18.3.Win.Py37.7z

**Comment by rendetto** [comment]
@portnov I checked the .pth file every time I tested different FreeCAD package.  Each time the path was the correct one - corresponding to the current package I'm testing, but no luck. (of course most of those aren't py37)

@vicdoval Thanks! At last one distribution that works fine here! 

I'm starting to doubth that on my own pc all those distributions really worked every time I was updating FreeCAD.  I'll check that in a couple of days and report, because the last time I checked the distribution was py38 and had no problems. Now I'm confused, but I'm sure that the path was set exactly to the py38 package.

@portnov is there any chance that, no matter the .pth is set correctly, Sverchok reads some different location of FreeCAD?  

Thanks

**Comment by portnov** [comment]
> is there any chance that, no matter the .pth is set correctly, Sverchok reads some different location of FreeCAD?

I don't think so. You can check this by executing

```
import sys
print(sys.path)
```
from Blender's python console. The output must contain the path to FreeCad libraries (among other paths).

**Comment by rendetto** [comment]
Thanks I'll try that.

**Comment by rendetto** [comment]
I've checked with the commands above on my own pc, and yes, it appears that I was using an old FreeCAD version. So none of the latest(or earlier) FreeCAD win packages I have work - also none of those uses Python3.7

The version that worked for me is FreeCAD_0.19.19697_x64_Conda_Py3QT5-WinVS2015.7z (and it uses Python3.7)
I'm not sure how big files I can upload here, and I have to convert it to ZIP, but if you need something more recent than 0.18.3, just let me know and I'll try.

**Comment by vicdoval** [comment]
@rendetto I would like to try that version but github comments wont allow such a big file

**Comment by rendetto** [comment]
Here it is:

https://drive.google.com/file/d/1FTMbeCIRPuX1XZAaqzZ8MMh9JhSrfPBq/view?usp=sharing

I'm not sure how long I could share this link, so if you find it useful, please upload it in the sverchok repository like you did for 
FreeCad.0.18.3.Win.Py37.7z

Thanks

**Comment by nortikin** [comment]
@rendetto 
please, share also this link https://yadi.sk/d/NhCrTKi3nIgTXA uploaded. It will be long term

**Comment by dballesg** [comment]
Hi, 

Following the wrong advice from here:  https://github.com/nortikin/sverchok/wiki/Dependencies
    Install FreeCAD py3lib
        You have to use FreeCAD of version 0.18 or newer **(nightly builds of 0.19 work fine)**.

I downloaded and uncompressed FreeCAD_0.19.24267-Win-Conda_vc14.x-x86_64.7z from https://www.freecadweb.org/

And it's impossible to make it work with sverchok in Blender 2.83.8LTS, 2.92 or my own compiled 2.93.0 Alpha. 

Please correct the documentation and dont mislead people into think that those verisions work.

Thanks in advance.
