### ISSUE TITLE
Sverchok slows down Blender startup

### ISSUE THREAD

**Issue by gerroon** [nortikin/sverchok#3806]
Hi

It seems like Sverchok does some checks while loading, and those steps seems to be the slowest startup checks (compared to other addons) during Blender booting up. I am wondering if there is a way to speed up and disable those fully. 

This might not be as noticeable if you boot from an SSD but it definetely adds some seconds from a reguler HDD.

I do not have additional debugs  or developer nodes. My logging level is set to information.

thanks

**Comment by Durman** [comment]
Probably registration of nearly 600 nodes takes time. I think someone have to make profiling of loading event to see more exact situation.

**Comment by portnov** [comment]
@gerroon Please check: do you use presets? If so, how many of them do you have?

**Comment by gerroon** [comment]
@portnov 

I am using whatever stock Sverchok is, I do not have addiitonasl presets of my own or ones I downloaded.

**Comment by portnov** [comment]
Hmm. Please try the following:
1. Update Sverchok from current master.
2. Run Blender from command line as:
```
$ blender -- --profile-sverchok-startup
```
(for linux and macos), or
```
C:\...> blender.exe -- profile-sverchok-startup
```
(for windows). Then just close Blender.
3. In the directory from which you were running Blender, you should see two files, named `sverchok_profile.txt` and `sverchok_profile.prof`. Please send them here (you can pack two files as zip and attach it to the comment in this issue).

**Comment by gerroon** [comment]
[sv.zip](https://github.com/nortikin/sverchok/files/5773309/sv.zip)

**Comment by portnov** [comment]
@gerroon I've tried to speed up something. Please update from git master and check if startup gets any faster. If not, please attach prof and txt files again.

**Comment by gerroon** [comment]
Thanks for the update. Feels faster for sure. I will keep testing it.

**Comment by onerawartist** [comment]
i was having the same problem and keeping an eye on the updates, it does feel faster now, and i thought i share with you guys when the lag is happening:



CAD Transform 0.91.0 : ready
C:\Users\pc\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\tissue-0-3-48\utils_pip.py:31: RuntimeWarning: Use 'sys.executable' instead of 'binary_path_python'!
  PYPATH = bpy.app.binary_path_python
Registered MACHIN3tools 0.5.0 with 0 tools, 4 pie menus and 0 context menus
sv: import settings
PyMCubes package is not available. PyMCubes-based implementation of Marching Cubes will not be available
2021-01-06 18:10:45,534     INFO dependencies.py 107 PyMCubes package is not available. PyMCubes-based implementation of Marching Cubes will not be available
FreeCAD 0.18, Libs: 0.18R16131 (Git)
Dependencies available: pip, scipy, geomdl, scikit-image, circlify, FreeCAD, Cython.
2021-01-06 18:10:46,247     INFO dependencies.py 144 Dependencies available: pip, scipy, geomdl, scikit-image, circlify, FreeCAD, Cython.
C:\Users\pc\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\sverchok-master\settings.py:16: RuntimeWarning: Use 'sys.executable' instead of 'binary_path_python'!
  PYPATH = bpy.app.binary_path_python
sv: import all modules
C:\Users\pc\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\sverchok-master\settings.py:16: RuntimeWarning: Use 'sys.executable' instead of 'binary_path_python'!
  PYPATH = bpy.app.binary_path_python

-----------------
it takes few seconds in this line each time i open blender

**Comment by gerroon** [comment]
I also getting new error with this update


```
Exception in module unregister(): 'C:\\Users\\USER\\AppData\\Roaming\\Blender Foundation\\Blender\\2.91\\scripts\\addons\\sverchok-master\\__init__.py'
Traceback (most recent call last):
  File "C:\BLENDER_RELEASE\2.91\scripts\modules\addon_utils.py", line 434, in disable
    mod.unregister()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\sverchok-master\__init__.py", line 97, in unregister
    sv_registration_utils.unregister_all(imported_modules + node_list)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\sverchok-master\core\__init__.py", line 32, in sv_unregister_modules
    m.unregister()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\sverchok-master\nodes\spatial\homogenous_vector_field.py", line 129, in unregister
    bpy.utils.unregister_class(SvHomogenousVectorField)
RuntimeError: unregister_class(...):, missing bl_rna attribute from 'RNAMetaPropGroup' instance (may not be registered)



```

**Comment by portnov** [comment]
@gerroon please provide full console output since blender startup till it's termination.

**Comment by onerawartist** [comment]
@portnov no problem with my start up ?

**Comment by portnov** [comment]
@onerawartist I do not see any error messages there. There is warning about bpy.app.python_binary_path_python, but that's harmless.
