### ISSUE TITLE
List Level Fails to import

### ISSUE THREAD

**Issue by vicdoval** [nortikin/sverchok#3856]
The problem with this node is that it creates the properties dynamically, so when the node is created by the importer it does not have the properties so the can not be set.

Maybe it could be solved with load_from_json function but @Durman suggested to avoid this solution

**Comment by Durman** [comment]
I would not say that the node generate the properties. It would be more precisely to say it copies the properties, may be. Anyway import system can copy / generate properties in the same way. So the problem is not in generating properties. 

During importing, node is being created with all properties and with required values but I suspect that during linking it's reseting properties to default values.

By the way in the node code I found solution of a problem which I had been trying to solve several days ago without success. It's lucky I have a look at the code.
