### ISSUE TITLE
How to execute in sverchok bpy.ops Related operations

### ISSUE THREAD

**Issue by vktcl** [nortikin/sverchok#3865]
For example, set the origin for an object

Specific operation: bpy.ops.object .origin_ set(type='ORIGIN_ GEOMETRY', center='MEDIAN')

Is there a node to execute bpy.ops Related operations

**Comment by zeffii** [comment]
`bpy.ops` are usually triggered by the user in the UI with an object / objects selected. Not all `ops` will make sense to perform from a nodetree, in fact very few standard `bpy.ops` are used internally in sverchok at all. There are almost always lowerlevel alternatives (which are by their nature more flexible too)

Inside any given `bpy.ops.*` there are often multiple handlings going on and also sometimes side-effects which may cause sverchok node tree to retrigger in an infinite loop. 

I think for the bpy.ops you are referring to specifically you want to do something like

![image](https://user-images.githubusercontent.com/619340/106383036-a8ff2c80-63c3-11eb-8df1-e6357710d46c.png)

this would always place the origin of the object at the mean of its geometry.

**Comment by vktcl** [comment]
@zeffii Your example does solve the problem of placing the origin. What I want to do is as follows:

1 set the origin of many objects generated by mesh viewer as their respective geometric centers

2 select an object to add rigid body attributes

3 use Set property node to set rigid body properties

Use (copy from activity) to add the set rigid body attributes to other objects

In this way, I don't have to set the geometric center and adjust the rigid body properties repeatedly

1 and 3 I know how to do, but 2 and 4 need to bpy.ops operation

**Comment by zeffii** [comment]
unfortunately I know nothing about rigging / rigid bodies, nor the bpy api for these things. Generally bpy api offers lower level (non bpy.ops) alternatives when you aren't using the UI (like using elaborate scripts ..or a node tree ). Having lower level control would let you add frame based logic and tests weather or not you want to perform certain parts of the code.

else you end using a `script node` or an `exec node` , or `prop set node`.
```python
obj = ...

bpy.context.view_layer.objects.active = obj    # how to set active
obj.select_set()                               # how to set selected

```
and relying on getting the active / selected object correct prior to letting the control flow run any of the `bpy.ops` , which can be an unpleasant experience :)

**Comment by zeffii** [comment]
i haven't been much help : /

**Comment by vktcl** [comment]
concrete bpy.ops ... operations can be learned from the info window to perform such accurate operations bpy.ops Whether the sverchok node of the operation can be implemented.

I found that Get Property / Set Property is access and operation bpy.data and bpy.context Relevant data

**Comment by zeffii** [comment]
I'll try to explain this, and emphasize where you will want to focus your efforts. 

Blender defines many `bpy.ops`, which wrap several steps into one callable operation, called an "Operator". Operators are generally triggered by the UI, and indeed these are the "functions" you see being called from the Info window. And, yes these Operators can indeed be called from a script, but here's where you may encounter some unexpected complexity.  

### invalid context

Many scripters have stumbled upon "invalid context" errors in their Python scripts because the Operators that they trigger aren't finding enough information about the state of Blender/Scene at the time of calling. If you look at the documentation you'll see many Operators don't even have keyword arguments in which you could pass the required information as part of the function call.

Briefly look at these posts on [blender.stackexchange](https://blender.stackexchange.com/search?q=invalid+context) (really ..do it) , they'll show you a persistent theme and solution. Mostly the answers are 

 - don't use bpy.ops, there are more direct ways to achieve this desired result
 - or you must override the context, and then it should work as expected 

Here's [one example of @Durman showing how to override a context](https://github.com/nortikin/sverchok/issues/2221) in Sverchok because he wants to use a standard `bpy.ops`, 

### what I think you should do

1. figure out if it is possible to do the things you want using lower level bpy api calls, ie... not using bpy.ops.
2. or.. develop a script that does perform everything you want using bpy.ops and any context override, 

Then when you can achieve these things separarate from Sverchok, ( yes... stepping away from the nodetree while you develop the script) - this separates the *required code* from *how to execute it in sverchok*.  If you know what code needs be written in a world where the is no sverchok, then we can show you how to implement that inside sverchok.

**Comment by zeffii** [comment]
to be clear, your options are (From highly flexible to least flexible)
- ScriptNode (lite)
- Exec Node 
- Object ID Set

[`Script node`](https://github.com/nortikin/sverchok/blob/master/docs/nodes/generator/script1_lite.rst): write the code for the node in the TextEditor, and you can even update the code from the TextEditor.
[`ExecNode`](https://github.com/nortikin/sverchok/issues/1056): has a few inputs predefined, can load code from the TextEditor or you can type directly into the node's UI.
[`Object ID Set`](https://github.com/nortikin/sverchok/blob/master/docs/nodes/object_nodes/get_asset_properties_mk2.rst): allows you to access properties of a object that was passed into the node.

All of these nodes have documentation in some form or another, or their development threads are still readable.

**Comment by vktcl** [comment]
Through your answers, I have a new understanding of how to solve my problems

I'll consider using your initial suggestion, which is more convenient



There is a new problem. Can the SN node limit the number of updates? In this way, I can prevent unnecessary duplicate updates through restrictions

**Comment by zeffii** [comment]
yes, when the code is executed it will probably trigger a Blender event that in turn will cause the node tree to be updated, and this will indeed cause some infinite loop of updates (unless you can test whether to execute the code before the "working" code is run )
```python
    ng = self.id_data
    with ng.throttle_update():
        try:
            bpy.ops.*
        except:
            pass
```
and here the try/except is just a suggestion, you can test if code needs to be executed rather than running the code without tests

**Comment by zeffii** [comment]
feel free to reopen/continue this thread at any time.

**Comment by vktcl** [comment]
After adding some knowledge of python, I started to try my first code, and then I ran into a new problem

Objective: call blender Boolean operation to cut an object with multiple surfaces (of course, I know that I can use solid to achieve this)

Implementation logic: use face [O] to cut the object to get two objects, use face [1] to cut the new object, and then use face [2] to cut the new object, repeat this operation until face is used up.

My code:
for a in face :
    for b in objects:
        some ops...
        objects.append(new.object)
# My code is wrong, how can I use the code to implement this logic

**Comment by vktcl** [comment]
@zeffii

**Comment by zeffii** [comment]
there's two different problems here

1. figure out how to translate into code that which you can imagine in your head
2. apply this code within the context of the Sverchok node tree.

`2` is harder (..i'd even say impossible) when `1` is not not achieved yet. To get a better understanding of `1` get a good working knowledge of Python, this is separate from Sverchok - blender.stackexchange.com is a good resource for asking about how to script bpy stuff not just bpy.ops. What you'll find is that the people willing to help you will want you to 
- specify first in broad strokes what you wish to achieve
- show what you've tried
- show what parts the code you do understand, and where you think the problems are.

many more people will read those blender python questions than read this Sverchok issue tracker.

**Comment by vktcl** [comment]
OK, thank you very much for your advice.
