### ISSUE TITLE
Can I get a set of point locations on a curve via input x, y, or z?

### ISSUE THREAD

**Issue by hwy1992129** [nortikin/sverchok#3883]
Like the curve I draw in the image...
![image](https://user-images.githubusercontent.com/70329303/107134055-95206280-68bc-11eb-8734-5e4379d553b0.png)
I believe there is a parametric function for the curve in scripts.... Can I input x and get y, z?

**Comment by summereasy** [comment]
Is this what you expected?

![iShot2021-02-07 14 47 27](https://user-images.githubusercontent.com/51897649/107139112-8f299080-6953-11eb-8a59-b9601e4feec0.jpg)

**Comment by Durman** [comment]
Most likely you are looking of something like this.

![2021-02-07_10-59-59](https://user-images.githubusercontent.com/28003269/107139314-bb351980-6933-11eb-825e-ad3941f8a5d9.png)

[curve.zip](https://github.com/nortikin/sverchok/files/5938414/curve.zip)

**Comment by hwy1992129** [comment]
@summereasy Yes. That is what I want, but what if I want more planes. 100 to 1000...? Do I need to script my own node? Or is there any combo for the nodes available?

**Comment by summereasy** [comment]
> @summereasy Yes. That is what I want, but what if I want more planes. 100 to 1000...? Do I need to script my own node? Or is there any combo for the nodes available?

Sure, you can do it. But to find those "intersection" points on a curve do have a lot of ways. Since I don't know what you might consider doing next... I really cannot give you the best suggestion for this.

Let's keep it simple, if you just want to keep using the CURVE-PLANE intersection method, all you need to do is find a way to define those planes, mathematically. For example, you can create a list of YZ-Planes use various x positions and consistent Normal Directions.

![iShot2021-02-08 18 19 31](https://user-images.githubusercontent.com/51897649/107206793-7ba52500-6a3a-11eb-8977-df6bd03fc534.jpg)

### But there are more other ways in other situations

For example, the more accurate way of finding a Point on a Curve I think refers to Curve Frame Node.
**Curve frame Node** gives you not only the location but a hell of other information on that specific point (like directions Rotations etc.) through a matrix.

For example, you have a parametric curve in which x is always at 0, y is t, and z is some function of t. Say $z = 3 * cos(t) * e ** -(.1*t)$
If you want to get any point refers to a specific y, since y = t, you just plug your y values into t, and it will work for you. No paining intersection stuff what so ever. But like I said, since I don't know what's your next move, I cannot give out the best solution. 
![iShot2021-02-08 18 37 46](https://user-images.githubusercontent.com/51897649/107208603-cb84eb80-6a3c-11eb-9c86-7d591d44ad90.jpg)

If you want to dig more, please take a look at the docs.

**Comment by hwy1992129** [comment]
@summereasy Thank you. That is what I want! I don't know how to create a list as input...
