### ISSUE TITLE
BPY DATA node is invalid in node group.

### ISSUE THREAD

**Issue by vktcl** [nortikin/sverchok#3902]
BPY DATA node is invalid in node group.There was no reaction
Can this problem be fixed？

**Comment by Durman** [comment]
Could you share your file?

**Comment by vktcl** [comment]
> 你能分享你的文件吗？


[P.zip](https://github.com/nortikin/sverchok/files/5977001/P.zip)

**Comment by Durman** [comment]
There are two implementation of the node groups. In menu they have names `monad` and `group`. The Monad implementation is going to be deprecated one day and I would not suggest to use it. However neither of this implementation support nodes from `bpy data` category. I will have a look probably it is time to support at least part of them in `Groups`. It should not be too difficult to fix.
![2021-02-14_09-15-16](https://user-images.githubusercontent.com/28003269/107869224-2b4c1e00-6ea5-11eb-86f8-ac0ff70e70ea.png)

**Comment by zeffii** [comment]
@vktcl   the Alpha node category has a version of the Set/Get node that will work in both current 2.92  / 2.93 , at least it will give you access to those kinds of properties from outside of the Monad or Group Node system. The Set/Get nodes are better at general purpose "hot wiring" of most bpy API stuff, when there aren't dedicated nodes to do the job.

and the eval line would be something like `bpy.data.objects['Cube'].location[0]` , not `bpy.context.object` (or active object) because that could be pointing to a different object than you intend sometimes.

As you've noticed already you can use the more specialized `Object Remote` control with a matrix input, you could insert something like this
![image](https://user-images.githubusercontent.com/619340/111918910-9e8a1680-8a87-11eb-8c52-801a6f6c766e.png)

but to get the `Monad` to _update_, it expects at least one of the output sockets to be connected. I don't think the `Group Node` system has this limitation.

**Comment by Durman** [comment]
> but to get the Monad to update, it expects at least one of the output sockets to be connected. I don't think the Group Node system has this limitation.

Actually it has the same limitation for now. Because supporting viewer nodes required extra work in their code. However it's possible to use Stethoscope node. This is only node which is supported inside node groups.

**Comment by zeffii** [comment]
kind of off topic, but still tangiential: 

I considered Monad similar to functions, and didn't want them to have side-effects. True `input->operation->output`, allowing GLViewers/ObjectViewers inside a Monad would break that abstraction. Also with the Loop mode in Monad it's not clear how predictable those Viewers would be or how useful. The stethoscope however makes sense because the user can still view data inside the Monad, which is hidden again once you are outside of the Monad.

For the `Group Node` implementation, which doesn't have a loop mode this may not be an issue, but I think it does complicate the global Hide/unhide stuff. It also becomes more unlike the shader node tree which only has one True output into blender, i think...

**Comment by Durman** [comment]
My idea is to put generation of Blender objects out of viewer nodes. So they could get the objects via parameters of the `process` method. But in this case update system, of node group particularly, should be able to generate them and distribute among viewer nodes. To say it differently viewer nodes also should become functions without side effects.
