### ISSUE TITLE
SV interfering with Animation Nodes Shift+A functionality

### ISSUE THREAD

**Issue by unity2k** [nortikin/sverchok#3951]
## Problem statement

SV interfering with Animation Nodes Shift+A functionality. With SV enabled I cannot bring up the list of nodes in Animation Nodes, all I get is an empty search function. If I disable Sverchok, Animation Nodes works as expected.

## Steps to reproduce

1. Install and enable Animation Nodes on 2.93 nightly
2. Install and enable Sverchok
3. Start a new Node session with Animation Nodes and press Shift+A to select a node.

## Expected result

My expectation was to see the long list of Nodes that are usually present. This was working with VStable4 but I can't go back as it was enabled from 2.92 and was able to remain enabled but on 2.93 I cannot enable that version.

## Actual result

I did not get the list of Nodes until I disabled Sverchok

## Sverchok version

vstable5 from release page on Blender 2.93 daily release

**Comment by zeffii** [comment]
i think this is related to the patch that replaces that whole menu, https://github.com/nortikin/sverchok/commit/4ff9c71fea9aeb0f395d72bc2763906a4ab17892

you can locally uncomment that line, for now.

https://github.com/nortikin/sverchok/blob/4ff9c71fea9aeb0f395d72bc2763906a4ab17892/__init__.py#L95

**Comment by zeffii** [comment]
this part of the Blender Custom Nodes API is under developed.

We resorted to a monkey patch to enhance the standard Add menu in sverchok, I wasn't aware that this would affect other custom node systems, especially because Sverchok now has it's own View. (and no longer under the Nodes view as was the case in 2.79 )

@vicdoval  : /

**Comment by zeffii** [comment]
One possibility might be that we populate the whole Header panel of the Sverchok node tree ourselves, but I think this breaks a reusability principle.

**Comment by vicdoval** [comment]
Does it happen the same with 2.92?

**Comment by unity2k** [comment]
> Does it happen the same with 2.92?

vStable4 works with 2.92 but vStable5 produces the same problem as with 2.93. On 2.93 I cannot enable vStable4 as it throws errors.

**Comment by zeffii** [comment]
@unity2k  if you update i've temporarily removed the monkey patch, until we think of some other solution.

**Comment by zeffii** [comment]
closing this, because the problem lies elsewhere, and is a Blender design problem until someone else shows me it isn't. 

But because i changed this back to the original "sucky" menu behaviour, i'm sure we'll get notfied about that too.  Just use Shift+A instead of the header-menu.

Maybe we can make a configuration option in settings, to Auto patch the menu or not... if we do it one way one group will speak up, if we do it another then the other group will speak up.  Ultimately we can't satisfy both without a change to the pynode API, or we trash the existing Sverchok Header menu (with all the auto populated stuff) and completely repopulate it with out own menus from scratch. -- i for one don't like that idea.
