### ISSUE TITLE
( Adaptive Polygons ) node with ( Instances ) instead of real objects

### ISSUE THREAD

**Issue by AnasFX** [nortikin/sverchok#3964]
## Problem statement

Is it possible that the ( Adaptive Polygons ) node could use ( Instances ) instead of real objects.

## Expected result

a lot of instances, with low poly count in the scene

**Comment by Durman** [comment]
I'm not sure that it is possible. Because the node deforms points of each duplicated mesh. At least it could be done by the node.

There is `instancer` node which can create object instances. It requires matrixes where to instance new objects. `Origins` node can help to get matrixes from mesh elements.

**Comment by enzyme69** [comment]
Seems like future task of Geometry Nodes 😀 don't know maybe we can "hack" it somewhat with matrix being sent to Geometry Nodes.

I am not sure exactly how Adaptive works, is it deforming like in Lattice kind of way or more like Matrix transform.

**Comment by Durman** [comment]
I don't see how this can be achieved with matrixes.

![2021-03-11_08-32-54](https://user-images.githubusercontent.com/28003269/110736044-67746380-8244-11eb-9dc0-be6d6dd9acdf.png)
