### ISSUE TITLE
Error : ValueError: faces.new(verts): face already exists

### ISSUE THREAD

**Issue by AnasFX** [nortikin/sverchok#3989]
## Problem statement

When I try to get center points of faces with the Component Analyzer node I get the error :

File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\utils\sv_bmesh_utils.py", line 89, in bmesh_from_pydata
    add_face(tuple(bm_verts[i] for i in face))
ValueError: faces.new(verts): face already exists

## Steps to reproduce

1.  use Object In node to get a object
2. Use Component Analyzer to get the mid points ( or you can use Origins Node, same problem )

## Sverchok version

Latest Version Update 0.6.0.0

**Comment by Durman** [comment]
The error means that your mesh has two polygons with the same vertices. It does not supported by this node. What could be done is to make the message more explicit.

Also it's possible to write a script to detect and remove such faces.

**Comment by zeffii** [comment]
The analyzers use a custom `"pydata to bmesh"` function to convert `pydata` (sverchok) to a `bmesh` (blender) representation. This `"pydata_to_bmesh"` function does a blind conversion of the data (extra checks means slowing down the node., and we avoid them intentionally). The `bmesh` mesh structure doesn't allow duplicate faces. Under nominal operation you wouldn't want duplicate faces in a mesh ( i'm not sure there is even a good reason to have duplicate faces.. ) and if it isn't intentional you can as @durman mentions use a script to de-duplicate faces.

Here's an ExecNode script that allows us to make duplicate faces in the mesh, by duplicating every 2nd face. This way you can see what happens even with a simple Cube.

```python

for faces in V1:
    out.append([])
    new_faces = out[-1]
    for idx, face in enumerate(faces):
        if idx % 2 == 0:
                    new_faces.append(face)
        new_faces.append(face)

```
![image](https://user-images.githubusercontent.com/619340/112656041-479e8b80-8e51-11eb-8e0d-edd5ecd3db1b.png)

The kind of code i would use to `make_unique_faces` util function, 

```python
from sverchok.utils.sv_mesh_utils import get_unique_faces
for faces in V1:
    out.append(get_unique_faces(faces))
```


![image](https://user-images.githubusercontent.com/619340/112657210-79fcb880-8e52-11eb-9388-38322446acb8.png)

**Comment by zeffii** [comment]
@AnasFX  there's a new ["Mesh Clean"](https://github.com/nortikin/sverchok/pull/4012) node now, that can take care of meshes with redundant topologic information (like duplicated faces, or unused verts..and a lot more). In the event that you have such an input mesh, pass it through such a node first, before hitting other nodes.
