### ISSUE TITLE
Text in+ not recognizing strings in CSV file

### ISSUE THREAD

**Issue by wassimj** [nortikin/sverchok#4016]
## Problem statement

When trying to import a CSV file, the Text in+ node does not recognize string field. It only recognizes number.
## Steps to reproduce

1. Create a CSV file with a mix of numbers and strings
2. Load the CSV file with the CSV option into Sverchok Text in+ node
3. Connect the output to a Stethoscope node to inspect.

## Expected result

I expected to see the strings that are stored in the CSV file

## Actual result

An empty list

## Sverchok version

0.6.0.0
<img width="1317" alt="SverchokBug" src="https://user-images.githubusercontent.com/6302909/113478443-bfd40500-9480-11eb-848e-a60f64577dcc.PNG">

**Comment by zeffii** [comment]
there's an extra option in the N panel of that node "Force Input"

![image](https://user-images.githubusercontent.com/619340/113479267-5529c600-948e-11eb-89b5-b723926db5e0.png)

**Comment by zeffii** [comment]
i thought i added this to the documentation?

![image](https://user-images.githubusercontent.com/619340/113479376-07fa2400-948f-11eb-95fd-5721b45fd841.png)

**Comment by zeffii** [comment]
there's three kinds of csv lines to read
- all numbers
- all strings
- mixed bag of strings and numbers

thus:

- the `default mode` will handle all numbers, and be fast
- the `force_input mode` will handle the mixed bag and be slightly slower because it has to check the input, the slowdown is probably minute if this is done properly (and it's allowed to assume consistency over the rows) , I don't think this mode is optimal at the moment. And if it was, it would definitely be candidate for the new default mode, maybe even replace the current `default mode`. 
- the `extended mode` reads everything as a string, and puts control in the hand of the user to cast the data correctly.
