### ISSUE TITLE
Incompatibility of FreeCAD with Blender 2.93

### ISSUE THREAD

**Issue by maxim1967** [nortikin/sverchok#4056]
## Problem statement

Blender 2.93 uses Python 3.9, and FreeCAD uses Python 3.7 or 3.8 So when switching to Blender 2.93, FreeCAD cannot be installed, they are not compatible. Alas, a large number of nodes will not work in Blender 2.93. Perhaps there is some solution to this problem?

**Comment by zeffii** [comment]
and what about this? https://github.com/nortikin/sverchok/issues/4005

**Comment by maxim1967** [comment]
Well, there it is written that later versions are again on Python 3.8 . And where to get FreeCAD_weekly-builds-24612-Win-Conda_vc14. x-x86_x64.7z it is not specified there so the problem is 100% relevant%

**Comment by maxim1967** [comment]
Who has: FreeCAD_weekly-builds-24612-Win-Conda_vc14.x-x86_x64. 7z share with the people

**Comment by rendetto** [comment]
I uploaded the packages you are searching for here:
https://we.tl/t-uh8YZSCGHp

But... I didn't felt comfortable with this build(**and post bugs**) since is seems highly experimental. 
Thus I stopped using it and reverted back to Bl2.92 and FC0.19 build19697.

Couldn't we ask the FreeCAD developers for Blender2.93 compatible builds?
