### ISSUE TITLE
updating Sverchok beyond 0.6.0

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#4103]
what's it going to take? : )

is there a github action that can automatically commit a change to the version number?  people are under a serious misapprehension that this 0.6.0 value is in any way meaningful at this point.

**Comment by vicdoval** [comment]
i suggest to change the number manually before making the release or after, i would go to something like Year-Incremental num
so the next one would be
`21.3` or `21.1` to start with something easy

**Comment by zeffii** [comment]
ok, for the next release maybe it could be `0.6.21.5`

**Comment by zeffii** [comment]
or maybe you really man simply ` 21.5`

**Comment by vicdoval** [comment]
I meant simply `21.5`

**Comment by portnov** [comment]
We could just extract tag name from git log. If current revision is not tagged, then output git revision hash — this will mean unreleased version, from master branch, for example.

**Comment by zeffii** [comment]
i think a version number that encodes the date takes my preference. it would be the least arbitrary of all options. but then ``YY.M.D``

**Comment by Durman** [comment]
It looks like that next release should have another version because I consider removing monads as significant changes which we would probably like to mark in the Sverchok's history.

**Comment by zeffii** [comment]
agreed

**Comment by zeffii** [comment]
i've seen other repositories do action-driven releases.

so i think we would do something like
- action
   - action-bot obtains 30 latest commit messages
       - update release text area from commit messages
   - action-bot commits change/update to bl_info['version']
       - ( we must convene on an acceptable convention for versioning )
   - action-bot pushes release.

**Comment by Durman** [comment]
There is [Semantic Versioning](https://semver.org/) and it looks that it's what is already used in Sverchok.

According to the article the sence of versions is to mark changes in API. From this point of view putting date into a version does not have too match sence because it does not say anything about API changes. There may be significant changes or may not. It only says that one version is after another.

For Sverchok, API is its nodes. If a tree had one output and after new version another it means that it's incompatible API changes. In history of Sverchok such changes was done only once. If we had 1.0.0+ version before adopting Sverhok for Blender 2.8 now we would have Sverchok 2.0.0+.

I think we should stick with current version symantec and should create 1.0.0 version (probably here #4164 ?). It would means that there won't be any incompatible changes in the future without changes Sverchok version. Most likely every new release should increments second number (`1.1.0`) because new nodes are being added quite rapidly. If between releases only bugfixes were made then third number should be incremented (`1.0.1`). If to made releases every month then second increment can grow pretty fast. But is it a problem? We can see that Blender itself has (had?) quite big second increment (2.**93**). Or we can make releases more rare.

About release notes. It looks like that now we have a lot of useless, from user point of view, information in the notes.
<details> 
  <summary>example</summary>  

![2021-07-05_19-23-18](https://user-images.githubusercontent.com/28003269/124493382-a23b7200-ddc6-11eb-8194-31519c8335b9.png)


</details>

I think significant information is about new nodes, node bugfixes, new UI elements etc. but not about internal stuff like changes in the utils package, changes in Sverchok node tree API etc.
I think we can achieve this properly labeling PRs.

**Comment by portnov** [comment]
Or, we can work out an agreement about commit message format. For example,
```
[+] new node introduced: ...
```

```
[*] node logic was changed: ...
```

```
[-] previously deprecated functionality was removed: ...
```

```
[#] Bug was fixed: ...
```

and modify script so that it would pick up only commits marked with such signs.

Just a suggestion. We can use another format if we like.

**Comment by Durman** [comment]
> and modify script so that it would pick up only commits marked with such signs. Any commit without mark is considered to be technical and not worth disturbing the user.

And the table of a release should have different categories for different commits then.

If it would be possible to generate list of PRs instead of list of commits release information would be more readable I think. Also it looks like it's simpler to add a label to a PR then stick with the commit convention. Labels of PRs can be always changed unlike commit messages.

**Comment by Durman** [comment]
I found this link in the GitHub documentation - https://github.com/semantic-release/semantic-release
Fully automated version management and package publishing

**Comment by kevinwright** [comment]
I'm using a different strategy in https://github.com/nortikin/sverchok/issues/4415

Instead of going by git hash, I'm going on the build pipeline number, which is guaranteed to always increase, and means that a release only gets published if all tests pass. It could just as easily be timestamped though.

That's fine for anyone who always wants to use the bleeding edge, but if a release ever comes out that breaks compatibility for files saved using an older version, then we're going to **need** semantic versioning for stable releases.
