### ISSUE TITLE
Cannot deconstruct IsoUVCurve from GEOMDL Surface

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#4174]
"Deconstruct Curve" is not working on IsoUV Curve created from GEOMDL Surface. The other implementations are working though.
![Deconstruct_IsoUVCurve_GeomdlSurface](https://user-images.githubusercontent.com/66558924/122639925-608fa380-d105-11eb-80b8-febb08324429.jpg)
I'm uploading the test file:
[Deconstruct_IsoUVCurve_From_GEOMDL_Surface.zip](https://github.com/nortikin/sverchok/files/6680529/Deconstruct_IsoUVCurve_From_GEOMDL_Surface.zip)

**Comment by portnov** [comment]
Calculating "iso U/V curves" of Geomdl surfaces as Nurbs curves is not (yet) supported for rational surfaces. If you check with stethoscope, you will see that "Iso curve" in your case outputs not a Nurbs curve object, but `<<Geomdl NURBS (degree=3x3, pts=4x4) surface> at U = 0.23000001907348633 curve>` — a generic Curve object. In this particular case, it is enough to switch "Build Nurbs surface" node to "B-Spline" mode, so that it would generate non-rational surface.

**Comment by rendetto** [comment]
OK I think I got it. Am I understanding correctly that this calculation is not yet implemented in GEOMDL library itself so that's not a Sverchok issue?

**Comment by portnov** [comment]
Geomdl library does not have public API for such calculation. Sverchok theoretically could do it by itself, but that would mean more code and more knowledge of Geomdl internals in Sverchok.

**Comment by rendetto** [comment]
Thank you. In that case that's not a huge problem since you did it for Sverchok Native and FreeCAD surfaces. I can convert the input surface implementation easily thanks to the Deconstruct Surface node and then extract a rational IsoCurve if I need it. 

I'm not sure If I have to close the issue since it's not considered a bug and it's not even a Sverchok problem. Please feel free to close this topic if you find it unnecessary to stay open.
