### ISSUE TITLE
Sverchok crashes Blender on fast input changes

### ISSUE THREAD

**Issue by wassimj** [nortikin/sverchok#4179]
When I slide inputs fast, sverchok crashes all of Blender

Windows fatal exception: access violation

Current thread 0x00006f14 (most recent call first):
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\ui\bgl_callback_3dview.py", line 52 in callback_disable
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\nodes\viz\viewer_draw_mk4.py", line 873 in process
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\core\update_system.py", line 393 in do_update_general
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\utils\profile.py", line 107 in wrapper
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\core\update_system.py", line 431 in do_update
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\core\update_system.py", line 514 in process_from_node
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\node_tree.py", line 399 in process_node
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\data_structure.py", line 1249 in updateNode
 *** Break *** segmentation violation

**Comment by zeffii** [comment]
does this only happen when you have a viewdraw / stethoscope in use? does the same happen if you have a meshviewer attached only ?

**Comment by wassimj** [comment]
> does this only happen when you have a viewerdraw / stethoscope / temporal viewers in use? does the same happen if you have a meshviewer attached only ?

Not exclusively, but it does seem to stop crashing as quickly if I do NOT have a temporal viewer. Once I removed tmeporal viewer, I was able to slide the inputs and get stethosope to update almost in real-time, but if I recall, it did crash after a lot of that.

**Comment by zeffii** [comment]
can you reproduce this using just sverchok nodes?

the 2dview/3dview opengl / shader callbacks have remained relatively unchanged since about 2016, and the biggest subsequent change was the event handlers that can trigger the callbacks, this changed a lot in the switch from 2.79 to 2.80. 2018/19 and even then things seemed "relatively stable on this machine" (tm). In an attempt to minimize re-computes there are now parts of the update system that I do not have a working model for in my brain, so don't feel qualified to suggest what would be the issue. But... the error origin does hint (or i get the impression that it hints at) the callback being triggered at higher rate than it can repaint.

i think @Durman 's update system might be able to address this, if slider changes upstream will halt and restart the downstream execution. but I dunno, the code isn't finished?

**Comment by zeffii** [comment]
there are things that cause a `2dview` callback repaint ( `disable existing` followed by an `enable new` )
- moving the mouse cursor, just in general without even moving a slider
- and more generally sliding a value, because it triggers the update system + because the mouse moves
- and if for some reason you trigger an update to the nodetree
- 
in `3dview` there are similar redraws
- caused by updates to the nodetree
- caused by rotating around the 3dview
- (not sure) by editing 3dview ,
- (not sure) if i missed any.

**Comment by wassimj** [comment]
I cannot reproduce this using only sverchok nodes. So this has to do with the interaction between sverchok and Topologic. The issue is that, it works some of the times, but rapid interaction is what causes it to crash. Please see this video of the simplest definition that I could create that is making it crash. It works many times, but at one point, it creates a fault. Please see this video that shows how it crashes:
https://cf-my.sharepoint.com/:v:/g/personal/jabiw_cardiff_ac_uk/EexFjnRCJWlBo0iYgoQZUvUBxd29dFYqV1V1UB9hDyPytA?e=JcHHd6

**Comment by zeffii** [comment]
> I cannot reproduce this using only sverchok nodes

that's reassuring. because it changes the focus a little bit.

i've looked through a few of your nodes, and there's a part of the sverchok API that i think you're not appreciating in places. It appears that `socket.is_linked` may not always return True, and that's a quirk of bpy pynodes API. 

So `sv_get()`  has a `default` param just in case, it's closer to being certain that you'll get a value "no-matter-what" than if you have logic like this. (even if you copied that logic from some unfortunate Sverchok node)

https://github.com/wassimj/topologicsverchok/blob/d18e0eb18d1811cba662d95b53920891c510be58/nodes/Topologic/CellPrism.py#L225-L228

**Comment by zeffii** [comment]
but the screencap is a bit of a puzzle, why the last successful python function called would be `socket.sv_set`

**Comment by zeffii** [comment]
this message you get even when Blender doesn't crash kind of bothers me
```
Windows fatal exception: access violation
```

**Comment by zeffii** [comment]
and you can't get it to crash using just these two nodes?

![image](https://user-images.githubusercontent.com/619340/123454163-8b379b80-d5e0-11eb-9a50-4e4acce76950.png)

it doesnt have to perform anything useful to gain insight..

**Comment by zeffii** [comment]
you have a link somewhere with a one-click-to-install topologicsverchok ? I think you should post it here, i have a spare computer to try it on.

**Comment by wassimj** [comment]
1. Download and install Visual Studio 2019 with C++ Desktop development or test installing only the Visual Studio Build Tools
2. Use Blender 2.93 with python 3.92
3. Download and install BlenderBIM add-on (One Topologic node requires ifcopenshell)
The ZIP file is large (400MB) and available at:
https://cf-my.sharepoint.com/:u:/g/personal/jabiw_cardiff_ac_uk/EQQ7mP7AZy9AqivgMRiKubsBo9GpEvDoneRazAW-IEOklQ?e=Nj2Qkk

**Comment by wassimj** [comment]
> and you can't get it to crash using just these two nodes?
> 
> ![image](https://user-images.githubusercontent.com/619340/123454163-8b379b80-d5e0-11eb-9a50-4e4acce76950.png)
> 
> it doesnt have to perform anything useful to gain insight..

I was able to crash it just with the two nodes. It took longer and more manipulation, but it does crash:

https://cf-my.sharepoint.com/:v:/g/personal/jabiw_cardiff_ac_uk/ETEDSZBtrr5Ko0-Mq3O77VoBWfMHjV4YcKnZBrxu7Gks4A?e=O3DtR3
