### ISSUE TITLE
Curve Viewer output is segmented curve edge?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#4191]
## Problem statement

Curve Viewer output is not a smooth curve but like segment.

## Steps to reproduce

<img width="815" alt="Screen Shot 2021-06-30 at 9 24 26 am" src="https://user-images.githubusercontent.com/3952687/123880036-2e900400-d985-11eb-92cd-0531955e84dd.png">

## Expected result

I want to see smooth curve.

## Actual result

I am getting segmented weird looking curve

## Sverchok version

I got the latest version. Using iMac M1.

**Comment by enzyme69** [comment]
<img width="1137" alt="Screen Shot 2021-06-30 at 12 32 41 am" src="https://user-images.githubusercontent.com/3952687/123881225-9d6e5c80-d987-11eb-87ca-a21b0f0e0935.png">

Ok maybe I forgot something here, but I think Curve Viewer could also be outputting a smooth curve?

**Comment by Moult** [comment]
I would guess that the curve viewer simply takes your vertices and edges and displays it as a blender curve object (which then allows beveling, depth, etc) - it doesn't magically give you a true implicit curve, only a Curve object representation of discrete verts and edges.

In other words, doesn't seem like a bug to me, but perhaps not the node you're looking for.

**Comment by enzyme69** [comment]
Yes, I am just wondering if SV nodes now have a way to output true implicit curve or injecting it like Geometry Nodes... oh wait Geometry Nodes also does not really output Curve.

So PolyLine Viewer node is still the node.

**Comment by zeffii** [comment]
the hint is in the name, polyline, polylines are `x-----------x------------x------------x----------x` , joined entities. where the `edge` indices are implied by the order of the vertices. That's why it lacks an 'edges' socket. This is usually what you want, if you are inputting the kind of data as in the example image.

Curve Viewer is indeed just designed to output Curve objects from the edges of the incoming verts+edges combinations, it's not very versatile, but it makes it easy to render "edge-based" geometry as single segment straight curves for architectural elements, like scaffolding, beams, pipes..  i wrote it for this back in: 2014

![image](https://user-images.githubusercontent.com/619340/123934109-41113a00-d993-11eb-90d7-65eb34a1cd91.png)
