### ISSUE TITLE
Divide Curve by Distance ?

### ISSUE THREAD

**Issue by rwny** [nortikin/sverchok#4235]
Question : Is this the way to do Divide Curve by distance ?
i re-check with circle it incorrect .... 

[div_curve_by_distance001.zip](https://github.com/nortikin/sverchok/files/6863949/div_curve_by_distance001.zip)

![image_2021-07-22_235348](https://user-images.githubusercontent.com/32074126/126677983-c5a2a6ff-9187-4251-928a-3abd181064cc.png)

Thank you . 
i not see the node if it already have somewhere :)

**Comment by portnov** [comment]
The answer in this case is "Curve Length Parameter" node.
![Screenshot_20210723_075932](https://user-images.githubusercontent.com/284644/126732773-84913aec-7528-43ee-8166-e4c1cfba7d34.png)
(circles do intersect a bit, but not at the curve, so it's not because of the distance between their centers along the curve, it's because of curve's curvature).

**Comment by rwny** [comment]
Yes . Thank you very much 
![image_2021-07-23_205023](https://user-images.githubusercontent.com/32074126/126791599-a764d1af-43d0-403e-9bb9-55ccd42186c2.png)
