### ISSUE TITLE
Improve error messages from Select Mesh Elements node

### ISSUE THREAD

**Issue by sna-scourtney** [nortikin/sverchok#4312]
## Problem statement

This is a minor UX issue with the subject node's diagnostic output in the editor. If the Polygons input is disconnected, Select Mesh Elements says TypeError("'NoneType' object is not subscriptable"). If the Edges input is disconnected, the message is ValueError('not enough values to unpack (expected 2, got 0)').

These examples are with the node's default mode of "Normal Direction". Other modes produce different messages, but in all cases the user would benefit more from a message identifying the known cause, namely that a required input is not being provided from upstream.

(Nota bene: I am documenting this as an issue but am looking at contributing a patch for this and a couple other small things. I have my local Git repo set up and am reviewing the contributor guidelines before I create any branches.)

## Steps to reproduce

1. Create a simple node graph with a generator node (such as Box) connected to a Select Mesh Elements node.
2. Connect two consumer nodes (such as List Mask Out) to use the Edges Mask and Faces Mask outputs (at minimum).
3. Connect consumer node(s) to use the outputs from the List Mask nodes, so the graph section will be active.
4. Connect the Vertices input of the Select Mesh Elements node, but leave open its Edges and/or Polygons inputs.

## Expected result

Other nodes issue specific error messages when their required inputs are missing, which guides the user to know which specific input port is the problem.

## Actual result

Error messages like the two examples cited above are not helpful to non-programmers in general, and even for programmers they do not identify the port.

## Sverchok version

Sverchok was updated from its internal self-update function as of 2021-08-28.

**Comment by Durman** [comment]
More clear error messages are welcome.
But also it worth to know that rising such error messages does not lead to comfortable workflow. The thing is that Sverchok data structure has vectorization. It is independent collections of data (objects) which go through node tree from node to node. But if there is at least one collection (object) with wrong data the whole process is halting.
![2021-08-29_22-44-36](https://user-images.githubusercontent.com/28003269/131261875-0fcfda0a-c5a7-4c80-b647-56b6c4984f7e.png)
For example you can see that first object has one face but second does not have them at all. The Select mesh elements node could process first object but because it rising error it stops working. What I would expect from the node in this case is just produce an empty lists if the input data does not produce enough information for the operation.
I do not mean that this logic should be implemented but point what should be the strategy in implementation of nodes.

**Comment by sna-scourtney** [comment]
I absolutely agree with you, and I should have clarified that my intention was not to suppress the existing messages when (as in your example) they are appropriate. Rather, I was suggesting that we preempt that message only for the specific case where a required input port is not connected to anything at all.

Your example -- a connected input that provides invalid data -- is a very good illustration of your extremely valid point, but also of why I think the specific "port not connected" message is needed. If you disconnect the Polygons port, a message like TypeError(....) might lead the user to assume something was wrong with the Vertices data stream, whereas in your example the TypeError(...) message is absolutely correct and therefore useful.

I apologize if it was not clear in my proposal that I want to add a more specific message in the case where it applies, but defer to the existing messages for all other cases including the one you have cited.

**Comment by Durman** [comment]
Most likely it is me who should give apologies because my English is not as fluent as yours to be clear. What I was tring to say is that descriptive error messages are definitely leading to more comfortable workflow and should be provided where it's possible. And I encourage your initiative in this issue.

But there is also another side of this issue. Rising errors, when there is no enough data for node to be executed, does not lead to comfortable workflow sometimes. It's better to just skip such data and provide empty list as the result.

**Comment by sna-scourtney** [comment]
> Most likely it is me who should give apologies because my English is not as fluent as yours to be clear. What I was tring to say is that descriptive error messages are definitely leading to more comfortable workflow and should be provided where it's possible. And I encourage your initiative in this issue.

No need to apologize -- your English is excellent, and since I know only a few phrases in Russian (owing to a friend from there), I have no right to judge anyone. :)

Sverchok is one of several tools I have been trying in Blender, and I have determined that is is the best suited to the things I need to accomplish. So, I want to contribute as my skills and time permit, to help the community and not just benefit myself.

> 
> But there is also another side of this issue. Rising errors, when there is no enough data for node to be executed, does not lead to comfortable workflow sometimes. It's better to just skip such data and provide empty list as the result.

I agree with this as well, but I did not think it would be within acceptable scope to change the behavior of the node in this way -- and my issue is small enough that fixing it should not break existing graphs.

If instead of changing the error messages, you would prefer for me to have the node more gracefully handle missing input, I am amenable to work in that direction instead. In that case, please tell me what you think would be a reasonable fallback or default behavior for the missing inputs, and I will code toward that spec (or will discuss with you first, if we happen to disagree, but I think that is unlikely).

**Comment by Durman** [comment]
The problem with missing input data error is the global problem and most of the nodes share it. There is no strong opinion about how this should be handled yet. So I would not advise you to mess with this. I just told about the problem because thought it's good to know.
