### ISSUE TITLE
Does Sverchok support multiprocessing?

### ISSUE THREAD

**Issue by Moult** [nortikin/sverchok#4392]
Rhino / Grasshopper has something like this: https://developer.rhino3d.com/guides/grasshopper/multi-treaded-components/

When porting over Ladybug Tools, I ran across this option. Does Sverchok / Blender have a similar capability?

Example code which uses it: https://github.com/ladybug-tools/ladybug-rhino/blob/master/ladybug_rhino/grasshopper.py#L134-L175

**Comment by Durman** [comment]
There was a problem with using multiprocessing in Blender on Windows but it seems was fixed. I have tested basic examples with Blender 3.0 and they works.

Initially Sverchok was not design to support multithreading/multiprocessing. The main problem, as I see, is that nodes get access to shared memory to get initial data to process. So their parallel execution is impossible now. But I can be wrong because I'm absolutely unexperienced in this area.
#4323 this is a first step to solve the problem of shared memory.
