### ISSUE TITLE
Get Objects Data Unable to import hidden objects

### ISSUE THREAD

**Issue by vkter** [nortikin/sverchok#4402]
As shown in the figure

**Comment by vkter** [comment]
![image](https://user-images.githubusercontent.com/74725748/154784288-79b2bb17-8216-4897-90de-3e68cd3a6a2e.png)

**Comment by Durman** [comment]
Can confirm. Also this is true only if Get objects data node is in Post mode.

It seems that the problem is in getting object from depsgraph. When object is disabled the call returns None. Don't know whether it was made intentionally. Possible fix is this:
```diff
- obj = depsgraph.objects[obj_name]
+ obj = bpy.data.objects[obj_name]
```
[untitled.zip](https://github.com/nortikin/sverchok/files/8101413/untitled.zip)

**Comment by vkter** [comment]
After changing the code, the problem has been solved

**Comment by vkter** [comment]
If this problem is difficult to fix, Maybe we can think differently., add a button that hides an input object in the Get Objects Data node

**Comment by Durman** [comment]
I can make next suggestion then. Add object to a collection and hide the collection. It will hide the object as well and Get Objects Data node still will be able to read the data.

**Comment by vkter** [comment]
By hiding the collection, the node can continue to read the data, which has achieved my expectations.
