### ISSUE TITLE
FreeCAD package is not available

### ISSUE THREAD

**Issue by TekuConcept** [nortikin/sverchok#4406]
`FreeCAD package is not available, Solids nodes will not be available`

I've tried several variations to see if I could get this to work - from downloading the freecad zip referenced in the [dependency docs](https://github.com/nortikin/sverchok/wiki/FreeCAD) to running `conda create -p fc_env freecad=0.19.4 python=3.9 --copy -y -c conda-forge` as referenced in #4131

The sverchok scripts suggest FreeCAD.dll is used for windows-based systems, but the only libraries I can find close to this include FreeCADGui.dll, FreeCADApp.dll, and FreeCADBase.dll.

Sverchok version: sverchok-master.zip
Operating System: Windows 10

**Comment by rendetto** [comment]
Which Blender version you're using?
The Blender developers decided to drop compatibility with the VFX Reference Platform early this year so the Python version will follow the latest Python available:
https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

If you are using Blender3.1.0 the Python version will be 3.10 (which is not compatible with the FreeCAD you built against py3.9).

So you have several options:
1. Use Blender3.0.0 (which is py3.9)
2. Compile Blender3.1.0 against python3.9 (I don't know if that's possible)
3. Create conda package of FreeCAD against python3.10 (I cannot say if this is possible either, because I just tried and it failed)

Any help for creating conda FreeCAD package which is py3.10 compatible is welcome. 

Thanks

**Comment by TekuConcept** [comment]
Good point! I assumed python compatibility under the same major but different minor versions.

I’m using Blender 3.2-alpha, which uses Python3.11. I’ll see if I can compile FreeCAD against Py3.11 then.

**Comment by TekuConcept** [comment]
I'll close this issue for now since FreeCAD doesn't yet support the target python version.
