### ISSUE TITLE
Stable build cannot be enabled after installing

### ISSUE THREAD

**Issue by kevinwright** [nortikin/sverchok#4413]
## Problem statement

Please describe your problem here.

## Steps to reproduce

1. Download sverchok-1.0.0.zip
2. Install it
3. Attempt to enable it

## Expected result

The plugin is enabled

## Actual result

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'sverchok-1' 
```

## Sverchok version

1.0.0 stable release

## Analysis and workaround

`sverchok-1.0.0.zip` contains the folder `sverchok-1.0.0` which (on windows) is copied to `%AppData%\Roaming\Blender Foundation\Blender\3.0\scripts\addons\sverchok-1.0.0`. But enabling the plugin looks for `...\addons\sverchok-1`

Renaming the folder after installation allows the plugin to be enabled.

## Suggested fix

Package the zip with the correct folder name in the first place.

**Comment by zeffii** [comment]
rename the directory to just `sverchok` and the re-enable

**Comment by kevinwright** [comment]
> rename the directory to just `sverchok` and the re-enable

Yes, I already said I did that as a workaround - doesn't fix the underlying problem for others though

**Comment by zeffii** [comment]
no you're right. but it can't be fixed by us by changing any sverchok code. I suggest sticking to the zipped master in future.
https://github.com/nortikin/sverchok/archive/refs/heads/master.zip

**Comment by zeffii** [comment]
i welcome you to propose a change to the installation issues section of the readme. I can't seem to make it cover issues encountered by users.
https://github.com/nortikin/sverchok#troubleshooting-installation-errors

**Comment by macdroid53** [comment]
Blender 3.1 was definitely not going to work since the python version was different on this Debian 11 PC.

So, Blender 2.93 when attempting to enable:

Initially, in Blender preferences attempting to enable sverchok complained about not finding libTKV3d.so.7.7

So, finding that in occt's install directory, I then exported the occt lib directory. (OCCT being the OpenCASCADE engine that FreeCAD uses.)

[code]export LD_LIBRARY_PATH=$HOME/occt7-install/lib[/code]

After that I copied the sverchok download that had the FreeCAD to [code]/home/mac/.config/blender/2.93/scripts/addons/sverchok/[/code]

Then it was a matter of learning how to find the sverchok nodes to add in the Blender Nodes UI and seems to be working.
