### ISSUE TITLE
Improve CI build

### ISSUE THREAD

**Issue by kevinwright** [nortikin/sverchok#4415]
## Problem statement

The existing build and release process via github actions can be improved upon:

- Use blender via a docker image with dependencies pre-installed, this significantly speed up builds (only need to do the `pip install`s when building the image, not every time a test is run)
- Test against multiple blender versions
- Explicitly build a release zip in the correct structure that it can be installed via the blender UI or API without folder renaming
- Auto-tag the codebase on a successful build
- Produce a release on a successful build

Examples of usage:
- The commit with the changes: https://github.com/kevinwright/sverchok/commit/affdac475cb95d1ea5e4f5c8adc274117eb1d1a0
- A successful automated build, testing against two blender versions and uploading artifacts: https://github.com/kevinwright/sverchok/actions/runs/2081826659
- The corresponding release action: https://github.com/kevinwright/sverchok/actions/runs/2081829907
- The test docker image: https://github.com/kevinwright/sverchok-testing-image

**This is not something that can be done via just a pull request.** An authorisation token must be added to the repository for the tagging operation, and the second project to build the docker image also needs to be migrated. So I'm opening it up for discussion via an issue first, and I'm happy to talk anyone through how it works.

**Comment by Durman** [comment]
Related issue #4103

* I'm not familiar with docker images. If it solves only performance problem then probably it's not very useful because performance, as I see, is not a problem.
* Tests for multiple Bender versions would nice.
* Actually Sverchok is made in a way that renaming add-on folder is unnecessary step, thought probably it's not always work correctly according to some reports.)
* Probably, but it's not clear which rules should be applied here. I'm against applying of standard rules. This can be a mixture of auto and manual version incrementation. Something like this `Vmanual.manual.auto`
* I'm not sure that creating releases for every successful build is a good idea. Probably builds can be stored in actions instead, in case they are really necessary. I would prefer to keep releases storage only for really big releases.

**Comment by kevinwright** [comment]
"releases" might not be the best name, but it's what github gives us

If you look here: https://github.com/kevinwright/sverchok/releases

You can se releases named build-2081826659-8, build-2081783486-7, etc. These all have corresponding tags in git too.

Any one of those could then be given an additional "v1.1.2" tag to produce a *true* stable release.

**Comment by Durman** [comment]
It's strange that the add-on can't be enabled because of the folder name. Sverchok does a trick to handle this case by renaming the initial module.

https://github.com/nortikin/sverchok/blob/9a0f4fee42c5f492a80e86341d2d3e7e6585a9bc/__init__.py#L64-L66

Probably this problem occurs only in Blender 3.1+ with Python 3.10. Last Python version might have some changes which break the solution. I will check this.

**Comment by Durman** [comment]
Well, it works for me on Blender 3.1.2. I'm not sure what causes the problem. 🤔 
![image](https://user-images.githubusercontent.com/28003269/161680744-cff2bce2-ed80-427f-879b-c341c611e1cf.png)

**Comment by Durman** [comment]
Found the problem #4420

**Comment by kevinwright** [comment]
> Probably this problem occurs only in Blender 3.1+ with Python 3.10. Last Python version might have some changes which break the solution.

I've reproduced in 2.93, 3.0, and 3.1

**Comment by zeffii** [comment]
I don't think we feel obliged to keep master supporting all possible Blender revisions. ( 2.8x 2.9x 3.x ), that would start to complicate stuff, if there's a way to automate a table creation which associated last Sverchok git-hash to support certain Blender versions, no one will object to that but it would something we would need to only occasionally run.

I support your PR but only for the creation of the custom zip.

**Comment by kevinwright** [comment]
It's simplicity itself to control which versions are tested against:

https://github.com/kevinwright/sverchok/blob/master/.github/workflows/build-and-test.yml#L27-L36

Nothing is being *forced* here, I'm just providing options

**Comment by kevinwright** [comment]
> if there's a way to automate a table creation which associated last Sverchok git-hash to support certain Blender versions

It goes a bit deep than that. For example, blender 3.1 uses the latest version of `numpy`, but installing `numba` downgrades this and causes things to break. I haven't been able to get unit tests to run in 3.1 but I **have** installed the addon in that version and made some things work.

So we'd need a table listing which **nodes** work in which version. This is 100% possible, though we'd want to update the unit tests to also produce a structured output or special easily-matched messages in the log output. It could perhaps be run as a secondary step in each build to trigger if the initial tests (against 2.93) pass

**Comment by Durman** [comment]
I have to agree =) that creating builds has a lot of benefits which were already mentioned and others. But I repeat my concerns about locating them in the release section. My vision is that that place is dedicated only for real/big releases. My suggestion is to use action storage. As example the same approach is used in Animation nodes:

![image](https://user-images.githubusercontent.com/28003269/162118919-ed69ad96-d22c-4312-acb8-362e4e8916f7.png)

**Comment by kevinwright** [comment]
I see no problem with that
