### ISSUE TITLE
Raycaster incompatible with numpy

### ISSUE THREAD

**Issue by ArpegorPSGH** [nortikin/sverchok#4477]
I tried using numpy in one of my node trees, but it crashed because raycaster node do not expect numpy arrays. Could this node be made compatible with numpy?

**Comment by zeffii** [comment]
yes, but in the meantime you can use a `Numpy Array` node and use the `tolist()` function.
![image](https://user-images.githubusercontent.com/619340/169259174-ecf37e2e-c65b-492d-8814-e67fa38c9f50.png)

**Comment by zeffii** [comment]
@ArpegorPSGH  which raycasting node are you using we have several.
'Raycaster' should support them by default.
but these may not. (yet)
``` 
C:\Users\zeffi\Desktop\github\sverchok\nodes\object_nodes\object_raycast2.py:
   53      bl_label = 'Object ID Raycast MK2'  # new is nonsense name
C:\Users\zeffi\Desktop\github\sverchok\nodes\object_nodes\scene_raycast2.py:
   27      bl_label = 'Scene Raycast MK2' #new is nonsense name
```

**Comment by zeffii** [comment]
if you can provide a simple `.blend` which demonstrates the crash, that would be great.

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/169275842-2c7cb336-1436-433e-a9e8-06d593f61a8e.png)
[raycasta_2022_05_19_10_45.zip](https://github.com/nortikin/sverchok/files/8728379/raycasta_2022_05_19_10_45.zip)

sverchok-master 's Blender 3.1 raycaster accepts all input as numpy.

**Comment by ArpegorPSGH** [comment]
I use Blender 2.92, as I have multiple scripts in my node trees and I am not sure they would still work with Blender 3+. Do you mean if I simply get the last Blender version, the Raycaster node will work. I do not know which Raycaster I am using, as I only found one node called 'Raycaster', I did not take the other one containing "raycaster" in its name. However, it definitely has the same inputs, outputs and layout as the one above.

**Comment by zeffii** [comment]
> I use Blender 2.92, as I have multiple scripts in my node trees and I am not sure they would still work with Blender 3+. Do you mean if I simply get the last Blender version, the Raycaster node will work? 

i wouldn't presume to say that. Is there any particular reason why you are using 2.92?  this might have nothing to do which version of Blender/sverchok you're using. as np.array was supported in Raycaster since: https://github.com/nortikin/sverchok/blame/master/utils/bvh_tree.py (about 14 months ago) which is i think close to the age of  blender 2.92 ..so yeah, if you are using an older version of Sverchok check this file:
https://github.com/nortikin/sverchok/blob/82af1bf6a406520f5210cd961b67b9afd71754fc/utils/bvh_tree.py
if your local copy of bvh_tree.py looks like that, then it will not support numpy until you convert it first. ( or upgrade Sverchok... and that will mean probably upgrading Blender to 3.0+ )

scripts that work in 2.92 should work in 3+ , unless there is some kind of dependency that can't be met.  It's possible to try a portable version of Blender 3.1+ on your machine and use a recent Sverchok (cutting edge) https://github.com/nortikin/sverchok/archive/refs/heads/master.zip

**Comment by ArpegorPSGH** [comment]
I downloaded sverchok 10 months ago, and updated it via the dedicated button directly in Blender a few weeks ago, so this should not be the problem. I will check if I am really using the right Raycaster node. If that does not work, I'll try upgrading Blender.
I do not need it to work right now. After all, the script using it is so slow (a few faces/s) that it won't be usable until nodes stop using pure python and multi-threading is introduced.

**Comment by zeffii** [comment]
i am intrigued at the nothing that some process is only able to do something for a few faces per second. so it might be worth explaining and a demo :)

**Comment by zeffii** [comment]
i'd like to point out that multi-threading won't fix everything, it will just apply brute force to a problem. Sometimes the problem lies in the algorithm, rather than the language it is executed in.

For example, the Raycaster node is nice and all, but it's a "Lite" node, it expects the input Mesh to be non-static, therefor it rebuilds the BVHTree continuously upon scene updates. Depending on how "expensive" that mesh is, this can be a big step, perhaps what you want is a version of that node that only builds the bvhtree once.  who knows? :)

**Comment by ArpegorPSGH** [comment]
Well, the node tree I am working on aims at automatically measuring maximal thickness admissible by each face (to avoid going through another face upon solidification) of an object that can have tens of thousands of faces, and then solidify or not each loose part of the object depending on its average thickness and how thick each face should be relatively to its maximal thickness. This takes almost two hundreds nodes, plus two small scripts to prepare the object at the beginning, and solidify it at the end, since I want to preserve materials and UV maps. Currently, on a base blender cube (12 faces with triangularization), it takes around 3 seconds. However, I enabled node timing, so that may slow down the whole process. Durman said that nodes could be accelerated hundreds of times if they were fully optimized, without even multi-threading. Also, I use a 10 years old laptop with an intel core 7 3630QM and 8GB of RAM (waiting to buy a new computer for 2 years now, but the market is just strating to recover).

**Comment by zeffii** [comment]
> Well, the node tree I am working on aims at automatically measuring maximal thickness admissible by each face (to avoid going through another face upon solidification) of an object that can have tens of thousands of faces, and then solidify or not each loose part of the object depending on its average thickness and how thick each face should be relatively to its maximal thickness. This takes almost two hundreds nodes, plus two small scripts to prepare the object at the beginning, and solidify it at the end, since I want to preserve materials and UV maps.

i understand if you don't want to share the .blend for our insights, but i'm going to close this issue because the topic is drifting away from the title and turning more abstract. Feel free to start a [discussion](https://github.com/nortikin/sverchok/discussions)

**Comment by ArpegorPSGH** [comment]
Well, it's not that I don't want to, but rather than it is quite messy, as there are node trees and models everywhere for testing purposes, along with intermediate versions of the node trees. I'll maybe post some part of it when it is completely finished, as this is still a work in progress (it has been for the last 2-3 months).

**Comment by zeffii** [comment]
we've been doing this for a almost a decade now :)    and have seen some crazy trees...we learn as much from them as you will by showing them.  but it's up to you.   like i said, i understand if you don't want to.
