### ISSUE TITLE
Untimely Execution of Scripts Within For Each Loops

### ISSUE THREAD

**Issue by ArpegorPSGH** [nortikin/sverchok#4551]
I am creating a node tree with a for each loop, and within this loop I have a script node which add and then apply a modifier to the object considered in the loop. I have noticed that the first iteration of the loop is executed twice, adding two modifiers to my first object, which completely messes the processing afterwards. In this particular case, I can work around that by putting the script node outside the loop, but it may not always be the case, so could this issue be resolved?

**Comment by Durman** [comment]
Yes, such thing can happen. This is actually how the loop nodes are implemented. All nodes are executed by update system in ordinary way until it comes to Loop out node. This node intercept execution and evaluate previous nodes again because update system can't guarantee that they all are evaluated properly. Here is where extra execution can appear.

https://github.com/nortikin/sverchok/blob/5ea267f9d1019ec3f744564ca9a636df76416a5c/nodes/logic/loop_out.py#L296-L298

There definitely should be ways to improve this but the problem with them is that it will require extra complexity in update system and this is not what is easy to fix (as far as I can see).

One of the solutions could be to forbid to execution system evaluate nodes between loop nodes at all and to pass execution to them. Probably in order to do this update system should consider loop expression as one big node so it would be able to find all previous nodes which should be executed before loop can start its job.

**Comment by ArpegorPSGH** [comment]
Okay, I will keep that in mind. I solved my problem by extracting the script from the loop, the only downside being that both the node tree and the scripts are now a bit more complicated, but it's good enough for me.
