### ISSUE TITLE
Bug at the upper domain limit for unclamped splines (geomdl and Native implementations) 

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#4722]
I'm reporting the strange behavior of the unclamped splines mentioned in https://github.com/nortikin/sverchok/issues/4469 
It is still present for Native and geomdl implementations with the most recent Sverchok master.

![LatestSV_PeriodicSplineBug](https://user-images.githubusercontent.com/66558924/198097371-b65dfb59-d187-462f-99ca-1a0185ea9380.JPG)

The setup is the same as used in https://github.com/nortikin/sverchok/issues/4469 (a constructed closed unclamped /periodic/ spline using wrapped control points - a convenient method for constructing arbitrary smoothly closed curves)
The problem is present when taking a segment from a spline and the end (TMax) of this segment is exactly at the upper domain limit (which is 1.0 in this particular example)

I found that reverting to an earlier version of Sverchok (32f8f36787fcf89809d6cff6165caa662bb1ea26) this problem is not present for both Native and geomdl. I run this early version of Sverchok under blender-2.90.0-windows64 and also aligned it to the corresponding Sverchok-extra for the time being.
I also used the latest geomdl (v5.3.1) due to #3521 and https://github.com/orbingol/NURBS-Python/issues/115

![oldSV_PeriodicSpline](https://user-images.githubusercontent.com/66558924/198098581-134c124f-9e03-4198-8903-35a3020bd0c3.JPG)

As with other similar issues I got, there is a workaround that could "solve" the issue by using a value of 0.99999 instead of 1.0

**Comment by portnov** [comment]
Well, what I understood for now.
1. Splitting of a Nurbs curve at parmeter `t` is done by inserting a knot in that point `p` times (`p` being the degree of the curve). After such insertion, there will be a control point coinciding with `Curve(t)` point. After that, the process of splitting is obvious: first segment's control points are all old control points at left of `t` plus new control point, second segment's control points are new control point plus all old control points at right of `t`.
2. Knot insertion always cuts a corner, or several corners, from curve's control polygon. On illustration from The Nurbs Book, P are old control points, Q are new control points:

![Screenshot_20221104_132455](https://user-images.githubusercontent.com/284644/199926751-b71d71f4-9ddc-43ab-817a-dbe5a1739f50.png)

So to calculate how exactly corners must be cut, one has to have several control points at left of `t` and several control points at right of `t`, otherwise there will be no corners to be cut.
3. If curve's knotvector is clamped, then mathematically there are enough "corners" (of zero size) at the ends of the curve. So formulas for knot insertion work fine if you try to add a knot near the end of the curve (but not exactly in the start or end point).
4. If curve's knotvector is not clamped, then, if you try to insert a knot near to curve's end, you will find that there are not enough control points either on the left or on the right of `t`, to form corners which are to be cut. So, depending on specific algorithm which you use for knot insertion, you will either get deformed curve, or get something like division by zero. In short: mathematically, usual knot insertion process is not possible for non-clamped curves near curve's ends.
5. The only workaround I see here (and probably it's what was working in Sverchok earlier) in such cases, is to do not try to calculate control points of segment (to form a new nurbs curve), but instead just take a subdomain of initial curve.

**Comment by portnov** [comment]
> So, depending on specific algorithm which you use for knot insertion, you will either get deformed curve, or get something like division by zero. 

For example, if you try FreeCAD implementation of curve in your setup, you will see an error thrown from FreeCAD API.

**Comment by portnov** [comment]
Aha, I managed to read 12th chapter of The Nurbs book :)
There they say, that for unclamped knotvectors, the curve is defined not on the whole interval covered by knotvector, but only on `[u[p]; u[m-p]]` (where `u` is knotvector, `p` is curve's degree and `m` is number of control points). I.e., the beginning and the end of such curve must be just ignored.

However,
1. It does not make sense to insert knots for unclamped knotvector before `u[p]` or after `u[m-p]`.
2. But, insertion of knot exactly at `u[p]` or `u[m-p]` still makes sense. I just had a bug in knot insertion code.

**Comment by portnov** [comment]
> BTW the Curve Segment is really usefull with this NURBS output, but the corresponding Surface Subdomain node doesn't have NURBS output. Do you plan implementing that functionality?

Shouldn't be too hard to implement. But I can't promise that I will do this soon.

**Comment by rendetto** [comment]
No pressure :) 

Thanks again.

**Comment by portnov** [comment]
@rendetto I filed a bug to Geomdl library: https://github.com/orbingol/NURBS-Python/issues/158 .
