### ISSUE TITLE
Node "Torus knot" create curved cycles if p==q.

### ISSUE THREAD

**Issue by satabol** [nortikin/sverchok#4746]
Windows 11, Blender 3.3.1, Sverchok - master

p==q==3 - three cycles
p==q==4 - four cycles
![image](https://user-images.githubusercontent.com/14288520/200142945-95e6f5fb-73cb-4fe8-90d4-326f160e6471.png)

If p!=q then "Torus Knot" create right torus:

![image](https://user-images.githubusercontent.com/14288520/200143049-ab102c18-ac23-4c80-8494-0c8ede081ce9.png)

**Comment by portnov** [comment]
As far as I understand, this is as expected :)

**Comment by satabol** [comment]
@portnov  Thank you . I surprised. Name of node is “Torus Knot”. Not “Torus Knots”. But there is a comment in docs:
P/Q: “Used without adaptive resolution these allow to create aliased torus knots resulting in all sorts of interesting shaped knots.” (http://nortikin.github.io/sverchok/docs/nodes/generators_extended/torus_knot_mk2.html)
Do you mean this?

**Comment by portnov** [comment]
@satabol mathematically it is obvious, imho :) It can be illustrated simply enough, if you cut the knot along one of it's meridians and along one of it's parallels, and then unroll the knot into rectangle.
Draw a `p` x `q` rectangle on a checkered paper. Start drawing `p` parallel lines from one of sides of that rectangles, at 45 degrees. When you encounter another side of the rectangle, jump to the opposite side (we are on the surface of a torus) and continue.
If you experiment with different `p` and `q`, you will discover, that when `p` and `q` do not have common divisors, all your lines eventually happen to be continuation of one another (if you remember that opposite sides of rectangle should be glued in order to form a torus), so you actually have drawn only one line. When `p` and `q` have common divisor, you will see that you have drawn several disconnected lines.
![Screenshot_20221106_195109](https://user-images.githubusercontent.com/284644/200178103-47803474-7a89-4bec-ba07-7dd56a10b0a9.png)

**Comment by satabol** [comment]
@portnov Thank you very much. I did not know this. It is obvious now!
