### ISSUE TITLE
Modifiers->Modifier Make->"Subdivide Lite" Incorrect Result on mask some edges

### ISSUE THREAD

**Issue by satabol** [nortikin/sverchok#4751]
Windows 11, blender 3.3.1, sverchok-master:

Comparison of "subdivide" and "subdivide lite":

![image](https://user-images.githubusercontent.com/14288520/200698364-7d5a2cee-fa1e-4c33-badc-bcbcc9d1dbc0.png)

But with list [1,4,7,10] result of "subdivide lite" is good:

![image](https://user-images.githubusercontent.com/14288520/200697937-f516eba4-f2a3-4011-aab5-1656aad966d1.png)

**Comment by Durman** [comment]
It works correctly if to put edges instead of faces. When you put faces the node extracts edges in unpredictable order and you can't select certain edges. The problem seems is in the node design. Though in the documentation there is an example with selection which does not work currently. As variant we can remove the node, because it's not clear what is advantages of having two nodes with the same functionality. It would be less efficient to support them both.

![image](https://user-images.githubusercontent.com/28003269/200738394-6deb9386-b515-47f4-b878-d98be7c4d990.png)

**Comment by satabol** [comment]
@Durman Where is faces in your example? Can you turn it on? (Socket name of "Subdivide lite" is "edg_pol" so faces allowed too)

In the doc: http://nortikin.github.io/sverchok/docs/nodes/modifier_make/subdivide_lite.html there is no restriction about edges only.

**Comment by satabol** [comment]
gist: https://gist.github.com/8b67b9c623fd54c263a639fc691cc7f1

**Comment by Durman** [comment]
I just demonstrated that with edges it works correctly,

**Comment by satabol** [comment]
@Durman Ok, Thank you. I did not realize this a day ago. But what the difference these two nodes? They seems twin. They both use one operator. The only difference is “lite” node has no face socket and edg_pol socket work only with edges. May be this is a bug?
Or may be just remove “lite” node as identical in the future? )))

**Comment by satabol** [comment]
I agree. Can you add “subdivide lite” to TODO list at #4737 ?

**Comment by satabol** [comment]
I can do it as proposal in #4737.

**Comment by Durman** [comment]
If you wish you can edit the first post in the thread. I guess you has permissions for that.

But I don't think the node should be removed completely, it rather should be moved into the old nodes folder.
