### ISSUE TITLE
Spatial Delaunay 2D Cdt "inside" mode unexpected result. 

### ISSUE THREAD

**Issue by satabol** [nortikin/sverchok#4764]
Windows 11, Blender 3.3.1, Sverchok master.

"Inside" mode has to exclude points from triangulation if they are outside faces. Single face are not excluded from delaunay if mode is "inside":

![image](https://user-images.githubusercontent.com/14288520/202150425-e64ffec1-1a2e-4a8f-9004-98bad951ac61.png)
![image](https://user-images.githubusercontent.com/14288520/202152484-d7895e58-69fb-4a36-802d-648978dc5432.png)

for tests: https://gist.github.com/d1a8ab1aaf833f0d1fbf0ec479841c9f

doc: http://nortikin.github.io/sverchok/docs/nodes/spatial/delaunay_2d_cdt.html

**Comment by Durman** [comment]
Looks like a bug in the [delaunay_2d_cdt](https://docs.blender.org/api/3.3/mathutils.geometry.html#mathutils.geometry.delaunay_2d_cdt) Blender function.

**Comment by Durman** [comment]
Well, I can't really name it a bug. The doc says that it triangulates inside constrains and it really does not have any explanation of what constrains are. I assume that constrains are edges. In this case the current behavior is expected. The node documentation can be more explicit about that.

Also I guess it's possible to implement behavior when constrains are faces. The Blender function returns indexes of old faces and if new face does not have correspondent old face its index might be -1. So all what should be done is just to clear out all faces with -1 index. But it should be done in different mode since current behavior can be already in use.

**Comment by satabol** [comment]
As I see this node do not show all output modes existed in docs:

![image](https://user-images.githubusercontent.com/14288520/207950833-d7c4237c-9020-4a95-b867-15695c2bdff1.png)

I test modes 2,3,4,5 manually and found they are very unstable and cause Blender crash every time I select any of 2-5. I guess mode 3 is what I want. 

![image](https://user-images.githubusercontent.com/14288520/207951159-4650cdc6-69b7-45c5-aaf0-d7ea5e8b2c99.png)

)))
