### ISSUE TITLE
No dependency "numexpr" in list of dependency for a node "Num expression node"

### ISSUE THREAD

**Issue by satabol** [nortikin/sverchok#4984]
Sverchok 1.3-alpha, Blender 3.6.1, Windows 11.

Try to create Script->"Num expression node". No "numexpr" in dependencies of Sverchok:

![image](https://github.com/nortikin/sverchok/assets/14288520/85f2f826-e0b4-4ffc-9a58-5c3e94355150)

**Comment by Durman** [comment]
Yes I was lasy to add one more dependency just because of one node. I actually think that it's possible to invent alternative way to install. For example when user clicks on a node to add with a missing dependency we can propose to install the library instead of actual adding the node. But in this case all nodes should be active in the menu.

**Comment by satabol** [comment]
Ok. I append this library in console and this node active now:

![image](https://github.com/nortikin/sverchok/assets/14288520/17f18682-1b29-4ee0-906f-569090591b2a)

But these is some errors in console. May be I debug them later.
