### ISSUE TITLE
BootStrap script

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#560]
I intend to make a script that runs in the TextEditor to do a Bootstrapped installation of Sverchok. Any suggestions below are welcome

**Comment by yanivg101** [comment]
I think that the order need to be:
1. download the sverchok-master.zip
2. unpack it to temp folder.
3. if everything until here goes well continue:
4. search for the installed addon.
5. replace it.

the reason for that is that when you download after you delete the working version and suddenly have no internet or some other problems with downloading/unpacking etc you lose the working version.

in other addons, sometimes I can't just uninstall them with Blender UI because I have wierd permission problems so I need to delete them manually (windows 7) so you need to check also this issue.

**Comment by zeffii** [comment]
We can tailor different scripts to different operating systems. I will probably only make this script for people who are installing Sverchok for the first time - it won't need to look for installed copies.

**Comment by zeffii** [comment]
yes, there are many ways to write such a script. many interpretations of what is desirable. I'll probably only make a script that helps install Sverchok if it hasn't been installed yet. so
- download 
- find `\addons` of current blender executable
- unpack into `\addons`

It shouldn't expect sverchok or sverchok-master or any other branch, but if it does it could certainly do alternative behaviour - like what you mention

**Comment by zeffii** [comment]
so, several flavours of bootstrap script. either separate scripts, or one script with Flags that the user can set (dictionary entries) so the script does a specific thing. maybe like 

modes = {
   'download': True,
   'backup_current_if_found':  True,
   'look_in_addons':  True,
   'look_in_addons_contrib':  True
}

something like this..

**Comment by nortikin** [comment]
Since not have windows, it is strange behaviour.
upgrade from master always danger.

**Comment by zeffii** [comment]
<script src="https://gist.github.com/zeffii/91faac0febf94c2f7831.js"></script>
untested as joined script, but separately the compoinents do work.
I'm not recommending anyone uses this on existing Blender / Sverchok installations.

**Comment by zeffii** [comment]
I'd like to confirm that this script (bootstrap) works nicely. I'm currently running a ubuntu from a live usb stick and ran the script once in text editor and the addon was downloaded and I was able to enable it and it works :)

**Comment by zeffii** [comment]
now... it would be possible to make this script shorter by making it so it downloads much of the working code, into a data.text block or simply ` exec()`  it.
