### ISSUE TITLE
Scripted node disconnects and unloads inside group

### ISSUE THREAD

**Issue by snovvfall** [nortikin/sverchok#597]
![scripted node in group](https://cloud.githubusercontent.com/assets/2778154/6839251/a4bb1706-d3a0-11e4-9a9b-c798da861139.png)

**Comment by ly29** [comment]
Groups needs to be redone, that said I will take a look at.

**Comment by zeffii** [comment]
inside ` import_tree`  the inputs and outputs of the script node are not created yet when the loop tries to connect the inputs/outputs of the script node.

Because the PyNodes API doesn't offer a tidy way to do groups the Beta Groups feature of sverchok is necessarily hacky, and doubly so as it relies on code I wrote to store layouts as jsons, which itself is also quite admittedly a very tentative approach to solving lots of ugly problems with storing a serialized version of a _nodetree_.

the ` import_tree` function might need an additional switch for use in the SvGroups . ScriptNode does retain the script.. but needs to internally have 'reload' triggered once to get the sockets..

**Comment by zeffii** [comment]
hmmm.. it seems the links are created, but when the ` Edit group` button is pressed something changes

**Comment by zeffii** [comment]
work is being done on Group nodes, it probably will solve this. if not - we reopen.
