### ISSUE TITLE
Cannot activate on macos 

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#604]
On BA forum there is message from guy using MACos 32bit, blender 2.71.

```
Hello.

I'm really interested in use Sverchok. I have blender 2.71 on an old iMac but when I tried to activate the addon, suddenly displays a lot of error. I don't know what happens. Maybe I can use it with my computer. Would you help me?

Thanks! 
```
```
Traceback (more recent call last):

File "/Applications/Blender/blender.app/Contents/MacOS/2.71/scripts/modules/addon_utils.py". line 299, in enable mod = -import_(module_name)

File "/Applications/Blender/blender.app/Contents/MacOS/2.71/scripts/addons/sverchok-master/_init_.py". line 124, in <module> node_list = make_node_list()

File "/Applications/Blender/blender.app/Contents/MacOS/2.71/scripts/addons/sverchok-master/_init_.py". line 116, in make_node_list for category, names in nodes.nodes_dist.items():

NameError: names 'nodes' is not defined
```

**Comment by ly29** [comment]
Try with 2.72 at least, due to some changes in python version of blender.

**Comment by zeffii** [comment]
get the latest Blender 2.74 from https://builder.blender.org/download/ and try again.

**Comment by nortikin** [comment]
there is no 32bit version of blender for MACos anymore. Last was 2.71. I donno why.
That is real problem.

**Comment by zeffii** [comment]
ooohww I see.. yeah. most unfortunate

**Comment by zeffii** [comment]
for OS 10.6 won work ? 
![image](https://cloud.githubusercontent.com/assets/619340/7253397/aede7592-e83c-11e4-9942-736fb0c2dfd0.png)

**Comment by ly29** [comment]
Due to some changes in blenders python which also happened for 2.72 making sverchok load would take some work.  Further changes in 2.73 blenders python api makes even more work to support older versions.

So if you have one of the few models, basiclly the first generation of intel imacs from 2006 with core duo, then newer blender will not work. If it isn't from 2006 but later then it should work.

Unless the shown by @zeffii above works.

**Comment by zeffii** [comment]
closing for now as seems inactive
