### ISSUE TITLE
Can the "Angles at Edges" computation be sped up?

### ISSUE THREAD

**Issue by ThomasHelzle** [nortikin/sverchok#681]
Hey,

I recently worked on a hexagonal grid and found that the "Angles at Edges" node was extremely slow.
I attached two images, the first shows the mesh before the bevel to give you an impression of the relatively simple geometry and a second image with the final mesh with bevels only on the sharp corners.
The computation was actually much faster if I bevelled everything without masking - which somehow feels wrong ;-)

I don't know enough about the inner workings of meshes in Blender to be of any help, but thought I should at least ask if something can be done about it.

I can provide the scene if needed.

Thank you very very much for all the work you do with Sverchok!!!

Cheers,

Tom

![sverchok_bevel_before](https://cloud.githubusercontent.com/assets/4435871/7982076/2f9165de-0ab4-11e5-8281-3dbc177ba383.jpg)
![sverchok_bevel_after](https://cloud.githubusercontent.com/assets/4435871/7982087/46f90bc8-0ab4-11e5-8553-4565f0096006.jpg)

**Comment by portnov** [comment]
Current implementation of both nodes, "Angles at Edges" and "Bevel" is slow. The issue seems to be trivial at first glance, but it is not, due to current architecture of Sverchok. These nodes (and some other) work by converting Sverchok's native representation of mesh (lists of vertices, edges and faces) into Blender's internal representation, called BMesh; then some Blender's native operators are applied (this part is most complex computationally, but fast); and then BMesh is converted to Sverchok's representation again. The problem is that order of edges and faces in BMesh representation is selected by Blender for it's own purposes, and this order does not correspond to the order of edges and faces in Sverchok's representation. And we can not predict the order of edges BMesh will choose to use. So, say, second edge in Sverchok may become 20th in BMesh. So at converting mesh between representations, node needs to search needed edge in BMesh, and this search is the slowest part of node work.
The problem could be fully extinguished if Sverchok used BMesh as it's native mesh representation; but this would require a lot of changes in Sverchok's core, and would affect all nodes. And BMesh does not support some operators, which are currently implemented in Sverchok in terms of vertices, edges and faces lists. So for some nodes we still would need to convert mesh between representations.

**Comment by portnov** [comment]
@zeffii , maybe you have something to add?

**Comment by zeffii** [comment]
Nope, I just looked (not the code) but can only confirm that if it works fine without the mask, then the mask isn't needed and is in-fact just extra computation for no gain. If you can live without the mask drop it.

**Comment by zeffii** [comment]
Adding a bmesh socket type would be neat, it's not planned but could happen and it would simplify the code of certain nodes a lot, we haven't tried a bmesh socket type yet, it may be interesting to see how stable that would be..

**Comment by zeffii** [comment]
@portnov have you  considered using a layer mask for the bm conversion?
http://blender.stackexchange.com/questions/31849/python-custom-data-of-vertices/31850#31850

not sure if it would be useful, but maybe.

**Comment by ThomasHelzle** [comment]
Thanks a lot for your comments and explanations!

@zeffii : Sorry if I was unclear: I can not drop the mask, since in that case I would get "bevels" even in completely flat areas and in places where the bevel creates weird structures.
What I was trying to say was, that if I bevel everything (no mask), the speed is much better. The generation of the mask with Angles at Edges is what makes the whole thing extremely slow.

But from your explanation I wonder: Would it be possible/make sense to make the mask-by-angle a direct part of the bevel node, so that the conversion only has to happen once? In a generative system like Sverchok I would imagine that you basically need a mask by angle in almost every case that is more complex than a cube... ;-)

I can't comment on the bmesh socket but if it would help with cases like this and is feasible/stable, maybe some exploration would make sense?

I'll link to the Blender Scene here for you to test:
http://www.screendream.de/stuff/Sverchok/Sverchok_Test8.blend

Cheers and thanks!

Tom

**Comment by zeffii** [comment]
yep, auto bevel edges that form a certain angle with their faces makes complete sense. ( min angle, max angle, angle range )

**Comment by nortikin** [comment]
additionally - if you change something heavy - turn off button P in panel to not process layout. it will save energy

**Comment by ThomasHelzle** [comment]
@nortikin: Ok. It's just not always so easy when you need to see what happens ;-)
But for work I used a smaller grid, so it was a bit more bearable.
