### ISSUE TITLE
Mesh instances aren't deleted after mesh instancer node is deleted

### ISSUE THREAD

**Issue by naught101** [nortikin/sverchok#770]
If I create a Mesh Instancer, with a matrix input, and use an existing mesh, then a bunch of "Alpha_X" objects are created. If I then delete the Mesh Instancer node, all of the "Alpha_X" objects remain, and I have to delete them all manually, which can be a pain.

It would be good if there was a way to automatically remove them from the Mesh Instancer node, and it would be good if they were deleted when the Mesh Instancer node was deleted, or when the "Reset" button was pressed..

**Comment by zeffii** [comment]
i see your point, not sure when/how best to implement an obvious solution.

A quick work around is to use the Group feature, tick it, and the next update of the node tree will cause all instances of the mesh to be grouped. The _outliner_ lets you select by group, and select all items in the group. then you hit X.

One reason I never added automatic removal of instances upon removal of the Mesh instancer node is that I do sometimes want instances to remain, and I know of the above workaround to delete instances..

But..seen as you bring up the point, I'll think about it a little. (it's been a while since I've done any Sverchok coding)

**Comment by naught101** [comment]
Fair enough. Perhaps the easiest thing to do would be to turn the grouping on by default, so that people like me don't accidentally add hundreds of cubes that aren't easy to delete in a complex scene.

I'm not that familiar with blender, but perhaps it might be possible to put a custom property on each mesh instance stating which instancer it came from, and then you could have a "select all instances" button on the instancer node..

**Comment by naught101** [comment]
Actually, even with group selected, it doesn't really group the nodes: 

![ipcc_complexity1](https://cloud.githubusercontent.com/assets/167164/14064016/18626716-f43b-11e5-9ea6-74ce607e561a.png)

Also, the update doesn't always trigger when the input matrix changes, even with 'update' ticked (the cubes usually move correctly, when I add vectors to the matrix input, but not when I remove vectors. I'm using blender 2.74.

**Comment by zeffii** [comment]
OK, not all interactions with the UI trigger a full nodetree update. This is by design, but sometimes (like in this case) it means you'd need to cause updates to a node which precedes the matrix in. in order for the group tick/untick to take effect.

I'm tempted to make the default behaviour as you suggested, if the node is removed then so are the instances.. no ETA.

for convenience here's a link to the node so I don't have to look it up again:  
https://github.com/nortikin/sverchok/blob/master/nodes/basic_data/instancer.py

**Comment by zeffii** [comment]
Each object created by the _instancer_ does have a custom property assigned, that's what allows the node to delete instances if the matrix count shrinks between updates. Not a big bit of code needed, just some quiet time around here :)

**Comment by zeffii** [comment]
possibly:
```python
    def free(self):
        self.remove_non_updated_objects(-1, self.basemesh_name)
```
but that doesn't entirely exit clean either.. -- this I believe is a minor issue to solve but i dont have time
```text
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\core\update_system.py", line 318, in do_update_general
    node.process()
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\nodes\basic_data\instancer.py", line 188, in process
    make_or_update_instance(self, obj_name, matrix)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\nodes\basic_data\instancer.py", line 52, in make_or_update_instance
    mesh = meshes[mesh_name]
Node Sv Instancer Node had exception 'bpy_prop_collection[key]: key "" not found'
```

**Comment by zeffii** [comment]
there's a branch to test this:
https://github.com/nortikin/sverchok/tree/instance_remover

I refrain from pushing to master until more testing time becomes available.

**Comment by zeffii** [comment]
commited most of the fix

side note - 'ungrouping' doesn't work / was never implemented right. Didn't notice until just now.

**Comment by zeffii** [comment]
Your screenshot shows that you are using an aged version of Sverchok. Please update to the latest. ( (0, 5, 4, 5) 
![image](https://cloud.githubusercontent.com/assets/619340/14274604/9ef3e894-fb12-11e5-93c2-b50ac1288512.png)

**Comment by zeffii** [comment]
```python
    def process(self):
        (...)
        if self.grouping:
            self.to_group()
        else:
            self.ungroup()

    def to_group(self):
        (...)

    def ungroup(self):
        g = bpy.data.groups.get(self.basemesh_name)
        if g:
            bpy.data.groups.remove(g)
```

**Comment by zeffii** [comment]
hmm, mayble also do an ungroup / delete group in the `def free()`

**Comment by zeffii** [comment]
commit patch to master. I consider this closed for now.

**Comment by naught101** [comment]
Thank you, I'll try to get around to having a try of it soon.
