### ISSUE TITLE
INSPIRATION: Motion Graphics Periodic Table

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#861]
This is just for own notes, inspiration :+1: 
http://foxcodex.html.xdomain.jp/index.html

Most of them, I think I could replicate using Animation Nodes. I found it much simpler. Sverchok probably can as well, I wanted to give it a go. Sverchok is more challenging because it feels more abstract.

The Matryoshka Doll concept is still something I am exploring. Sverchok does the unpack and pack on the fly. But how does it work in "Loop".

ANYWAYS, I think Sverchok needs its own "Periodic Table".

Kind of like more in the Mesh Generation Element Nodes. What nodes are still missing or required, which are Sverchok is most powerful with, which algorithm, etc.

Because I think Sverchok is already powerful for:
- Generating Mesh: Vertex, Edge, Poly
- L-Tree
- Generative Art
- Algorithm like 
- Building parametric structure 
- Connecting points

See if that website can spark you some inspirations! :dancer:

**Comment by ly29** [comment]
If you find one any of those that you think should work, but are having trouble with, please, do ask.

**Comment by zeffii** [comment]
i did one in javascript with d3.js, all info stored in a csv
http://tributary.io/inlet/4470284/

**Comment by zeffii** [comment]
I think this is a great idea. A nice graphical interface to a collection of tutorials / .blends.

**Comment by ly29** [comment]
Yeah it is really nice page.

**Comment by zeffii** [comment]
i suggest fleshing out some examples and maybe have two tables

1. for modular independant concepts: _functions_

  - [ ] arcs
  - [ ] splines
  - [ ] lofting
  - [ ] extruding
  - [ ] interpolating
  - [ ] making meshes
  - [ ] outputting curves
  - [ ] csg booleans
  - [ ] matrix transforms
  - [ ] arrays
  - [ ] mesh instancing
  - [ ] vector match
  - [ ] scalar math
  - [ ] list math
  - [ ] convex hull
  - [ ] delauney
  - [ ] voronoi
  - [ ] vertex colors
  - [ ] script notes (only mk3)
  - etc

2. for methods that bring a variety of concepts together: _modules_.
  
  - [ ] transforming array items
  ...
 
rather than

**Comment by zeffii** [comment]
We can set up a separate sverchok_examples repo and store .blends in there and make the https://sverchok.com/sverchok_examples gh-page quite a neat landing page.

but i dunno , work++ atm :/
