### ISSUE TITLE
Exploring Bounding Box and Stacking 

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#925]
![screen shot 2016-10-20 at 21 01 34](https://cloud.githubusercontent.com/assets/3952687/19555425/837c6612-9708-11e6-8c18-8390baa8202d.png)

I have probably asked this at some point and didn't study it. But anyhow, if I have bunch of objects and would like to stack one over each other by investigating the Bounding Box, can we do this in a sane and simple way?

I was thinking, if object A - C is sourced.

A => placed on the ground by selected DMINZ (dimension minimum in Z),
then B should be placed at the DMAXZ of A, 
then C placed at DMANXZ of B,
and so on.

With Bounding Box node, we can have the center, but how to project that center to get the top and the bottom point?

**Comment by enzyme69** [comment]
https://gist.github.com/3fc83dbe0134def6c52a9d180cc4d996

**Comment by zeffii** [comment]
i agree this is not the simplest thing to do just via Sverchok's nodes, i _will_ add a mode to `List_Modifier`'s Accumulate Sum. (that starts with 0 and cuts off the last item)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/19559062/32d18cc2-96ce-11e6-93d1-039b5cf78b53.png)

[herrrr.zip](https://github.com/nortikin/sverchok/files/541619/herrrr.zip)

**Comment by nortikin** [comment]
maybe make node 'bounds' that get min max xyz and finds dimentions?

**Comment by nortikin** [comment]
Dimentions node

**Comment by enzyme69** [comment]
Thanks so much! I will have a study maybe make video about this. I always want to stack some boxes!

**Comment by nortikin** [comment]
https://gist.github.com/nortikin/3b9258cc23c9c1416c63c632678938c8
@enzyme69 
this is scripted node objects' dimentions

**Comment by gerroon** [comment]
@zeffii 

I am trying this setup based on your screenshot, It seems to work (although the scenes and the gist do not work due to the given list levels) It is all good but I get garbled polygons when I try to use list shuffle to randomize the objects order.

I am wondering if you could offer insight into why this is not working. 
I am on Blender 2.92, Sverchok 0.6


thanks

![blender_hHHjvhNZil](https://user-images.githubusercontent.com/8519469/109901039-f0483980-7c5d-11eb-954e-4227eb3f76ae.jpg)

![blender_DncgmVNrzT](https://user-images.githubusercontent.com/8519469/109901056-f807de00-7c5d-11eb-9a6d-dba2491b90d9.jpg)

**Comment by nortikin** [comment]
@gerroon ohohoh
1. list shuffle on polygons not working somehow. idonno what is wrong. seems ok.
2. use bound box size button to get size directly

**Comment by nortikin** [comment]
https://gist.github.com/e55b03b151b320005eac4333a486fe6f

**Comment by gerroon** [comment]
@nortikin 

Thanks for the new gist.

Is your setup going to work with shuffle? I still need to randomize the order of the stacked objects.

**Comment by gerroon** [comment]
Ok your initial setup works but when I try randomizing elements, I am getting empty spots (used randomized list item instead of shuffle)


https://user-images.githubusercontent.com/8519469/109997657-08f43600-7cd6-11eb-9bda-06190ec412d0.mp4

**Comment by nortikin** [comment]
> Is your setup going to work with shuffle?

no, it is about bounds on Z
i still do not understand what is wrong

**Comment by gerroon** [comment]
> > Is your setup going to work with shuffle?
> 
> no, it is about bounds on Z
> i still do not understand what is wrong
> 
> https://gist.github.com/4075ea279902aace3f44513100caaedb
> this works

Thanks for the update, I just removed the SV generated objects and pluged the actual test objects  (since I need to use real objects at some point) and still misses spots in the stack.

![blender_clLsOfR030](https://user-images.githubusercontent.com/8519469/110001584-20352280-7cda-11eb-9eb6-bad45adfaeaf.jpg)

**Comment by gerroon** [comment]
Nevermind, I think those missing spots are from the "disk" , for some reason it is not drawing the internal polygons of the disk

![blender_fge8x98fOQ](https://user-images.githubusercontent.com/8519469/110002027-946fc600-7cda-11eb-941c-dd2453e0fd65.jpg)

**Comment by nortikin** [comment]
> Nevermind, I think those missing spots are from the "circle" , for some reason it is not drawing the internal polygons of the disk
> 
> ![blender_fge8x98fOQ](https://user-images.githubusercontent.com/8519469/110002027-946fc600-7cda-11eb-941c-dd2453e0fd65.jpg)

ahaha!!! cool. but that situation took place on polygons list shuffle to me with planes... how?

**Comment by nortikin** [comment]
[cuts.zip](https://github.com/nortikin/sverchok/files/6085770/cuts.zip)
try that figure, i added basepoint shift
