### ISSUE TITLE
Viewer Text Update is strange and something strange about this setup

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#945]
I think Viewer Text MK2 has issue when update is checked, in this setup:
https://gist.github.com/0f018dcb2b8126935801fdc421c451ac

And also above, I wonder why the Resulting Arcs seems to get double transformation.

![screen shot 2016-11-04 at 18 47 27](https://cloud.githubusercontent.com/assets/3952687/19998149/2b4c3248-a2bf-11e6-80b3-a8c10ae42aa7.png)

Trying to make proper centipede, which later be animated as well. But don't want to be too complex.

**Comment by zeffii** [comment]
if you remove the matrix input into the ViewerDraw, you'll notice that each Spline is made up by the coordinates that you had fed in earlier, when you then add a matrix for each spline you will get further transformation.

either remove the matrix, or instead of using Line input into the 2pt spline uses a vector (0,0,0).

**Comment by zeffii** [comment]
https://gist.github.com/c84bb92cf8366c7b393692d896758083

**Comment by zeffii** [comment]
maybe you can be clearer about what issue you're experiencing w/regard to the TextViewer.
