### ISSUE TITLE
is it possible not to update the whole tree when connecting nodes.

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#989]
Intersect Edge node is a bit slow, when calculating, that is ok, but the fact that Sverchok node tree seems to have to re-calculate for every node changes, is difficult.

Whenever plugging and and plugging noodles, is it possible not to update the tree? Only when the data is dirty?

**Comment by nortikin** [comment]
switch off process layout "P" button in "N" panel
http://nikitron.cc.ua/sverch/html/panels.html#node-tree-panel

**Comment by zeffii** [comment]
_Intersect Edges_ speed decreases as a function of the amount of intersecting geometry. I have considered reimplementing it with BVH but didn't get around to it.

I think your real question here is more general. "Does Sverchok's update mechanism only update nodes downstream from the currently updated node?" .

**Comment by zeffii** [comment]
i agree with @enzyme69 there are still a few scenarios where partial update isn't used yet. 
- node noodle interaction
- click on a socket
- add node to tree.

example in this layout..
https://gist.github.com/b8950df9999a4b5290fbf90e7e86fcc8

**Comment by zeffii** [comment]
@ly29, if you have time, could you clarify some of this? You've invested more time than any of us on this mechanism.

**Comment by enzyme69** [comment]
Kind of missing @ly29 by now. Hope he is alright! I have to dig some post by him, lots of learning gems.

**Comment by ly29** [comment]
Well, it can certainly be done and I agree that it would be useful, even in a limited form.

The problem is the following:
Given a directed acyclic graph, we can call it NT, detect which changes has happened between subsequent calls to ```update```. 
Any number of nodes might have been removed or added.
Any number of links might have been removed or added.
After detecting the changes see if and how they affect the calculated state of NT, and if necessary recalculate what is needed.

It is a hard problem to solve in good way since there are a number of edge cases, I just didn't feel like spending time on it. 

But there are some simple subproblems that could help a lot. 
- Don't update when a link is invalid (doesn't have two ends)
- Don't update if the links don't change
- Add one node downstream in a given DAG,
For more complex problems it would give but and do a full update.

Some more state would have to be kept but not that much would have to change I think, but honestly the update code is bit of mess even though it has keep working quite well...

**Comment by ly29** [comment]
Looking at the I think a total re factoring is in order anyway.
Somethings we could dump, like the heat map and bring back later if we feel it is needed, such things would simply a transition.

**Comment by zeffii** [comment]
let it be known that these issues are known and understood.
